import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';

import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { Prisma, PrismaClient } from '@prisma/client';
import { Client } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const runDatabaseTests = process.env.RUN_DATABASE_INTEGRITY_TESTS === '1';
const databaseUrl = process.env.DATABASE_URL;
const describeDatabase = runDatabaseTests && databaseUrl ? describe : describe.skip;
const migrationPath =
  'prisma/migrations/20260724120000_enforce_account_owned_subscription_allocations/migration.sql';

describeDatabase('account-owned subscription allocation database invariant', () => {
  const schema = `allocation_ownership_${randomUUID().replaceAll('-', '')}`;
  const quotedSchema = `"${schema}"`;
  let client: Client;
  let prisma: PrismaClient;

  async function seedBaseFixture() {
    await client.query(`
      INSERT INTO "TradingAccount" ("id") VALUES (1), (2);
      INSERT INTO "Subscription" ("id") VALUES (10), (11), (12);
      INSERT INTO "TradingAccountAllocation" ("id", "tradingAccountId", "key", "name")
      VALUES (100, 1, 'primary', 'Primary'), (200, 2, 'other', 'Other');
    `);
  }

  beforeAll(async () => {
    client = new Client({ connectionString: databaseUrl });
    await client.connect();
    await client.query(`CREATE SCHEMA ${quotedSchema}`);
    await client.query(`SET search_path TO ${quotedSchema}`);
    await client.query(`
      CREATE TABLE "TradingAccount" ("id" integer PRIMARY KEY);
      CREATE TABLE "Subscription" ("id" integer PRIMARY KEY);
      CREATE TABLE "TradingAccountAllocation" (
        "id" integer PRIMARY KEY,
        "tradingAccountId" integer NOT NULL REFERENCES "TradingAccount"("id"),
        "key" text NOT NULL,
        "name" text NOT NULL,
        "description" text,
        "enabled" boolean NOT NULL DEFAULT true,
        "maxAllocatedNotional" double precision,
        "maxOpenPositions" integer,
        "maxPositionNotional" double precision,
        "notes" text,
        "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE "TradingAccountSubscription" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "tradingAccountId" integer NOT NULL REFERENCES "TradingAccount"("id"),
        "subscriptionId" integer NOT NULL REFERENCES "Subscription"("id"),
        "allocationId" integer,
        "enabled" boolean NOT NULL DEFAULT true,
        "entriesEnabled" boolean NOT NULL DEFAULT true,
        "exitsEnabled" boolean NOT NULL DEFAULT true,
        "sizingType" text NOT NULL DEFAULT 'FIXED_QTY',
        "fixedQty" double precision,
        "maxPositionNotional" double precision,
        "reservedNotional" double precision,
        "minPositionNotional" double precision,
        "maxQty" double precision,
        "notes" text,
        "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "TradingAccountSubscription_tradingAccountId_subscriptionId_key"
          UNIQUE ("tradingAccountId", "subscriptionId"),
        CONSTRAINT "TradingAccountSubscription_allocationId_fkey"
          FOREIGN KEY ("allocationId") REFERENCES "TradingAccountAllocation"("id")
          ON DELETE SET NULL ON UPDATE CASCADE
      );
    `);
    await seedBaseFixture();
    const migrationSql = await readFile(migrationPath, 'utf8');
    await client.query(migrationSql);

    prisma = new PrismaClient({
      adapter: new PrismaPg({
        connectionString: databaseUrl,
        options: `-c search_path=${schema}`,
      }),
    });
  });

  afterAll(async () => {
    await prisma?.$disconnect();
    if (client) {
      await client.query(`DROP SCHEMA IF EXISTS ${quotedSchema} CASCADE`);
      await client.end();
    }
  });

  it('accepts same-account and null allocations, including duplicate allocation use', async () => {
    await client.query(`
      INSERT INTO "TradingAccountSubscription"
        ("tradingAccountId", "subscriptionId", "allocationId")
      VALUES (1, 10, 100), (1, 11, 100), (2, 12, NULL)
    `);
    const result = await client.query(
      'SELECT "allocationId" FROM "TradingAccountSubscription" ORDER BY "subscriptionId"'
    );
    expect(result.rows.map((row) => row.allocationId)).toEqual([100, 100, null]);
  });

  it('rejects direct cross-account inserts and updates with the named foreign key', async () => {
    await expect(
      client.query(`
        INSERT INTO "TradingAccountSubscription"
          ("tradingAccountId", "subscriptionId", "allocationId")
        VALUES (2, 10, 100)
      `)
    ).rejects.toMatchObject({
      code: '23503',
      constraint:
        'TradingAccountSubscription_allocationId_tradingAccountId_fkey',
    });

    await client.query(`
      INSERT INTO "TradingAccountSubscription"
        ("tradingAccountId", "subscriptionId", "allocationId")
      VALUES (2, 10, 200)
    `);
    await expect(
      client.query(`
        UPDATE "TradingAccountSubscription"
        SET "allocationId" = 100
        WHERE "tradingAccountId" = 2 AND "subscriptionId" = 10
      `)
    ).rejects.toMatchObject({
      code: '23503',
      constraint:
        'TradingAccountSubscription_allocationId_tradingAccountId_fkey',
    });
  });

  it('rejects an unchecked Prisma cross-account write', async () => {
    await expect(
      prisma.tradingAccountSubscription.create({
        data: {
          tradingAccountId: 2,
          subscriptionId: 11,
          allocationId: 100,
        } as Prisma.TradingAccountSubscriptionUncheckedCreateInput,
      })
    ).rejects.toMatchObject({ code: 'P2003' });
  });

  it('restricts allocation ownership changes and deletion while referenced', async () => {
    await expect(
      client.query(`
        UPDATE "TradingAccountAllocation"
        SET "tradingAccountId" = 2
        WHERE "id" = 100
      `)
    ).rejects.toMatchObject({
      code: '23503',
      constraint:
        'TradingAccountSubscription_allocationId_tradingAccountId_fkey',
    });
    await expect(
      client.query('DELETE FROM "TradingAccountAllocation" WHERE "id" = 100')
    ).rejects.toMatchObject({
      code: '23503',
      constraint:
        'TradingAccountSubscription_allocationId_tradingAccountId_fkey',
    });
  });

  it('preserves the unique account/subscription assignment constraint', async () => {
    await expect(
      client.query(`
        INSERT INTO "TradingAccountSubscription"
          ("tradingAccountId", "subscriptionId", "allocationId")
        VALUES (1, 10, 100)
      `)
    ).rejects.toMatchObject({
      code: '23505',
      constraint:
        'TradingAccountSubscription_tradingAccountId_subscriptionId_key',
    });
  });
});

describeDatabase('account-owned subscription allocation migration preflight', () => {
  async function withFixture(
    seedSql: string,
    assertion: (client: Client, migrationSql: string) => Promise<void>
  ) {
    const schema = `allocation_preflight_${randomUUID().replaceAll('-', '')}`;
    const quotedSchema = `"${schema}"`;
    const client = new Client({ connectionString: databaseUrl });
    await client.connect();
    try {
      await client.query(`CREATE SCHEMA ${quotedSchema}`);
      await client.query(`SET search_path TO ${quotedSchema}`);
      await client.query(`
        CREATE TABLE "TradingAccountAllocation" (
          "id" integer PRIMARY KEY,
          "tradingAccountId" integer NOT NULL
        );
        CREATE TABLE "TradingAccountSubscription" (
          "id" integer PRIMARY KEY,
          "tradingAccountId" integer NOT NULL,
          "allocationId" integer,
          CONSTRAINT "TradingAccountSubscription_allocationId_fkey"
            FOREIGN KEY ("allocationId") REFERENCES "TradingAccountAllocation"("id")
            ON DELETE SET NULL ON UPDATE CASCADE
        );
        ${seedSql}
      `);
      await assertion(client, await readFile(migrationPath, 'utf8'));
    } finally {
      await client.query(`DROP SCHEMA IF EXISTS ${quotedSchema} CASCADE`);
      await client.end();
    }
  }

  it('aborts on existing cross-account references before changing constraints', async () => {
    await withFixture(
      `
        INSERT INTO "TradingAccountAllocation" VALUES (100, 1);
        INSERT INTO "TradingAccountSubscription" VALUES (1, 2, 100);
      `,
      async (client, migrationSql) => {
        await expect(client.query(migrationSql)).rejects.toThrow(
          /1 assignment\(s\) reference a TradingAccountAllocation owned by another TradingAccount/
        );
        const oldConstraint = await client.query(`
          SELECT 1
          FROM information_schema.table_constraints
          WHERE table_schema = current_schema()
            AND constraint_name = 'TradingAccountSubscription_allocationId_fkey'
        `);
        expect(oldConstraint.rowCount).toBe(1);
      }
    );
  });

  it('migrates valid and dormant null-allocation fixtures', async () => {
    await withFixture(
      `
        INSERT INTO "TradingAccountAllocation" VALUES (100, 1);
        INSERT INTO "TradingAccountSubscription"
        VALUES (1, 1, 100), (2, 2, NULL);
      `,
      async (client, migrationSql) => {
        await client.query(migrationSql);
        const result = await client.query(`
          SELECT "allocationId"
          FROM "TradingAccountSubscription"
          ORDER BY "id"
        `);
        expect(result.rows.map((row) => row.allocationId)).toEqual([100, null]);
      }
    );
  });
});
