import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import 'dotenv/config';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Client } from 'pg';
import {
  deriveAdvisoryLockKey,
  withTradingAccountWorkflowLock,
} from '../../services/trading-account-workflow-lock.service.js';

const runDatabaseTests = process.env.RUN_DATABASE_INTEGRITY_TESTS === '1';
const databaseUrl = process.env.DATABASE_URL;
const describeDatabase = runDatabaseTests && databaseUrl ? describe : describe.skip;
const migrationPath =
  'prisma/migrations/20260726120000_add_account_worker_health_and_active_position_uniqueness/migration.sql';

describeDatabase('account workflow locks and active position uniqueness', () => {
  const schema = `account_worker_lock_${randomUUID().replaceAll('-', '')}`;
  const quotedSchema = `"${schema}"`;
  let admin: Client;

  beforeAll(async () => {
    admin = new Client({ connectionString: databaseUrl });
    await admin.connect();
    await admin.query(`CREATE SCHEMA ${quotedSchema}`);
    await admin.query(`SET search_path TO ${quotedSchema}`);
    await admin.query(`
      CREATE TABLE "TradingAccount" ("id" integer PRIMARY KEY);
      CREATE TABLE "TrackedPosition" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "tradingAccountId" integer,
        broker text NOT NULL,
        symbol text NOT NULL,
        status text NOT NULL
      );
      INSERT INTO "TradingAccount" ("id") VALUES (1), (2);
    `);
    await admin.query(await readFile(migrationPath, 'utf8'));
  });

  afterAll(async () => {
    await admin?.query(`DROP SCHEMA IF EXISTS ${quotedSchema} CASCADE`);
    await admin?.end();
  });

  async function connectedClient() {
    const client = new Client({ connectionString: databaseUrl });
    await client.connect();
    return client;
  }

  it('allows only one session to own the same account/workflow lock', async () => {
    const first = await connectedClient();
    const second = await connectedClient();
    const key = deriveAdvisoryLockKey('ai-trader:reconciliation:1').toString();
    expect((await first.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [key])).rows[0]?.acquired).toBe(true);
    expect((await second.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [key])).rows[0]?.acquired).toBe(false);
    await first.query('SELECT pg_advisory_unlock($1::bigint)', [key]);
    expect((await second.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [key])).rows[0]?.acquired).toBe(true);
    await second.query('SELECT pg_advisory_unlock($1::bigint)', [key]);
    await first.end();
    await second.end();
  });

  it('does not let one account lock block another account', async () => {
    const first = await connectedClient();
    const second = await connectedClient();
    const paper = deriveAdvisoryLockKey('ai-trader:order-lifecycle:1').toString();
    const live = deriveAdvisoryLockKey('ai-trader:order-lifecycle:2').toString();
    expect((await first.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [paper])).rows[0]?.acquired).toBe(true);
    expect((await second.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [live])).rows[0]?.acquired).toBe(true);
    await first.end();
    await second.end();
  });

  it('releases a session lock when the owning connection closes', async () => {
    const owner = await connectedClient();
    const contender = await connectedClient();
    const key = deriveAdvisoryLockKey('ai-trader:exit-evaluation:1').toString();
    await owner.query('SELECT pg_advisory_lock($1::bigint)', [key]);
    await owner.end();
    expect((await contender.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [key])).rows[0]?.acquired).toBe(true);
    await contender.end();
  });

  it('enforces account-scoped active cycles while preserving history', async () => {
    await admin.query(`
      INSERT INTO "TrackedPosition" ("tradingAccountId", broker, symbol, status)
      VALUES
        (1, 'alpaca', 'AAPL', 'open'),
        (2, 'ALPACA', 'aapl', 'closing'),
        (1, 'alpaca', 'AAPL', 'closed'),
        (1, 'alpaca', 'AAPL', 'closed'),
        (NULL, 'alpaca', 'AAPL', 'open'),
        (NULL, 'alpaca', 'AAPL', 'closing')
    `);
    await expect(admin.query(`
      INSERT INTO "TrackedPosition" ("tradingAccountId", broker, symbol, status)
      VALUES (1, 'ALPACA', 'aapl', 'closing')
    `)).rejects.toThrow(/TrackedPosition_active_account_broker_symbol_key/);
    await admin.query(`
      INSERT INTO "TrackedPosition" ("tradingAccountId", broker, symbol, status)
      VALUES (1, 'alpaca', 'MSFT', 'closed'), (1, 'alpaca', 'MSFT', 'open')
    `);
  });

  it('keeps Paper and Live health and backoff rows independent', async () => {
    await admin.query(`
      INSERT INTO "TradingAccountWorkerHealthState"
        ("tradingAccountId", "workerKey", "processInstanceId",
         "expectedIntervalMs", "lastOutcome", "consecutiveFailures",
         "backoffUntil", "lastError", "updatedAt")
      VALUES
        (1, 'exit_evaluation', 'paper-process', 2000, 'success', 0,
         NULL, NULL, CURRENT_TIMESTAMP),
        (2, 'exit_evaluation', 'live-process', 2000, 'failure', 2,
         CURRENT_TIMESTAMP + interval '15 seconds', 'mock Live failure',
         CURRENT_TIMESTAMP)
    `);
    const result = await admin.query(`
      SELECT "tradingAccountId", "lastOutcome", "consecutiveFailures",
             "backoffUntil" IS NOT NULL AS "backingOff"
      FROM "TradingAccountWorkerHealthState"
      WHERE "workerKey" = 'exit_evaluation'
      ORDER BY "tradingAccountId"
    `);
    expect(result.rows).toEqual([
      { tradingAccountId: 1, lastOutcome: 'success', consecutiveFailures: 0, backingOff: false },
      { tradingAccountId: 2, lastOutcome: 'failure', consecutiveFailures: 2, backingOff: true },
    ]);
    await expect(admin.query(`
      INSERT INTO "TradingAccountWorkerHealthState"
        ("tradingAccountId", "workerKey", "processInstanceId",
         "expectedIntervalMs", "updatedAt")
      VALUES (1, 'exit_evaluation', 'duplicate', 2000, CURRENT_TIMESTAMP)
    `)).rejects.toThrow(/TradingAccountWorkerHealthState_tradingAccountId_workerKey_key/);
  });

  it('derives distinct stable keys and rejects a synthetic account lock', async () => {
    const paper = deriveAdvisoryLockKey('ai-trader:order-lifecycle:1');
    const live = deriveAdvisoryLockKey('ai-trader:order-lifecycle:2');
    const paperExit = deriveAdvisoryLockKey('ai-trader:exit-evaluation:1');
    expect(paper).not.toBe(live);
    expect(paper).not.toBe(paperExit);
    await expect(withTradingAccountWorkflowLock({
      tradingAccountId: 0,
      workflowKey: 'order-lifecycle',
      processInstanceId: 'test',
      execute: async () => undefined,
    })).rejects.toThrow(/real positive tradingAccountId/);
  });

  it('aborts migration explicitly when duplicate active cycles pre-exist', async () => {
    const duplicateSchema = `duplicate_active_${randomUUID().replaceAll('-', '')}`;
    const duplicateQuoted = `"${duplicateSchema}"`;
    const client = await connectedClient();
    try {
      await client.query(`CREATE SCHEMA ${duplicateQuoted}; SET search_path TO ${duplicateQuoted}`);
      await client.query(`
        CREATE TABLE "TradingAccount" ("id" integer PRIMARY KEY);
        CREATE TABLE "TrackedPosition" (
          "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "tradingAccountId" integer, broker text NOT NULL, symbol text NOT NULL, status text NOT NULL
        );
        INSERT INTO "TradingAccount" ("id") VALUES (1);
        INSERT INTO "TrackedPosition" ("tradingAccountId", broker, symbol, status)
        VALUES (1, 'alpaca', 'DIA', 'open'), (1, 'ALPACA', 'dia', 'closing');
      `);
      await expect(client.query(await readFile(migrationPath, 'utf8')))
        .rejects.toThrow(/1 duplicate group\(s\).*account=1 broker=alpaca symbol=DIA count=2/);
    } finally {
      await client.query('ROLLBACK');
      await client.query(`DROP SCHEMA IF EXISTS ${duplicateQuoted} CASCADE`);
      await client.end();
    }
  });
});
