import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import 'dotenv/config';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Client } from 'pg';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import {
  deriveAdvisoryLockKey,
  withTradingAccountWorkflowLock,
} from '../../services/trading-account-workflow-lock.service.js';
import {
  recordTradingAccountWorkflowLockContention,
  recordTradingAccountWorkerAttempt,
  startTradingAccountWorkerRun,
} from '../../services/trading-account-worker-health.service.js';

const runDatabaseTests = process.env.RUN_DATABASE_INTEGRITY_TESTS === '1';
const databaseUrl = process.env.DATABASE_URL;
const describeDatabase = runDatabaseTests && databaseUrl ? describe : describe.skip;
const migrationPath =
  'prisma/migrations/20260726120000_add_account_worker_health_and_active_position_uniqueness/migration.sql';

describeDatabase('account workflow locks and active position uniqueness', () => {
  const schema = `account_worker_lock_${randomUUID().replaceAll('-', '')}`;
  const quotedSchema = `"${schema}"`;
  let admin: Client;

  beforeAll(async () => {
    admin = new Client({ connectionString: databaseUrl });
    await admin.connect();
    await admin.query(`CREATE SCHEMA ${quotedSchema}`);
    await admin.query(`SET search_path TO ${quotedSchema}`);
    await admin.query(`
      CREATE TABLE "TradingAccount" (
        "id" integer PRIMARY KEY,
        "displayName" text NOT NULL DEFAULT 'Test Account',
        environment text NOT NULL DEFAULT 'PAPER'
      );
      CREATE TABLE "TrackedPosition" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "tradingAccountId" integer,
        broker text NOT NULL,
        symbol text NOT NULL,
        status text NOT NULL
      );
      INSERT INTO "TradingAccount" ("id") VALUES (1), (2);
    `);
    await admin.query(await readFile(migrationPath, 'utf8'));
  });

  afterAll(async () => {
    await admin?.query(`DROP SCHEMA IF EXISTS ${quotedSchema} CASCADE`);
    await admin?.end();
  });

  async function connectedClient() {
    const client = new Client({ connectionString: databaseUrl });
    await client.connect();
    return client;
  }

  function isolatedPrisma() {
    const url = new URL(databaseUrl!);
    url.searchParams.set('schema', schema);
    return new PrismaClient({
      adapter: new PrismaPg({ connectionString: url.toString() }),
    });
  }

  it('allows only one session to own the same account/workflow lock', async () => {
    const first = await connectedClient();
    const second = await connectedClient();
    const key = deriveAdvisoryLockKey('ai-trader:reconciliation:1').toString();
    expect((await first.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [key])).rows[0]?.acquired).toBe(true);
    expect((await second.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [key])).rows[0]?.acquired).toBe(false);
    await first.query('SELECT pg_advisory_unlock($1::bigint)', [key]);
    expect((await second.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [key])).rows[0]?.acquired).toBe(true);
    await second.query('SELECT pg_advisory_unlock($1::bigint)', [key]);
    await first.end();
    await second.end();
  });

  it('does not let one account lock block another account', async () => {
    const first = await connectedClient();
    const second = await connectedClient();
    const paper = deriveAdvisoryLockKey('ai-trader:order-lifecycle:1').toString();
    const live = deriveAdvisoryLockKey('ai-trader:order-lifecycle:2').toString();
    expect((await first.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [paper])).rows[0]?.acquired).toBe(true);
    expect((await second.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [live])).rows[0]?.acquired).toBe(true);
    await first.end();
    await second.end();
  });

  it('releases a session lock when the owning connection closes', async () => {
    const owner = await connectedClient();
    const contender = await connectedClient();
    const key = deriveAdvisoryLockKey('ai-trader:exit-evaluation:1').toString();
    await owner.query('SELECT pg_advisory_lock($1::bigint)', [key]);
    await owner.end();
    expect((await contender.query('SELECT pg_try_advisory_lock($1::bigint) acquired', [key])).rows[0]?.acquired).toBe(true);
    await contender.end();
  });

  it('enforces account-scoped active cycles while preserving history', async () => {
    await admin.query(`
      INSERT INTO "TrackedPosition" ("tradingAccountId", broker, symbol, status)
      VALUES
        (1, 'alpaca', 'AAPL', 'open'),
        (2, 'ALPACA', 'aapl', 'closing'),
        (1, 'alpaca', 'AAPL', 'closed'),
        (1, 'alpaca', 'AAPL', 'closed'),
        (NULL, 'alpaca', 'AAPL', 'open'),
        (NULL, 'alpaca', 'AAPL', 'closing')
    `);
    await expect(admin.query(`
      INSERT INTO "TrackedPosition" ("tradingAccountId", broker, symbol, status)
      VALUES (1, 'ALPACA', 'aapl', 'closing')
    `)).rejects.toThrow(/TrackedPosition_active_account_broker_symbol_key/);
    await admin.query(`
      INSERT INTO "TrackedPosition" ("tradingAccountId", broker, symbol, status)
      VALUES (1, 'alpaca', 'MSFT', 'closed'), (1, 'alpaca', 'MSFT', 'open')
    `);
  });

  it('keeps Paper and Live health and backoff rows independent', async () => {
    await admin.query(`
      INSERT INTO "TradingAccountWorkerHealthState"
        ("tradingAccountId", "workerKey", "processInstanceId",
         "expectedIntervalMs", "lastOutcome", "consecutiveFailures",
         "backoffUntil", "lastError", "updatedAt")
      VALUES
        (1, 'exit_evaluation', 'paper-process', 2000, 'success', 0,
         NULL, NULL, CURRENT_TIMESTAMP),
        (2, 'exit_evaluation', 'live-process', 2000, 'failure', 2,
         CURRENT_TIMESTAMP + interval '15 seconds', 'mock Live failure',
         CURRENT_TIMESTAMP)
    `);
    const result = await admin.query(`
      SELECT "tradingAccountId", "lastOutcome", "consecutiveFailures",
             "backoffUntil" IS NOT NULL AS "backingOff"
      FROM "TradingAccountWorkerHealthState"
      WHERE "workerKey" = 'exit_evaluation'
      ORDER BY "tradingAccountId"
    `);
    expect(result.rows).toEqual([
      { tradingAccountId: 1, lastOutcome: 'success', consecutiveFailures: 0, backingOff: false },
      { tradingAccountId: 2, lastOutcome: 'failure', consecutiveFailures: 2, backingOff: true },
    ]);
    await expect(admin.query(`
      INSERT INTO "TradingAccountWorkerHealthState"
        ("tradingAccountId", "workerKey", "processInstanceId",
         "expectedIntervalMs", "updatedAt")
      VALUES (1, 'exit_evaluation', 'duplicate', 2000, CURRENT_TIMESTAMP)
    `)).rejects.toThrow(/TradingAccountWorkerHealthState_tradingAccountId_workerKey_key/);
  });

  it('makes finalized health visible before another process can acquire the workflow lock', async () => {
    const owner = await connectedClient();
    const contender = await connectedClient();
    const key = deriveAdvisoryLockKey('ai-trader:broker-activity:1').toString();
    try {
      await owner.query(`SET search_path TO ${quotedSchema}`);
      await contender.query(`SET search_path TO ${quotedSchema}`);
      expect((await owner.query(
        'SELECT pg_try_advisory_lock($1::bigint) acquired',
        [key]
      )).rows[0]?.acquired).toBe(true);

      await owner.query(`
        INSERT INTO "TradingAccountWorkerHealthState"
          ("tradingAccountId", "workerKey", "processInstanceId",
           "expectedIntervalMs", "currentRunStartedAt", "lastTickStartedAt", "updatedAt")
        VALUES
          (1, 'broker_activity_sync', 'owner-process', 30000,
           CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
      `);
      await owner.query(`
        UPDATE "TradingAccountWorkerHealthState"
        SET "currentRunStartedAt" = NULL,
            "lastTickCompletedAt" = CURRENT_TIMESTAMP,
            "lastSucceededAt" = CURRENT_TIMESTAMP,
            "lastOutcome" = 'success',
            "updatedAt" = CURRENT_TIMESTAMP
        WHERE "tradingAccountId" = 1 AND "workerKey" = 'broker_activity_sync'
      `);

      expect((await contender.query(
        'SELECT pg_try_advisory_lock($1::bigint) acquired',
        [key]
      )).rows[0]?.acquired).toBe(false);
      await owner.query('SELECT pg_advisory_unlock($1::bigint)', [key]);
      expect((await contender.query(
        'SELECT pg_try_advisory_lock($1::bigint) acquired',
        [key]
      )).rows[0]?.acquired).toBe(true);

      const state = await contender.query(`
        SELECT "currentRunStartedAt", "lastOutcome", "lastSucceededAt"
        FROM "TradingAccountWorkerHealthState"
        WHERE "tradingAccountId" = 1 AND "workerKey" = 'broker_activity_sync'
      `);
      expect(state.rows[0]).toMatchObject({
        currentRunStartedAt: null,
        lastOutcome: 'success',
        lastSucceededAt: expect.any(Date),
      });
    } finally {
      await owner.end();
      await contender.end();
    }
  });

  it('preserves the active owner through contention and detects its later interruption once', async () => {
    const owner = await connectedClient();
    const contender = await connectedClient();
    const nextOwner = await connectedClient();
    const db = isolatedPrisma();
    const interruptedEvents: unknown[] = [];
    const contentionEvents: unknown[] = [];
    const key = deriveAdvisoryLockKey('ai-trader:pending-orders:1').toString();
    const ownerStartedAt = new Date('2026-07-26T20:10:00.000Z');
    const contentionAt = new Date('2026-07-26T20:10:01.000Z');
    let contenderWorkflowCalls = 0;
    let ownerClosed = false;
    try {
      await db.tradingAccountWorkerHealthState.deleteMany({
        where: { tradingAccountId: 1, workerKey: 'pending_order_processing' },
      });
      expect((await owner.query(
        'SELECT pg_try_advisory_lock($1::bigint) acquired',
        [key]
      )).rows[0]?.acquired).toBe(true);
      await startTradingAccountWorkerRun({
        tradingAccountId: 1,
        workerKey: 'pending_order_processing',
        processInstanceId: 'owner-a',
        startedAt: ownerStartedAt,
      }, {
        db,
        emitSystemEvent: async (event) => {
          interruptedEvents.push(event);
          return {} as never;
        },
      });

      const acquiredByContender = (await contender.query(
        'SELECT pg_try_advisory_lock($1::bigint) acquired',
        [key]
      )).rows[0]?.acquired;
      expect(acquiredByContender).toBe(false);
      if (acquiredByContender) contenderWorkflowCalls += 1;
      await recordTradingAccountWorkflowLockContention({
        tradingAccountId: 1,
        workerKey: 'pending_order_processing',
        contenderProcessInstanceId: 'contender-b',
        lockFamily: 'pending-orders',
        attemptedAt: contentionAt,
      }, {
        db,
        emitSystemEvent: async (event) => {
          contentionEvents.push(event);
          return {} as never;
        },
      });

      const contended = await db.tradingAccountWorkerHealthState.findUniqueOrThrow({
        where: { tradingAccountId_workerKey: {
          tradingAccountId: 1,
          workerKey: 'pending_order_processing',
        } },
      });
      expect(contenderWorkflowCalls).toBe(0);
      expect(contended).toMatchObject({
        processInstanceId: 'owner-a',
        currentRunStartedAt: ownerStartedAt,
        lastTickStartedAt: ownerStartedAt,
        lastTickCompletedAt: null,
        totalLockSkips: 1,
        consecutiveFailures: 0,
        backoffUntil: null,
      });
      expect(contended.lastSummaryJson).toMatchObject({
        contenderProcessInstanceId: 'contender-b',
      });
      expect(contentionEvents).toHaveLength(1);

      await owner.end();
      ownerClosed = true;
      expect((await nextOwner.query(
        'SELECT pg_try_advisory_lock($1::bigint) acquired',
        [key]
      )).rows[0]?.acquired).toBe(true);
      await startTradingAccountWorkerRun({
        tradingAccountId: 1,
        workerKey: 'pending_order_processing',
        processInstanceId: 'owner-c',
        startedAt: new Date('2026-07-26T20:11:00.000Z'),
      }, {
        db,
        emitSystemEvent: async (event) => {
          interruptedEvents.push(event);
          return {} as never;
        },
      });
      expect(interruptedEvents).toHaveLength(1);
      expect(interruptedEvents[0]).toMatchObject({
        type: 'account_worker_health.interrupted',
        payloadJson: expect.objectContaining({
          previousProcessInstanceId: 'owner-a',
          nextProcessInstanceId: 'owner-c',
        }),
      });
      const recovered = await db.tradingAccountWorkerHealthState.findUniqueOrThrow({
        where: { tradingAccountId_workerKey: {
          tradingAccountId: 1,
          workerKey: 'pending_order_processing',
        } },
      });
      expect(recovered.processInstanceId).toBe('owner-c');
      expect(recovered.totalLockSkips).toBe(1);
      expect(recovered.consecutiveFailures).toBe(1);
    } finally {
      await contender.end();
      await nextOwner.end();
      if (!ownerClosed) await owner.end();
      await db.$disconnect();
    }
  });

  it('preserves prior failure state and creates a safe row when contention has no row', async () => {
    const db = isolatedPrisma();
    const backoffUntil = new Date('2026-07-26T20:20:00.000Z');
    try {
      await db.tradingAccountWorkerHealthState.deleteMany({
        where: {
          tradingAccountId: 2,
          workerKey: { in: ['submitted_order_sync', 'account_snapshot_scheduler'] },
        },
      });
      await db.tradingAccountWorkerHealthState.create({
        data: {
          tradingAccountId: 2,
          workerKey: 'submitted_order_sync',
          processInstanceId: 'failed-owner',
          expectedIntervalMs: 30_000,
          consecutiveFailures: 3,
          totalFailures: 3,
          lastOutcome: 'failure',
          lastError: 'prior broker failure',
          lastErrorCode: 'BROKER_FAILURE',
          backoffUntil,
        },
      });
      await recordTradingAccountWorkflowLockContention({
        tradingAccountId: 2,
        workerKey: 'submitted_order_sync',
        contenderProcessInstanceId: 'contender-failure',
        lockFamily: 'order-lifecycle',
        attemptedAt: new Date('2026-07-26T20:15:00.000Z'),
      }, { db, emitSystemEvent: async () => ({} as never) });
      const failed = await db.tradingAccountWorkerHealthState.findUniqueOrThrow({
        where: { tradingAccountId_workerKey: {
          tradingAccountId: 2,
          workerKey: 'submitted_order_sync',
        } },
      });
      expect(failed).toMatchObject({
        processInstanceId: 'failed-owner',
        consecutiveFailures: 3,
        backoffUntil,
        lastError: 'prior broker failure',
        lastOutcome: 'failure',
        totalLockSkips: 1,
      });

      await recordTradingAccountWorkflowLockContention({
        tradingAccountId: 2,
        workerKey: 'account_snapshot_scheduler',
        contenderProcessInstanceId: 'first-contender',
        lockFamily: 'account-snapshot',
        attemptedAt: new Date('2026-07-26T20:16:00.000Z'),
      }, { db, emitSystemEvent: async () => ({} as never) });
      const minimal = await db.tradingAccountWorkerHealthState.findUniqueOrThrow({
        where: { tradingAccountId_workerKey: {
          tradingAccountId: 2,
          workerKey: 'account_snapshot_scheduler',
        } },
      });
      expect(minimal).toMatchObject({
        processInstanceId: 'lock-contention:no-owner',
        currentRunStartedAt: null,
        lastSucceededAt: null,
        lastFailedAt: null,
        consecutiveFailures: 0,
        totalFailures: 0,
        totalLockSkips: 1,
        lastOutcome: 'lock_skipped',
      });
      expect(minimal.lastSummaryJson).toMatchObject({
        contenderProcessInstanceId: 'first-contender',
      });
    } finally {
      await db.$disconnect();
    }
  });

  it('lets the owner finalize successfully after contention without losing contention counters', async () => {
    const db = isolatedPrisma();
    const startedAt = new Date();
    try {
      await db.tradingAccountWorkerHealthState.deleteMany({
        where: { tradingAccountId: 2, workerKey: 'tracked_position_sync' },
      });
      await startTradingAccountWorkerRun({
        tradingAccountId: 2,
        workerKey: 'tracked_position_sync',
        processInstanceId: 'success-owner',
        startedAt,
      }, { db, emitSystemEvent: async () => ({} as never) });
      await recordTradingAccountWorkflowLockContention({
        tradingAccountId: 2,
        workerKey: 'tracked_position_sync',
        contenderProcessInstanceId: 'success-contender',
        lockFamily: 'position-sync',
        attemptedAt: new Date(startedAt.getTime() + 1),
      }, { db, emitSystemEvent: async () => ({} as never) });
      await recordTradingAccountWorkerAttempt({
        tradingAccountId: 2,
        workerKey: 'tracked_position_sync',
        processInstanceId: 'success-owner',
        outcome: 'success',
        workSucceeded: true,
        startedAt,
      }, { db, emitSystemEvent: async () => ({} as never) });

      const finalized = await db.tradingAccountWorkerHealthState.findUniqueOrThrow({
        where: { tradingAccountId_workerKey: {
          tradingAccountId: 2,
          workerKey: 'tracked_position_sync',
        } },
      });
      expect(finalized).toMatchObject({
        processInstanceId: 'success-owner',
        currentRunStartedAt: null,
        lastOutcome: 'success',
        totalLockSkips: 1,
        consecutiveFailures: 0,
      });
      expect(finalized.lastSucceededAt).toBeInstanceOf(Date);
    } finally {
      await db.$disconnect();
    }
  });

  it('derives distinct stable keys and rejects a synthetic account lock', async () => {
    const paper = deriveAdvisoryLockKey('ai-trader:order-lifecycle:1');
    const live = deriveAdvisoryLockKey('ai-trader:order-lifecycle:2');
    const paperExit = deriveAdvisoryLockKey('ai-trader:exit-evaluation:1');
    expect(paper).not.toBe(live);
    expect(paper).not.toBe(paperExit);
    await expect(withTradingAccountWorkflowLock({
      tradingAccountId: 0,
      workflowKey: 'order-lifecycle',
      processInstanceId: 'test',
      execute: async () => undefined,
    })).rejects.toThrow(/real positive tradingAccountId/);
  });

  it('aborts migration explicitly when duplicate active cycles pre-exist', async () => {
    const duplicateSchema = `duplicate_active_${randomUUID().replaceAll('-', '')}`;
    const duplicateQuoted = `"${duplicateSchema}"`;
    const client = await connectedClient();
    try {
      await client.query(`CREATE SCHEMA ${duplicateQuoted}; SET search_path TO ${duplicateQuoted}`);
      await client.query(`
        CREATE TABLE "TradingAccount" ("id" integer PRIMARY KEY);
        CREATE TABLE "TrackedPosition" (
          "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "tradingAccountId" integer, broker text NOT NULL, symbol text NOT NULL, status text NOT NULL
        );
        INSERT INTO "TradingAccount" ("id") VALUES (1);
        INSERT INTO "TrackedPosition" ("tradingAccountId", broker, symbol, status)
        VALUES (1, 'alpaca', 'DIA', 'open'), (1, 'ALPACA', 'dia', 'closing');
      `);
      await expect(client.query(await readFile(migrationPath, 'utf8')))
        .rejects.toThrow(/1 duplicate group\(s\).*account=1 broker=alpaca symbol=DIA count=2/);
    } finally {
      await client.query('ROLLBACK');
      await client.query(`DROP SCHEMA IF EXISTS ${duplicateQuoted} CASCADE`);
      await client.end();
    }
  });
});
