import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';

import 'dotenv/config';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Client } from 'pg';

const runDatabaseTests = process.env.RUN_DATABASE_INTEGRITY_TESTS === '1';
const databaseUrl = process.env.DATABASE_URL;
const describeDatabase = runDatabaseTests && databaseUrl ? describe : describe.skip;
const migrationPath =
  'prisma/migrations/20260725120000_scope_broker_lifecycle_identity_by_account/migration.sql';

describeDatabase('broker lifecycle account-scoped external identity', () => {
  const schema = `broker_identity_${randomUUID().replaceAll('-', '')}`;
  const quotedSchema = `"${schema}"`;
  let client: Client;

  beforeAll(async () => {
    client = new Client({ connectionString: databaseUrl });
    await client.connect();
    await client.query(`CREATE SCHEMA ${quotedSchema}`);
    await client.query(`SET search_path TO ${quotedSchema}`);
    await client.query(`
      CREATE TYPE "TradingBroker" AS ENUM ('ALPACA');
      CREATE TYPE "TradingAccountEnvironment" AS ENUM ('PAPER', 'LIVE');

      CREATE TABLE "TradingAccount" (
        "id" integer PRIMARY KEY,
        "broker" "TradingBroker" NOT NULL,
        "environment" "TradingAccountEnvironment" NOT NULL
      );
      INSERT INTO "TradingAccount" VALUES
        (1, 'ALPACA', 'PAPER'),
        (2, 'ALPACA', 'LIVE');

      CREATE TABLE "BrokerActivity" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "tradingAccountId" integer,
        "broker" text NOT NULL,
        "mode" text NOT NULL,
        "activityId" text NOT NULL
      );
      CREATE UNIQUE INDEX "BrokerActivity_activityId_key"
        ON "BrokerActivity" ("activityId");

      CREATE TABLE "BrokerOrder" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "tradingAccountId" integer,
        "broker" text NOT NULL,
        "brokerOrderId" text NOT NULL,
        "clientOrderId" text NOT NULL
      );
      CREATE UNIQUE INDEX "BrokerOrder_broker_brokerOrderId_key"
        ON "BrokerOrder" ("broker", "brokerOrderId");
      CREATE UNIQUE INDEX "BrokerOrder_broker_clientOrderId_key"
        ON "BrokerOrder" ("broker", "clientOrderId");

      CREATE TABLE "AccountSnapshot" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "tradingAccountId" integer,
        "runKey" text
      );
      CREATE UNIQUE INDEX "AccountSnapshot_runKey_key"
        ON "AccountSnapshot" ("runKey");

      CREATE TABLE "AlpacaApiUsageBucket" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "tradingAccountId" integer,
        "bucketStart" timestamp(3) NOT NULL,
        "operation" text NOT NULL,
        "endpoint" text NOT NULL,
        "method" text NOT NULL,
        "requestClass" text NOT NULL
      );
      CREATE UNIQUE INDEX "AlpacaApiUsageBucket_bucketStart_operation_endpoint_method_requestClass_key"
        ON "AlpacaApiUsageBucket"
        ("bucketStart", "operation", "endpoint", "method", "requestClass");
    `);
    const migrationSql = await readFile(migrationPath, 'utf8');
    await client.query(`
      INSERT INTO "BrokerActivity"
        ("tradingAccountId", "broker", "mode", "activityId")
      VALUES (1, 'alpaca', 'live', 'contradictory-mode')
    `);
    await expect(client.query(migrationSql)).rejects.toThrow(
      /contradicts the owning TradingAccount/
    );
    await client.query(`
      DELETE FROM "BrokerActivity" WHERE "activityId" = 'contradictory-mode'
    `);
    await client.query(migrationSql);
  });

  afterAll(async () => {
    if (client) {
      await client.query(`DROP SCHEMA IF EXISTS ${quotedSchema} CASCADE`);
      await client.end();
    }
  });

  it('allows the same activity and order identifiers in Paper and Live', async () => {
    await client.query(`
      INSERT INTO "BrokerActivity"
        ("tradingAccountId", "broker", "mode", "activityId")
      VALUES
        (1, 'alpaca', 'paper', 'same-activity'),
        (2, 'alpaca', 'live', 'same-activity');

      INSERT INTO "BrokerOrder"
        ("tradingAccountId", "broker", "brokerOrderId", "clientOrderId")
      VALUES
        (1, 'alpaca', 'same-order', 'same-client'),
        (2, 'alpaca', 'same-order', 'same-client');
    `);
  });

  it('rejects duplicate external identity inside one account', async () => {
    await expect(
      client.query(`
        INSERT INTO "BrokerActivity"
          ("tradingAccountId", "broker", "mode", "activityId")
        VALUES (1, 'alpaca', 'paper', 'same-activity')
      `)
    ).rejects.toThrow();

    await expect(
      client.query(`
        INSERT INTO "BrokerOrder"
          ("tradingAccountId", "broker", "brokerOrderId", "clientOrderId")
        VALUES (1, 'alpaca', 'same-order', 'different-client')
      `)
    ).rejects.toThrow();
  });

  it('scopes snapshot checkpoints and usage aggregates by account', async () => {
    await client.query(`
      INSERT INTO "AccountSnapshot" ("tradingAccountId", "runKey")
      VALUES (1, 'scheduled:2026-07-25'), (2, 'scheduled:2026-07-25');

      INSERT INTO "AlpacaApiUsageBucket"
        ("tradingAccountId", "bucketStart", "operation", "endpoint", "method", "requestClass")
      VALUES
        (1, now(), 'sync', 'GET /v2/orders', 'GET', 'read'),
        (2, now(), 'sync', 'GET /v2/orders', 'GET', 'read');
    `);
  });

  it('preserves unattributed legacy identities without assigning an account', async () => {
    await client.query(`
      INSERT INTO "BrokerActivity"
        ("tradingAccountId", "broker", "mode", "activityId")
      VALUES (NULL, 'alpaca', 'paper', 'legacy-activity');
    `);
    const result = await client.query(`
      SELECT "tradingAccountId"
      FROM "BrokerActivity"
      WHERE "activityId" = 'legacy-activity'
    `);
    expect(result.rows).toEqual([{ tradingAccountId: null }]);
  });
});
