import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';

import 'dotenv/config';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Client } from 'pg';

const runDatabaseTests = process.env.RUN_DATABASE_INTEGRITY_TESTS === '1';
const databaseUrl = process.env.DATABASE_URL;
const describeDatabase = runDatabaseTests && databaseUrl ? describe : describe.skip;
const migrationPath =
  'prisma/migrations/20260724180000_lock_trading_account_operational_state/migration.sql';

describeDatabase('TradingAccount operational-state database invariant', () => {
  const schema = `trading_account_state_${randomUUID().replaceAll('-', '')}`;
  const quotedSchema = `"${schema}"`;
  let client: Client;
  let migrationSql: string;

  beforeAll(async () => {
    client = new Client({ connectionString: databaseUrl });
    await client.connect();
    await client.query(`CREATE SCHEMA ${quotedSchema}`);
    await client.query(`SET search_path TO ${quotedSchema}`);
    await client.query(`
      CREATE TYPE "TradingAccountStatus" AS ENUM
        ('NEEDS_CREDENTIALS', 'ACTIVE', 'PAUSED', 'DISABLED', 'ERROR');

      CREATE TABLE "User" (
        "id" integer PRIMARY KEY
      );

      CREATE TABLE "TradingAccount" (
        "id" integer PRIMARY KEY,
        "status" "TradingAccountStatus" NOT NULL DEFAULT 'NEEDS_CREDENTIALS',
        "tradingEnabled" boolean NOT NULL DEFAULT false,
        "killSwitchEnabled" boolean NOT NULL DEFAULT true
      );

      CREATE TABLE "SystemEvent" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "type" text NOT NULL,
        "entityType" text NOT NULL,
        "entityId" text NOT NULL,
        "message" text,
        "payloadJson" jsonb NOT NULL,
        "processed" boolean NOT NULL DEFAULT false,
        "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "tradingAccountId" integer
      );

      INSERT INTO "User" ("id") VALUES (7);
      INSERT INTO "TradingAccount"
        ("id", "status", "tradingEnabled", "killSwitchEnabled")
      VALUES
        (1, 'ACTIVE', true, false),
        (2, 'NEEDS_CREDENTIALS', false, true),
        (3, 'PAUSED', true, false);
    `);

    migrationSql = await readFile(migrationPath, 'utf8');
    await expect(client.query(migrationSql)).rejects.toThrow(
      /1 invalid row\(s\) found/
    );

    await client.query(`
      UPDATE "TradingAccount"
      SET "tradingEnabled" = false, "killSwitchEnabled" = true
      WHERE "id" = 3
    `);
    await client.query(migrationSql);
  });

  afterAll(async () => {
    if (client) {
      await client.query(`DROP SCHEMA IF EXISTS ${quotedSchema} CASCADE`);
      await client.end();
    }
  });

  it('accepts the Bobby Paper active and Bobby Live dormant tuples', async () => {
    const result = await client.query(`
      SELECT "id", "status", "tradingEnabled", "killSwitchEnabled"
      FROM "TradingAccount"
      WHERE "id" IN (1, 2)
      ORDER BY "id"
    `);
    expect(result.rows).toEqual([
      {
        id: 1,
        status: 'ACTIVE',
        tradingEnabled: true,
        killSwitchEnabled: false,
      },
      {
        id: 2,
        status: 'NEEDS_CREDENTIALS',
        tradingEnabled: false,
        killSwitchEnabled: true,
      },
    ]);
  });

  it('rejects an INSERT with an invalid operational tuple', async () => {
    await expect(
      client.query(`
        INSERT INTO "TradingAccount"
          ("id", "status", "tradingEnabled", "killSwitchEnabled")
        VALUES (10, 'NEEDS_CREDENTIALS', true, false)
      `)
    ).rejects.toThrow(/TradingAccount_operational_state_check/);
  });

  it('rejects an UPDATE to an invalid operational tuple', async () => {
    await expect(
      client.query(`
        UPDATE "TradingAccount"
        SET "status" = 'PAUSED'
        WHERE "id" = 1
      `)
    ).rejects.toThrow(/TradingAccount_operational_state_check/);
  });

  it('rolls back operational state and its audit event together on failure', async () => {
    await expect(
      client.query(`
        BEGIN;
        UPDATE "TradingAccount"
        SET
          "status" = 'PAUSED',
          "tradingEnabled" = false,
          "killSwitchEnabled" = true
        WHERE "id" = 1;
        INSERT INTO "SystemEvent"
          ("type", "entityType", "entityId", "payloadJson",
           "tradingAccountId", "actorUserId")
        VALUES
          ('trading_account.deactivated', 'tradingAccount', '1', '{}', 1, 7);
        INSERT INTO "TradingAccount"
          ("id", "status", "tradingEnabled", "killSwitchEnabled")
        VALUES (11, 'ACTIVE', false, true);
        COMMIT;
      `)
    ).rejects.toThrow(/TradingAccount_operational_state_check/);
    await client.query('ROLLBACK');

    const [account, events] = await Promise.all([
      client.query(`
        SELECT "status", "tradingEnabled", "killSwitchEnabled"
        FROM "TradingAccount"
        WHERE "id" = 1
      `),
      client.query(`
        SELECT COUNT(*)::integer AS count
        FROM "SystemEvent"
        WHERE "type" = 'trading_account.deactivated'
      `),
    ]);
    expect(account.rows[0]).toEqual({
      status: 'ACTIVE',
      tradingEnabled: true,
      killSwitchEnabled: false,
    });
    expect(events.rows[0]?.count).toBe(0);
  });
});
