import { Fragment, useRef, useState } from "react";
import { Alert, Button, Card, Checkbox, Group, List, Modal, Select, SimpleGrid, Stack, Table, Text, TextInput, Title } from "@mantine/core";
import { IconRefresh } from "@tabler/icons-react";
import { useQuery } from "@tanstack/react-query";
import { Link, useNavigate } from "react-router-dom";
import { CompactRecordList, DataState, DataTable, MobileRecordCard, RecordDetailsGrid, ResponsiveDataView, ResponsiveDetails, StatusBadge, formatStatusLabel, type StatusTone, type SummaryField } from "../../components/data-display";
import { getAdminToken } from "../../lib/api";
import { getSubscriptions } from "../subscriptions/api";
import { useLifecycleExerciseMutations, useLifecycleExercises, useSubscriptionEntryCandidates } from "./hooks";
import { DEFAULT_LIFECYCLE_EXERCISE_REASON, isLifecyclePreviewValid, selectionModeLabel, updateGeneratedExerciseName, validatedAssignmentIds } from "./exerciseForm";
import type { LifecycleExercise, LifecycleExerciseTarget, SubscriptionEntryCandidate } from "./types";
import classes from "./LifecycleExercisesPage.module.css";

const tone = (status: string): StatusTone => ["COMPLETED", "READY", "INTENT_CREATED", "RECONCILED"].includes(status) ? "positive" : ["BLOCKED", "FAILED"].includes(status) ? "danger" : ["ATTENTION_REQUIRED", "PARTIAL", "WARNING"].includes(status) ? "warning" : "informational";
const date = (value: string | null) => value ? new Date(value).toLocaleString() : "Not available";
const creator = (exercise: LifecycleExercise) => exercise.createdByUser.name ?? exercise.createdByUser.email;
const money = (value: number | null | undefined) => value == null ? "Not available" : new Intl.NumberFormat(undefined, { style: "currency", currency: "USD" }).format(value);
const countTargets = (exercise: LifecycleExercise) => exercise.targets?.length ?? exercise._count?.targets ?? 0;
const selectedLabel = (exercise: LifecycleExercise) => exercise.selectionMode === "EXPLICIT_ASSIGNMENTS" ? `${countTargets(exercise)} selected TradingAccount${countTargets(exercise) === 1 ? "" : "s"}` : selectionModeLabel(exercise.selectionMode);

function CandidateCard({ candidate, checked, onChange }: { candidate: SubscriptionEntryCandidate; checked: boolean; onChange: (checked: boolean) => void }) {
  const live = candidate.tradingAccount.environment === "LIVE";
  const disabled = live || !candidate.selectable;
  const reasons = live ? [{ code: "LIVE_EXERCISES_NOT_SUPPORTED", message: "Live exercises are not supported yet." }] : candidate.unavailableReasons;
  const configured = candidate.assignment.sizingType === "FIXED_QTY" ? `${candidate.assignment.fixedQty ?? "—"} shares` : candidate.assignment.maxPositionNotional != null ? money(candidate.assignment.maxPositionNotional) : "Configured by allocation";
  return <Card withBorder padding="sm" className={`${classes.candidate} ${checked ? classes.candidateSelected : ""}`}>
    <Group align="flex-start" wrap="nowrap">
      <Checkbox checked={checked} disabled={disabled} onChange={(event) => onChange(event.currentTarget.checked)} aria-label={`Select ${candidate.tradingAccount.displayName} assignment ${candidate.tradingAccountSubscriptionId}`} aria-describedby={`candidate-reasons-${candidate.tradingAccountSubscriptionId}`} mt={4} />
      <Stack gap={6} className={classes.candidateBody}>
        <Group justify="space-between" align="flex-start"><div><Text fw={700}>{candidate.tradingAccount.displayName}</Text><Text size="xs" c="dimmed">{candidate.accountHolder.name ?? candidate.accountHolder.email} · Assignment #{candidate.tradingAccountSubscriptionId}</Text></div><Group gap={6}><StatusBadge status={candidate.tradingAccount.environment} label={candidate.tradingAccount.environment === "PAPER" ? "Paper" : "Live"} tone={live ? "warning" : "informational"} size="compact" /><StatusBadge status={candidate.tradingAccount.status} label={formatStatusLabel(candidate.tradingAccount.status)} tone={tone(candidate.tradingAccount.status)} size="compact" /></Group></Group>
        <SimpleGrid cols={{ base: 1, sm: 2, lg: 4 }} spacing="xs"><Text size="xs"><b>Assignment:</b> {candidate.assignment.enabled ? "Enabled" : "Disabled"} · Entries {candidate.assignment.entriesEnabled ? "on" : "off"}</Text><Text size="xs"><b>Allocation:</b> {candidate.allocation?.displayName ?? "Unavailable"}</Text><Text size="xs"><b>Sizing:</b> {formatStatusLabel(candidate.assignment.sizingType)} · {configured}</Text><Text size="xs"><b>Credentials:</b> {candidate.tradingAccount.credentialStatus ? formatStatusLabel(candidate.tradingAccount.credentialStatus) : "Unavailable"}</Text></SimpleGrid>
        <div id={`candidate-reasons-${candidate.tradingAccountSubscriptionId}`}>{reasons.map((reason) => <Text key={reason.code} size="xs" c="red">{reason.message}</Text>)}{!disabled && <Text size="xs" c="teal">Available for PAPER preview. Runtime sizing and risk are evaluated during preview.</Text>}</div>
      </Stack>
    </Group>
  </Card>;
}

function previewPositionCapacity(target: LifecycleExerciseTarget) {
  if (target.readinessJson?.positionSlotUsage) return `${target.readinessJson.positionSlotUsage.projectedSlotCount} projected / ${target.readinessJson.positionSlotUsage.accountMaxPositions ?? "unlimited"}`;
  const details = target.readinessJson?.risk?.details;
  const used = details?.usage?.currentAccountPositionSlots ?? ((details?.usage?.activePositionCount ?? 0) + (details?.usage?.pendingEntryPositionCount ?? 0));
  if (!details?.usage) return target.blockersJson.length ? "Not evaluated — entry blocked earlier" : "Not evaluated";
  return `${used + 1} projected / ${details.effectiveEntryLimits?.limits?.maxOpenPositions?.value ?? "unlimited"}`;
}

function PreviewTarget({ target, candidate }: { target: LifecycleExerciseTarget; candidate?: SubscriptionEntryCandidate }) {
  const accountName = target.tradingAccount?.displayName ?? target.readinessJson?.context?.tradingAccount?.displayName ?? candidate?.tradingAccount.displayName ?? `TradingAccount #${target.tradingAccountId}`;
  const accountHolder = target.accountHolderUser?.name ?? target.accountHolderUser?.email ?? candidate?.accountHolder.name ?? candidate?.accountHolder.email ?? "Account holder unavailable";
  const allocation = target.allocationSnapshotJson?.displayName ?? target.allocationSnapshotJson?.name ?? target.allocationSnapshotJson?.key ?? target.readinessJson?.context?.allocation?.name ?? target.readinessJson?.risk?.details?.allocationRisk?.allocationName ?? target.readinessJson?.context?.allocation?.key ?? target.readinessJson?.risk?.details?.allocationRisk?.allocationKey ?? candidate?.allocation?.displayName;
  return <Card withBorder padding="sm"><Stack gap="xs"><Group justify="space-between"><div><Text fw={700}>{accountName}</Text><Text size="xs" c="dimmed">Selected target · {accountHolder} · Assignment #{target.tradingAccountSubscriptionId}</Text></div><StatusBadge status={target.status} label={target.status === "READY" || target.status === "WARNING" ? "Currently eligible" : formatStatusLabel(target.status)} tone={tone(target.status)} /></Group>
    <RecordDetailsGrid sections={[{ items: [{ label: "Environment", value: target.environment }, { label: "Quantity", value: target.resolvedQuantity }, { label: "Reference price", value: money(target.estimatedPrice) }, { label: "Estimated notional", value: money(target.estimatedNotional) }, { label: "Allocation", value: allocation }, { label: "Account position slots", value: previewPositionCapacity(target) }] }]}/>
    {target.blockersJson?.map((issue) => <Alert key={issue.code} color="red" title={formatStatusLabel(issue.code)}>{issue.message}</Alert>)}{target.warningsJson?.map((issue) => <Alert key={issue.code} color="yellow" title={formatStatusLabel(issue.code)}>{issue.message}</Alert>)}</Stack></Card>;
}

export function LifecycleExercisesPage() {
  const navigate = useNavigate(); const [token] = useState(() => getAdminToken()); const exercises = useLifecycleExercises(token); const mutations = useLifecycleExerciseMutations(token);
  const subscriptions = useQuery({ queryKey: ["subscriptions", "lifecycle-exercises"], queryFn: () => getSubscriptions(token as string), enabled: Boolean(token) });
  const [name, setName] = useState(""); const nameEdited = useRef(false); const [reason, setReason] = useState(DEFAULT_LIFECYCLE_EXERCISE_REASON); const [subscriptionId, setSubscriptionId] = useState<number | null>(null); const [selectedIds, setSelectedIds] = useState<number[]>([]); const [preview, setPreview] = useState<LifecycleExercise | null>(null); const [confirming, setConfirming] = useState(false); const [refreshNotice, setRefreshNotice] = useState<string | null>(null); const [expandedId, setExpandedId] = useState<number | null>(null); const [drawerExercise, setDrawerExercise] = useState<LifecycleExercise | null>(null); const [detailOpener, setDetailOpener] = useState<HTMLElement | null>(null); const [statusFilter, setStatusFilter] = useState<string | null>(null); const [modeFilter, setModeFilter] = useState<string | null>(null); const [subscriptionFilter, setSubscriptionFilter] = useState<string | null>(null);
  const candidates = useSubscriptionEntryCandidates(token, subscriptionId);
  const candidateRows = candidates.data?.candidates ?? []; const eligible = candidateRows.filter((row) => row.selectable && row.tradingAccount.environment === "PAPER"); const validIds = validatedAssignmentIds(candidateRows, selectedIds);
  async function refreshCandidates() { const result = await candidates.refetch(); if (!result.data) return; const next = validatedAssignmentIds(result.data.candidates, selectedIds); const removed = selectedIds.length - next.length; setSelectedIds(next); setRefreshNotice(removed ? `${removed} prior selection${removed === 1 ? " was" : "s were"} removed because the assignment is no longer available.` : "Candidates refreshed; current eligible selections were preserved."); }
  function changeSubscription(value: string | null) { const id = value ? Number(value) : null; setSubscriptionId(id); setSelectedIds([]); setPreview(null); setRefreshNotice(id ? "Candidate data refreshed for the selected Subscription." : null); if (!nameEdited.current && id) { const item = subscriptions.data?.find((row) => row.id === id); if (item) setName(updateGeneratedExerciseName({ currentName: name, manuallyEdited: false, subscriptionName: item.name })); } }
  async function createPreview() { if (!subscriptionId || !reason.trim()) return; const ids = validatedAssignmentIds(candidateRows, selectedIds); if (!ids.length || ids.length > 25) return; const response = await mutations.previewExplicit.mutateAsync({ ...(name.trim() ? { name: name.trim() } : {}), reason: reason.trim(), subscriptionId, tradingAccountSubscriptionIds: ids, environment: "PAPER" }); setPreview(response.exercise); setConfirming(false); }
  async function launch() { if (!preview) return; const response = await mutations.launch.mutateAsync(preview.id); setConfirming(false); navigate(`/lifecycle-exercises/${response.exercise.id}`); }
  function startOver() { setPreview(null); setConfirming(false); setSelectedIds([]); }
  const rows = (exercises.data?.exercises ?? []).filter((row) => (!statusFilter || row.status === statusFilter) && (!modeFilter || row.selectionMode === modeFilter) && (!subscriptionFilter || row.subscription.id === Number(subscriptionFilter)));
  const identity = (exercise: LifecycleExercise) => <div><Text fw={800}>#{exercise.id} {exercise.name ?? exercise.subscription.name}</Text><Text size="xs" c="dimmed">{creator(exercise)} · {date(exercise.createdAt)}</Text></div>;
  const fields = (exercise: LifecycleExercise): SummaryField[] => [{ label: "Type / selection", value: `Subscription Entry · ${selectedLabel(exercise)}` }, { label: "Subscription / environment", value: `${exercise.subscription.name} · ${exercise.containsLiveTargets ? "Contains LIVE targets" : "PAPER only"}` }, { label: "Targets", value: countTargets(exercise) }];
  const wide = (items: readonly LifecycleExercise[]) => <DataTable caption="Lifecycle exercise history" captionHidden density="compact"><Table.Thead><Table.Tr><Table.Th>Exercise</Table.Th><Table.Th>Type / selection</Table.Th><Table.Th>Subscription / environment</Table.Th><Table.Th>Targets</Table.Th><Table.Th>Status</Table.Th><Table.Th>Actions</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{items.map((exercise) => <Fragment key={exercise.id}><Table.Tr><Table.Td>{identity(exercise)}</Table.Td><Table.Td>{fields(exercise)[0].value}</Table.Td><Table.Td>{fields(exercise)[1].value}</Table.Td><Table.Td>{fields(exercise)[2].value}</Table.Td><Table.Td><StatusBadge status={exercise.status} label={formatStatusLabel(exercise.status)} tone={tone(exercise.status)} /></Table.Td><Table.Td><Button variant="default" size="compact-sm" onClick={(event) => { setExpandedId(expandedId === exercise.id ? null : exercise.id); setDetailOpener(event.currentTarget); setDrawerExercise(exercise); }}>Details</Button></Table.Td></Table.Tr></Fragment>)}</Table.Tbody></DataTable>;
  const compact = (items: readonly LifecycleExercise[]) => <CompactRecordList records={items} getRecordId={(row) => row.id} renderIdentity={identity} renderFields={fields} renderDetails={(row) => <Button component={Link} to={`/lifecycle-exercises/${row.id}`}>Open full details</Button>} expandedId={expandedId} onExpandedChange={(value) => setExpandedId(value as number | null)} />;
  const mobile = (items: readonly LifecycleExercise[]) => <MobileRecordCard records={items} getRecordId={(row) => row.id} renderIdentity={identity} renderFields={fields} renderStatus={(row) => <StatusBadge status={row.status} label={formatStatusLabel(row.status)} tone={tone(row.status)} />} onDetails={(row) => navigate(`/lifecycle-exercises/${row.id}`)} detailsLabel="Open details" detailsIsDialog={false} />;
  const ready = preview?.targets?.filter((row) => ["READY", "WARNING"].includes(row.status)).length ?? 0; const blocked = (preview?.targets?.length ?? 0) - ready; const warningCount = preview?.targets?.reduce((sum, row) => sum + (row.warningsJson?.length ?? 0), 0) ?? 0; const totalNotional = preview?.targets?.filter((row) => ["READY", "WARNING"].includes(row.status)).reduce((sum, row) => sum + (row.estimatedNotional ?? 0), 0) ?? 0;
  return <main className={classes.page}><Stack gap="lg"><Group justify="space-between" align="flex-start"><div><Title order={2}>Lifecycle Exercises</Title><Text size="sm" c="dimmed" maw={780}>Open PAPER positions for a Subscription on selected TradingAccounts to test the complete trading lifecycle. Preview eligibility and sizing first; launching then submits entries for every eligible selected account through the same risk, order, broker, position, and exit pipeline used by normal trading.</Text></div><Button variant="default" leftSection={<IconRefresh size={16}/>} onClick={() => void exercises.refetch()} loading={exercises.isFetching}>Refresh</Button></Group><Alert color="blue" title="Currently PAPER only">Launching an exercise can place PAPER orders and open PAPER positions on every eligible selected account. LIVE assignments are visible for deployment context but cannot yet be selected, previewed, or launched.</Alert>
  <Card withBorder><Stack gap="md"><Title order={3}>{preview ? "Review frozen targets" : "Create Subscription Entry exercise"}</Title>{!preview ? <>
    <Alert color="gray" title="How this works"><List size="sm" spacing={4}><List.Item>Choose one Subscription, then select up to 25 TradingAccounts where it is deployed.</List.Item><List.Item>Preview evaluates each account independently without placing orders and freezes the selected targets.</List.Item><List.Item>Launch revalidates every frozen target, then submits a PAPER entry for every account that is eligible at launch.</List.Item><List.Item>Successful entries can open positions. Blocked accounts place no order but stay recorded, so mixed outcomes are expected.</List.Item></List></Alert>
    <SimpleGrid cols={{ base: 1, md: 3 }}><Select required searchable label="Subscription" placeholder="Select a Subscription" value={subscriptionId ? String(subscriptionId) : null} onChange={changeSubscription} data={(subscriptions.data ?? []).map((row) => ({ value: String(row.id), label: `${row.name} (${row.key})` }))}/><TextInput label="Exercise name (optional)" value={name} onChange={(event) => { nameEdited.current = true; setName(event.currentTarget.value); }}/><Select label="Environment" value="PAPER" data={[{ value: "PAPER", label: "PAPER" }, { value: "LIVE", label: "LIVE — not supported", disabled: true }]}/></SimpleGrid><TextInput required label="Reason" value={reason} onChange={(event) => setReason(event.currentTarget.value)}/>
    <Stack gap="sm"><Group justify="space-between"><div><Text fw={600}>Select TradingAccounts</Text><Text size="xs" c="dimmed">{validIds.length}/25 selected · {eligible.length} eligible PAPER TradingAccount(s)</Text></div><Group><Button size="xs" variant="default" disabled={!eligible.length || eligible.length > 25} onClick={() => setSelectedIds(eligible.map((row) => row.tradingAccountSubscriptionId))}>Select all eligible</Button><Button size="xs" variant="subtle" disabled={!selectedIds.length} onClick={() => setSelectedIds([])}>Clear selection</Button><Button size="xs" variant="default" leftSection={<IconRefresh size={14}/>} disabled={!subscriptionId} loading={candidates.isFetching} onClick={() => void refreshCandidates()}>Refresh</Button></Group></Group>
      {!subscriptionId && <DataState state="empty" title="Select a Subscription" message="Assignments load only after a Subscription is selected."/>}{subscriptionId && candidates.isLoading && <DataState state="loading" message="Loading the Subscription's current deployments…"/>}{candidates.isError && <Alert color="red" title="Unable to load assignments">Candidate request failed. Refresh to try again.</Alert>}{refreshNotice && <Alert color="blue" withCloseButton onClose={() => setRefreshNotice(null)}>{refreshNotice}</Alert>}{candidates.data && !candidateRows.length && <DataState state="empty" title="No assignments" message="This Subscription has no TradingAccount assignments."/>}{candidateRows.length > 0 && !eligible.length && <Alert color="yellow" title="No selectable PAPER assignments">All assignments are LIVE or currently unavailable. Review the reasons below.</Alert>}
      <div className={classes.candidateGrid}>{candidateRows.map((candidate) => <CandidateCard key={candidate.tradingAccountSubscriptionId} candidate={candidate} checked={validIds.includes(candidate.tradingAccountSubscriptionId)} onChange={(checked) => setSelectedIds((current) => checked ? [...current, candidate.tradingAccountSubscriptionId].slice(0, 25) : current.filter((id) => id !== candidate.tradingAccountSubscriptionId))}/>)}</div>{selectedIds.length >= 25 && <Alert color="yellow">A maximum of 25 exact assignments may be previewed.</Alert>}
    </Stack>
    {mutations.previewExplicit.isError && <Alert color="red" title="Preview could not be created">{mutations.previewExplicit.error.message} Identity validation may have changed; refresh candidates and review your selection.</Alert>}<Button type="button" onClick={() => void createPreview()} loading={mutations.previewExplicit.isPending} disabled={!subscriptionId || !reason.trim() || !validIds.length || validIds.length > 25}>Preview frozen targets</Button>
  </> : <Stack><Alert color="blue" title="Frozen preview">These selected targets cannot be edited. Start over to abandon this preview and create a new one.</Alert><SimpleGrid cols={{ base: 2, md: 4 }}><div><Text size="xs" c="dimmed">Subscription</Text><Text fw={600}>{preview.subscription.name}</Text></div><div><Text size="xs" c="dimmed">Selection mode</Text><Text fw={600}>{selectionModeLabel(preview.selectionMode)}</Text></div><div><Text size="xs" c="dimmed">Frozen targets</Text><Text fw={600}>{countTargets(preview)}</Text></div><div><Text size="xs" c="dimmed">Environment</Text><Text fw={600}>PAPER only</Text></div><div><Text size="xs" c="dimmed">Ready / blocked</Text><Text fw={600}>{ready} / {blocked}</Text></div><div><Text size="xs" c="dimmed">Warnings</Text><Text fw={600}>{warningCount}</Text></div><div><Text size="xs" c="dimmed">Eligible notional</Text><Text fw={600}>{money(totalNotional)}</Text></div><div><Text size="xs" c="dimmed">Expires</Text><Text fw={600} c={isLifecyclePreviewValid(preview.status, preview.previewExpiresAt) ? undefined : "red"}>{date(preview.previewExpiresAt)}</Text></div></SimpleGrid>{!isLifecyclePreviewValid(preview.status, preview.previewExpiresAt) && <Alert color="red" title="Preview expired">Launch is disabled. Start over to create a fresh frozen preview.</Alert>}<div className={classes.previewTargets}>{preview.targets?.map((target) => <PreviewTarget key={target.id} target={target} candidate={candidateRows.find((row) => row.tradingAccountSubscriptionId === target.tradingAccountSubscriptionId)}/>)}</div>{mutations.launch.isError && <Alert color="red" title="Launch failed">{mutations.launch.error.message}. The frozen preview remains available for review.</Alert>}<Group justify="space-between"><Button variant="default" onClick={startOver}>Start over</Button><Button color="orange" disabled={!isLifecyclePreviewValid(preview.status, preview.previewExpiresAt)} onClick={() => setConfirming(true)}>Launch PAPER exercise</Button></Group></Stack>}</Stack></Card>
  <section><Group justify="space-between"><Title order={3}>Exercise history</Title><Group><Select clearable placeholder="Subscription" value={subscriptionFilter} onChange={setSubscriptionFilter} data={(subscriptions.data ?? []).map((row) => ({ value: String(row.id), label: row.name }))}/><Select clearable placeholder="Status" value={statusFilter} onChange={setStatusFilter} data={[...new Set((exercises.data?.exercises ?? []).map((row) => row.status))].map((value) => ({ value, label: formatStatusLabel(value) }))}/><Select clearable placeholder="Selection mode" value={modeFilter} onChange={setModeFilter} data={[{ value: "EXPLICIT_ASSIGNMENTS", label: "Selected TradingAccounts" }, { value: "SELECTED_USERS", label: "Selected users" }, { value: "ALL_ELIGIBLE", label: "All eligible users/accounts" }]}/></Group></Group>{exercises.isLoading ? <DataState state="loading" message="Loading exercises…"/> : !rows.length ? <DataState state="empty" title="No matching exercises"/> : <ResponsiveDataView records={rows} getRecordId={(row) => row.id} wide={wide} compact={compact} narrow={mobile} aria-label="Lifecycle exercise history"/>}</section>
  <ResponsiveDetails opened={drawerExercise !== null} title={drawerExercise ? `Exercise #${drawerExercise.id}` : "Exercise"} onClose={() => { setDrawerExercise(null); window.setTimeout(() => detailOpener?.focus(), 0); }}>{drawerExercise && <Stack><RecordDetailsGrid sections={[{ items: [{ label: "Exercise type", value: "Subscription Entry" }, { label: "Selection mode", value: selectionModeLabel(drawerExercise.selectionMode) }, { label: "Environment", value: drawerExercise.containsLiveTargets ? "Contains LIVE targets" : "PAPER only" }, { label: "Subscription", value: drawerExercise.subscription.name }, { label: "Created by", value: creator(drawerExercise) }, { label: "Status", value: formatStatusLabel(drawerExercise.status) }] }]}/><Button component={Link} to={`/lifecycle-exercises/${drawerExercise.id}`}>Open full details</Button></Stack>}</ResponsiveDetails>
  <Modal opened={confirming && Boolean(preview)} onClose={() => !mutations.launch.isPending && setConfirming(false)} title="Confirm PAPER exercise launch" centered>{preview && <Stack><Text>This launches the frozen {countTargets(preview)} TradingAccount assignment(s) for {preview.subscription.name}.</Text><Text size="sm">{ready} ready, {blocked} blocked · estimated eligible notional {money(totalNotional)}.</Text><Alert color="yellow">Launch revalidates every target against current state. Mixed results are possible; blocked preview targets may remain blocked, and state may change between preview and launch. Not every selected target will place an order.</Alert><Group justify="flex-end"><Button variant="default" onClick={() => setConfirming(false)}>Cancel</Button><Button color="orange" loading={mutations.launch.isPending} onClick={() => void launch()}>Launch frozen exercise</Button></Group></Stack>}</Modal>
  </Stack></main>;
}
