import { useState } from "react";
import { Accordion, Alert, Badge, Button, Card, Divider, Group, Loader, Modal, SimpleGrid, Stack, Text, TextInput, Timeline, Title } from "@mantine/core";
import { Link, useLocation, useParams } from "react-router-dom";
import { createScopedNavigationTarget } from "../../app/navigationUtils";
import { formatStatusLabel } from "../../components/data-display";
import { getAdminToken } from "../../lib/api";
import { useClosePosition } from "../positions/hooks";
import { selectionModeLabel } from "./exerciseForm";
import { useLifecycleExercise, useLifecycleExerciseMutations } from "./hooks";
import type { LifecycleExerciseTarget } from "./types";
import classes from "./LifecycleExerciseDetailPage.module.css";

const activeStages = new Set(["POSITION_OPEN", "EXIT_MONITORING", "PROTECTIVE_ORDER_ACTIVE"]);
const when = (value?: string | null) => value ? new Date(value).toLocaleString() : "Not available";
const money = (value?: number | null) => value == null ? "Not available" : new Intl.NumberFormat(undefined, { style: "currency", currency: "USD" }).format(value);

export function LifecycleExerciseDetailPage() {
  const location = useLocation();
  const id = Number(useParams().id); const [token] = useState(() => getAdminToken()); const query = useLifecycleExercise(token, id); const mutations = useLifecycleExerciseMutations(token); const [cancelReason, setCancelReason] = useState(""); const [recovering, setRecovering] = useState(false); const [closeTarget, setCloseTarget] = useState<LifecycleExerciseTarget | null>(null); const [recoveryResults, setRecoveryResults] = useState<Array<{ targetId: number; code: string; orderIntentId: number | null }> | null>(null);
  const closeMutation = useClosePosition(token);
  if (query.isLoading) return <Group><Loader size="sm"/><Text>Loading lifecycle exercise…</Text></Group>;
  if (query.isError || !query.data) return <Alert color="red">Unable to load lifecycle exercise.</Alert>;
  const exercise = query.data.exercise; const targets = exercise.targets ?? []; const cancellable = !["COMPLETED", "FAILED", "CANCELLED"].includes(exercise.status);
  const counts = targets.reduce<Record<string, number>>((result, target) => { const stage = target.projection?.stage ?? target.status; result[stage] = (result[stage] ?? 0) + 1; return result; }, {});
  return <Stack gap="lg" className={classes.page}>
    <Group justify="space-between" align="flex-start" className={classes.header}><div><Title order={2}>Exercise #{exercise.id}: {exercise.name ?? exercise.subscription.name}</Title><Text c="dimmed">{exercise.reason}</Text></div><Group><Badge color="cyan">{exercise.environment}</Badge>{exercise.containsLiveTargets && <Badge color="orange">Contains LIVE targets</Badge>}<Badge>{formatStatusLabel(exercise.status)}</Badge><Button variant="default" onClick={() => query.refetch()} loading={query.isFetching}>Refresh</Button></Group></Group>
    {exercise.cancelledAt && <Alert color="yellow" title="Exercise cancelled">Only undispatched targets were cancelled. Existing orders and positions continue through normal lifecycle management.</Alert>}
    <Card withBorder><Stack><SimpleGrid cols={{ base: 1, sm: 2, lg: 4 }}><Fact label="Exercise type" value="Subscription Entry"/><Fact label="Selection mode" value={selectionModeLabel(exercise.selectionMode)}/><Fact label="Environment" value={exercise.containsLiveTargets ? `${exercise.environment} · contains LIVE targets` : `${exercise.environment} only`}/><Fact label="Subscription" value={`${exercise.subscription.name} (${exercise.subscription.key})`}/><Fact label="Created by" value={exercise.createdByUser.name ?? exercise.createdByUser.email}/><Fact label="Previewed / expires" value={`${when(exercise.previewedAt)} / ${when(exercise.previewExpiresAt)}`}/><Fact label="Launched" value={when(exercise.launchedAt)}/><Fact label="Preview version / fingerprint" value={`v${exercise.previewVersion} · ${exercise.previewFingerprint?.slice(0, 12) ?? "Not available"}…`}/></SimpleGrid><Group>{Object.entries(counts).map(([stage, count]) => <Badge key={stage} variant="light">{formatStatusLabel(stage)}: {count}</Badge>)}</Group>
      {cancellable && <Group align="flex-end" className={classes.consequential}><TextInput label="Cancellation reason" value={cancelReason} onChange={(event) => setCancelReason(event.currentTarget.value)} className={classes.reason}/><Button color="red" variant="light" disabled={!cancelReason.trim()} loading={mutations.cancel.isPending} onClick={() => mutations.cancel.mutate({ id, reason: cancelReason })}>Cancel undispatched work</Button></Group>}
      {exercise.recoveryApplicable && <Alert color="orange" title="Stale dispatch recovery available"><Stack gap="xs"><Text size="sm">Recovery checks for an existing exact-scope intent before redispatch and preserves ambiguous matches as attention-required.</Text><Button color="orange" variant="light" onClick={() => setRecovering(true)}>Recover stale dispatches</Button></Stack></Alert>}
      {recoveryResults && <Alert color="blue" title="Dispatch recovery results">{recoveryResults.map((result) => <Text size="sm" key={result.targetId}>Target #{result.targetId}: {formatStatusLabel(result.code)}{result.orderIntentId ? ` · OrderIntent #${result.orderIntentId}` : ""}</Text>)}</Alert>}
    </Stack></Card>
    {targets.map((target) => { const projection = target.projection; const positionId = projection?.links.trackedPositionId; return <Card key={target.id} withBorder><Stack>
      <Group justify="space-between"><div><Title order={4}>{target.tradingAccount?.displayName ?? `TradingAccount #${target.tradingAccountId}`}</Title><Text size="sm" c="dimmed">{target.accountHolderUser?.name ?? target.accountHolderUser?.email ?? "Account holder unavailable"} · Assignment #{target.tradingAccountSubscriptionId}</Text></div><Badge color={projection?.stage === "ATTENTION_REQUIRED" ? "orange" : projection?.stage === "RECONCILED" ? "teal" : "blue"}>{formatStatusLabel(projection?.stage ?? target.status)}</Badge></Group>
      <section><Title order={5}>Preview evidence</Title><Text size="xs" c="dimmed">Frozen eligibility and sizing captured before launch.</Text><SimpleGrid cols={{ base: 1, sm: 2, lg: 4 }}><Fact label="Preview readiness" value={formatStatusLabel(target.status)}/><Fact label="Quantity" value={target.resolvedQuantity ?? "Not available"}/><Fact label="Reference price" value={money(target.estimatedPrice)}/><Fact label="Estimated notional" value={money(target.estimatedNotional)}/></SimpleGrid>{target.blockersJson?.map((item) => <Alert key={item.code} color="red" title={`Preview blocker · ${formatStatusLabel(item.code)}`}>{item.message}</Alert>)}{target.warningsJson?.map((item) => <Alert key={item.code} color="yellow" title={`Preview warning · ${formatStatusLabel(item.code)}`}>{item.message}</Alert>)}</section>
      <Divider/><section><Title order={5}>Launch evidence</Title><Text size="xs" c="dimmed">Persisted launch-time evidence remains separate from preview blockers and warnings.</Text><SimpleGrid cols={{ base: 1, sm: 2, lg: 4 }}><Fact label="Launch outcome" value={target.launchOutcome ? formatStatusLabel(target.launchOutcome) : "Not launched"}/><Fact label="Result code" value={target.launchResultCode ? formatStatusLabel(target.launchResultCode) : "Not available"}/><Fact label="Attempted" value={when(target.launchAttemptedAt)}/><Fact label="Result message" value={target.launchResultMessage ?? "Not available"}/></SimpleGrid>{target.launchEvidenceJson && <Accordion variant="contained" mt="sm"><Accordion.Item value="evidence"><Accordion.Control>Technical launch evidence</Accordion.Control><Accordion.Panel><Text component="pre" size="xs" style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{JSON.stringify(target.launchEvidenceJson, null, 2)}</Text></Accordion.Panel></Accordion.Item></Accordion>}</section>
      <Divider/><Group className={classes.actions}><Button component={Link} to={createScopedNavigationTarget(`/trading-accounts/${target.tradingAccountId}`, location.search)} variant="default" size="xs">Trading account</Button>{projection?.links.orderIntentId && <Button component={Link} to={`/orders/open?account=${target.tradingAccountId}`} variant="default" size="xs">Open orders</Button>}{positionId && <Button component={Link} to={`/positions/open?account=${target.tradingAccountId}`} variant="default" size="xs">Positions</Button>}{positionId && projection && activeStages.has(projection.stage) && <Button color="orange" size="xs" loading={closeMutation.isPending && closeMutation.variables?.trackedPositionId === positionId} onClick={() => setCloseTarget(target)}>Manual close</Button>}<Button size="xs" variant="light" loading={mutations.reconcile.isPending} onClick={() => mutations.reconcile.mutate({ exerciseId: exercise.id, targetId: target.id })}>Run diagnostic reconciliation</Button></Group>
      <Title order={5}>Authoritative lifecycle timeline</Title><Timeline bulletSize={18} lineWidth={2}>{(projection?.timeline ?? []).map((event) => <Timeline.Item key={event.key} title={event.label}><Text size="xs" c="dimmed">{when(event.at)} · {event.entityType} #{event.entityId}</Text></Timeline.Item>)}</Timeline>
    </Stack></Card>; })}
    <Modal opened={recovering} onClose={() => !mutations.recover.isPending && setRecovering(false)} title="Confirm stale dispatch recovery" centered><Stack><Text>Recovery checks every stale dispatch for an existing exact-scope OrderIntent before any safe redispatch.</Text><Alert color="yellow">Ambiguous matches remain attention-required. This never replaces assignments or bypasses normal entry processing.</Alert>{mutations.recover.isError && <Alert color="red">{mutations.recover.error.message}</Alert>}<Group justify="flex-end"><Button variant="default" onClick={() => setRecovering(false)}>Cancel</Button><Button color="orange" loading={mutations.recover.isPending} onClick={async () => { const result = await mutations.recover.mutateAsync(id); setRecoveryResults(result.recovery.results); setRecovering(false); await query.refetch(); }}>Run recovery</Button></Group></Stack></Modal>
    <Modal opened={closeTarget !== null} onClose={() => !closeMutation.isPending && setCloseTarget(null)} title="Confirm manual position close" centered>{closeTarget && <Stack><Text>Submit a close order for the tracked position in <strong>{closeTarget.tradingAccount?.displayName ?? `TradingAccount #${closeTarget.tradingAccountId}`} · {closeTarget.environment}</strong>?</Text>{closeTarget.environment === "LIVE" && <Alert color="red" title="LIVE brokerage action">This can execute a real-money trade in the named LIVE TradingAccount.</Alert>}{closeMutation.isError && <Alert color="red">{closeMutation.error.message}</Alert>}<Group justify="flex-end"><Button variant="default" onClick={() => setCloseTarget(null)}>Cancel</Button><Button color="red" loading={closeMutation.isPending} onClick={async () => { const trackedPositionId = closeTarget.projection?.links.trackedPositionId; if (!trackedPositionId) return; await closeMutation.mutateAsync({ tradingAccountId: closeTarget.tradingAccountId, trackedPositionId }); setCloseTarget(null); await query.refetch(); }}>Close position</Button></Group></Stack>}</Modal>
  </Stack>;
}

function Fact({ label, value }: { label: string; value: React.ReactNode }) { return <div><Text size="xs" c="dimmed">{label}</Text><Text fw={600}>{value}</Text></div>; }
