import { Router } from 'express';
import { volatilityAssessmentLatestController, volatilityAssessmentListController, volatilityAssessmentDetailController, volatilityAssessmentRunController } from '../controllers/volatility-assessment.controller.js';
import { requirePermission, requireSystemOwnerAccess } from '../middleware/rbac.js';
import { PlatformPermission } from '../types/platform-rbac.js';
import { trendAssessmentLatestController, trendAssessmentListController, trendAssessmentDetailController, trendAssessmentRunController } from '../controllers/trend-assessment.controller.js';
import { calendarCreateController, calendarDeleteController, calendarListController, calendarUpdateController, intradayMinuteAuthorityStatusController, marketBackfillController, marketDataStatusController, trendDayController, trendLabController } from '../controllers/market-data.controller.js';
import { breadthAssessmentLatestController, breadthAssessmentListController, breadthAssessmentDetailController, breadthAssessmentRunController } from '../controllers/breadth-assessment.controller.js';
import { participationAssessmentLatestController, participationAssessmentListController, participationAssessmentDetailController, participationAssessmentRunController } from '../controllers/participation-assessment.controller.js';
import { breadthObservationLatestController, breadthObservationListController, breadthObservationDetailController, breadthObservationRunController } from '../controllers/breadth-observation.controller.js';
import { intradayStressAssessmentLatestController, intradayStressAssessmentListController, intradayStressAssessmentDetailController, intradayStressAssessmentRunController } from '../controllers/intraday-stress-assessment.controller.js';
import { tiingoDailyStatusController } from '../controllers/tiingo-daily.controller.js';
import { breadthV2ObservationStatusController, breadthV2ObservationLatestController, breadthV2ObservationListController, breadthV2ObservationDetailController, breadthV2ObservationRunController } from '../controllers/breadth-v2-observation.controller.js';
import { breadthV2AssessmentStatusController, breadthV2AssessmentLatestController, breadthV2AssessmentListController, breadthV2AssessmentDetailController, breadthV2AssessmentRunController } from '../controllers/breadth-v2-assessment.controller.js';
import { breadthV2ShadowSnapshot } from '../workers/breadth-v2-shadow.worker.js';
const router = Router();
router.get('/breadth-v2-shadow/status', requirePermission(PlatformPermission.MARKET_DATA_READ), (_req, res) => { res.json(breadthV2ShadowSnapshot()); });
router.get('/breadth-v2-assessments/status', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthV2AssessmentStatusController);
router.get('/breadth-v2-assessments/latest', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthV2AssessmentLatestController);
router.get('/breadth-v2-assessments', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthV2AssessmentListController);
router.get('/breadth-v2-assessments/:id', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthV2AssessmentDetailController);
router.post('/breadth-v2-assessments/run', requireSystemOwnerAccess, breadthV2AssessmentRunController);
router.get('/breadth-v2-observations/status', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthV2ObservationStatusController);
router.get('/breadth-v2-observations/latest', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthV2ObservationLatestController);
router.get('/breadth-v2-observations', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthV2ObservationListController);
router.get('/breadth-v2-observations/:id', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthV2ObservationDetailController);
router.post('/breadth-v2-observations/run', requireSystemOwnerAccess, breadthV2ObservationRunController);
router.get('/tiingo-daily/status', requirePermission(PlatformPermission.MARKET_DATA_READ), tiingoDailyStatusController);
router.get('/intraday-stress-provider/status', requirePermission(PlatformPermission.MARKET_DATA_READ), intradayMinuteAuthorityStatusController);
router.get('/volatility-assessments/latest', requirePermission(PlatformPermission.MARKET_DATA_READ), volatilityAssessmentLatestController);
router.get('/volatility-assessments', requirePermission(PlatformPermission.MARKET_DATA_READ), volatilityAssessmentListController);
router.get('/volatility-assessments/:id', requirePermission(PlatformPermission.MARKET_DATA_READ), volatilityAssessmentDetailController);
router.post('/volatility-assessments/run', requireSystemOwnerAccess, volatilityAssessmentRunController);
router.get('/trend-assessments/latest', requirePermission(PlatformPermission.MARKET_DATA_READ), trendAssessmentLatestController);
router.get('/trend-assessments', requirePermission(PlatformPermission.MARKET_DATA_READ), trendAssessmentListController);
router.get('/trend-assessments/:id', requirePermission(PlatformPermission.MARKET_DATA_READ), trendAssessmentDetailController);
router.post('/trend-assessments/run', requireSystemOwnerAccess, trendAssessmentRunController);
router.get('/breadth-assessments/latest', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthAssessmentLatestController);
router.get('/breadth-assessments', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthAssessmentListController);
router.get('/breadth-assessments/:id', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthAssessmentDetailController);
router.post('/breadth-assessments/run', requireSystemOwnerAccess, breadthAssessmentRunController);
router.get('/participation-assessments/latest', requirePermission(PlatformPermission.MARKET_DATA_READ), participationAssessmentLatestController);
router.get('/participation-assessments', requirePermission(PlatformPermission.MARKET_DATA_READ), participationAssessmentListController);
router.get('/participation-assessments/:id', requirePermission(PlatformPermission.MARKET_DATA_READ), participationAssessmentDetailController);
router.post('/participation-assessments/run', requireSystemOwnerAccess, participationAssessmentRunController);
router.get('/breadth-observations/latest', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthObservationLatestController);
router.get('/breadth-observations', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthObservationListController);
router.get('/breadth-observations/:id', requirePermission(PlatformPermission.MARKET_DATA_READ), breadthObservationDetailController);
router.post('/breadth-observations/run', requireSystemOwnerAccess, breadthObservationRunController);
router.get('/intraday-stress-assessments/latest', requirePermission(PlatformPermission.MARKET_DATA_READ), intradayStressAssessmentLatestController);
router.get('/intraday-stress-assessments', requirePermission(PlatformPermission.MARKET_DATA_READ), intradayStressAssessmentListController);
router.get('/intraday-stress-assessments/:id', requirePermission(PlatformPermission.MARKET_DATA_READ), intradayStressAssessmentDetailController);
router.post('/intraday-stress-assessments/run', requireSystemOwnerAccess, intradayStressAssessmentRunController);
router.get('/calendar', requirePermission(PlatformPermission.MARKET_DATA_READ), calendarListController);
router.post('/calendar', requirePermission(PlatformPermission.MARKET_CALENDAR_WRITE), calendarCreateController);
router.put('/calendar/:id', requirePermission(PlatformPermission.MARKET_CALENDAR_WRITE), calendarUpdateController);
router.delete('/calendar/:id', requirePermission(PlatformPermission.MARKET_CALENDAR_WRITE), calendarDeleteController);
router.get('/status', requirePermission(PlatformPermission.MARKET_DATA_READ), marketDataStatusController);
router.get('/trend-lab', requirePermission(PlatformPermission.MARKET_DATA_READ), trendLabController);
router.get('/trend-lab/day', requirePermission(PlatformPermission.MARKET_DATA_READ), trendDayController);
router.post('/backfill', requireSystemOwnerAccess, marketBackfillController);
export default router;
