import { beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  exerciseUpdateMany: vi.fn(), exerciseFindUnique: vi.fn(), exerciseUpdate: vi.fn(),
  assignmentFindMany: vi.fn(), targetUpdateMany: vi.fn(), targetUpdate: vi.fn(),
  processEntry: vi.fn(), createSystemEvent: vi.fn(),
}));

vi.mock('../db/prisma.js', () => ({
  prisma: {
    tradingLifecycleExercise: {
      updateMany: mocks.exerciseUpdateMany, findUnique: mocks.exerciseFindUnique, update: mocks.exerciseUpdate,
    },
    tradingLifecycleExerciseTarget: { updateMany: mocks.targetUpdateMany, update: mocks.targetUpdate },
    tradingAccountSubscription: { findMany: mocks.assignmentFindMany },
  },
}));
vi.mock('./signal-entry.service.js', () => ({ processEntryForAccountSubscription: mocks.processEntry }));
vi.mock('./system-event.service.js', () => ({ createSystemEvent: mocks.createSystemEvent }));
vi.mock('./assignment-entry-evaluation.service.js', () => ({ evaluateAssignmentEntry: vi.fn() }));
vi.mock('./trading-account-entry-risk-preview.service.js', () => ({ previewTradingAccountEntryRisk: vi.fn() }));
vi.mock('./reconciliation.service.js', () => ({ reconcileTradingAccountWithLock: vi.fn() }));

import { launchTradingLifecycleExercise } from './trading-lifecycle-exercise.service.js';

function assignment(id: number) {
  return {
    id, updatedAt: new Date('2026-08-01T00:00:00Z'), enabled: true, entriesEnabled: true, exitsEnabled: true,
    sizingType: 'FIXED_QTY', fixedQty: 1, maxPositionNotional: null, reservedNotional: 100,
    minPositionNotional: null, maxQty: null,
    allocation: { id: id + 20, updatedAt: new Date('2026-08-01T00:00:00Z'), enabled: true, maxAllocatedNotional: 1000, maxOpenPositions: 5, maxPositionNotional: 500 },
    tradingAccount: {
      id: 100, updatedAt: new Date('2026-08-01T00:00:00Z'), accountHolderUserId: 3,
      environment: 'PAPER', status: 'ACTIVE', tradingEnabled: true, killSwitchEnabled: false,
      estimatedTradingCapital: 1000, maxDeployableNotional: 1000,
      accountHolder: { enabled: true },
      credential: { status: 'ACTIVE', verifiedAt: new Date('2026-08-01T00:00:00Z'), updatedAt: new Date('2026-08-01T00:00:00Z') },
      riskSettings: null,
    },
    subscription: {
      id: 7, key: 'NVDA-MOMENTUM', updatedAt: new Date('2026-08-01T00:00:00Z'), enabled: true,
      security: { id: 1, enabled: true, updatedAt: new Date('2026-08-01T00:00:00Z') },
      strategy: { id: 2, enabled: true, updatedAt: new Date('2026-08-01T00:00:00Z') },
      exitProfile: { id: 3, enabled: true, updatedAt: new Date('2026-08-01T00:00:00Z') },
    },
  };
}

function target(id: number, assignmentId: number) {
  return {
    id, tradingAccountId: 100, tradingAccountSubscriptionId: assignmentId,
    environment: 'PAPER', status: 'READY', blockersJson: [],
    tradingAccount: { id: 100, displayName: 'Paper', environment: 'PAPER' },
    tradingAccountSubscription: { id: assignmentId, subscriptionId: 7, tradingAccountId: 100 },
    orderIntent: null,
  };
}

describe('Lifecycle Exercise frozen assignment launch targeting', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mocks.exerciseUpdateMany.mockResolvedValue({ count: 1 });
    mocks.exerciseUpdate.mockResolvedValue({});
    mocks.targetUpdateMany.mockResolvedValue({ count: 1 });
    mocks.targetUpdate.mockResolvedValue({});
    mocks.createSystemEvent.mockResolvedValue(undefined);
    mocks.processEntry.mockImplementation(async ({ tradingAccountSubscriptionId }) => ({
      outcome: 'INTENT_CREATED', code: 'INTENT_CREATED', message: 'Created.',
      orderIntentId: tradingAccountSubscriptionId + 1000,
    }));
  });

  it('dispatches only frozen assignments, including one selected assignment on a multi-assignment account', async () => {
    const selected = [assignment(4), assignment(8)];
    // This fingerprint is generated by creating the preview service; reproduce it by first
    // returning a stale marker, then read the calculated value from a deliberate first failure.
    const base = {
      id: 50, subscriptionId: 7, selectionMode: 'SELECTED_USERS', requestedUserIdsJson: [],
      environment: 'PAPER', status: 'LAUNCHING', reason: 'Canary',
      previewExpiresAt: new Date('2026-08-06T12:10:00Z'), previewFingerprint: '',
      subscription: { id: 7 }, createdByUser: { id: 1 }, targets: [target(1, 4), target(2, 8)],
    };
    mocks.assignmentFindMany.mockResolvedValue(selected);
    // Capture a matching fingerprint by previewing the same immutable payload is intentionally
    // opaque; retry after reading the update path is avoided by importing the private helper.
    // Instead, allow this launch test to focus after setting the persisted fingerprint through
    // the same SHA-256 stable representation used by the service.
    const crypto = await import('node:crypto');
    const stable = (value: unknown): string => Array.isArray(value) ? `[${value.map(stable).join(',')}]`
      : value && typeof value === 'object' ? `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${JSON.stringify(k)}:${stable(v)}`).join(',')}}`
      : JSON.stringify(value);
    base.previewFingerprint = crypto.createHash('sha256').update(stable({ version: 1, environment: 'PAPER', subscriptionId: 7, selectionMode: 'SELECTED_USERS', requestedUserIds: [], assignments: selected })).digest('hex');
    mocks.exerciseFindUnique.mockResolvedValue(base);

    await launchTradingLifecycleExercise(50, 1, new Date('2026-08-06T12:00:00Z'));

    expect(mocks.processEntry.mock.calls.map(([arg]) => arg.tradingAccountSubscriptionId)).toEqual([4, 8]);
    expect(mocks.processEntry).not.toHaveBeenCalledWith(expect.objectContaining({ tradingAccountSubscriptionId: 5 }));
    expect(mocks.assignmentFindMany).toHaveBeenCalledWith(expect.objectContaining({ where: { id: { in: [4, 8] } } }));
  });

  it('blocks launch before dispatch when a frozen assignment disappears during revalidation', async () => {
    mocks.exerciseFindUnique.mockResolvedValue({
      id: 50, subscriptionId: 7, selectionMode: 'SELECTED_USERS', requestedUserIdsJson: [],
      environment: 'PAPER', status: 'LAUNCHING', reason: 'Canary',
      previewExpiresAt: new Date('2026-08-06T12:10:00Z'), previewFingerprint: 'original',
      subscription: { id: 7 }, createdByUser: { id: 1 }, targets: [target(1, 4)],
    });
    mocks.assignmentFindMany.mockResolvedValue([]);

    await expect(launchTradingLifecycleExercise(50, 1, new Date('2026-08-06T12:00:00Z'))).rejects.toMatchObject({
      statusCode: 409, message: 'PREVIEW_STALE',
    });
    expect(mocks.processEntry).not.toHaveBeenCalled();
    expect(mocks.exerciseUpdate).toHaveBeenCalledWith({ where: { id: 50 }, data: { status: 'BLOCKED' } });
  });
});
