// @vitest-environment happy-dom
import { MantineProvider } from "@mantine/core";
import { cleanup, render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { LiveOperationsResponse } from "./types";

const mocks = vi.hoisted(() => ({ scope: { selectedAccount: null as null | { id: number; environment: "LIVE" | "PAPER" }, isAll: true }, data: null as LiveOperationsResponse | null }));
vi.mock("../tradingAccountScope/useTradingAccountScope", () => ({ useTradingAccountScope: () => mocks.scope }));
vi.mock("../tradingAccountScope/TradingAccountScopeSelector", () => ({ TradingAccountScopeSelector: () => <label>Account scope<select aria-label="Account scope"><option>All accounts</option></select></label> }));
vi.mock("./hooks", () => ({ useLiveOperations: () => ({ data: mocks.data, isLoading: false, isError: false }) }));
vi.mock("../../lib/api", () => ({ getAdminToken: () => "token" }));
import { LiveOperationsPage } from "./LiveOperationsPage";
afterEach(cleanup);

const snapshot: LiveOperationsResponse["accounts"][number] = { account: { id: 7, displayName: "Bobby Live", broker: "ALPACA", environment: "LIVE", status: "ACTIVE" }, generatedAt: "2026-08-25T20:00:00Z", health: "HEALTHY", operationalState: "HEALTHY", summary: "One open Live position.", exposure: { openPositionCount: 1 }, positions: [], positionLifecycle: { health: "HEALTHY", state: "HEALTHY" }, exitCapability: { state: "READY", actionDue: false, strategyResolved: true, evaluatorHealth: "HEALTHY", authorizationActive: true, environmentWritePolicy: "ALLOWED" }, reconciliation: { health: "HEALTHY", state: "HEALTHY", findingCount: 0, freshness: "CURRENT", evidenceAt: "2026-08-25T20:00:00Z", context: null }, workers: { health: "HEALTHY", items: [] }, entryPosture: { state: "DISARMED", authorizationActive: false, armingId: null }, safetyPosture: { tradingEnabled: false, killSwitchEnabled: true, riskReducingAuthorization: "ACTIVE", entryAuthorization: "INACTIVE", deploymentRole: "PRODUCTION_EXECUTOR", liveRiskReducingWritesAllowed: true, exclusiveWriterOwnershipProven: false }, completedCanary: { id: 2, completedAt: "2026-08-25T20:00:00Z" }, attentionReasons: [], nextOperatorAction: { code: "MONITORING", message: "No action required. Continue monitoring the open position." } };
const productionContext = { applicationEnvironment: "production", deploymentRole: "PRODUCTION_EXECUTOR", operationalAuthority: "AUTHORITATIVE_EXECUTOR", healthScope: "CURRENT_ENVIRONMENT_ONLY", liveEntryWritePolicy: "ALLOWED", liveRiskReducingWritePolicy: "ALLOWED" } as const;
function response(): LiveOperationsResponse { return { generatedAt: snapshot.generatedAt, environmentContext: productionContext, summary: { liveAccountCount: 1, accountsWithExposure: 1, openPositionCount: 1, accountsRequiringAttention: 0, accountsDegradedOrStale: 0, accountsObservationLimited: 0, accountsWithActiveEntryArming: 0, health: "HEALTHY" }, accounts: [snapshot] }; }
function renderPage() { return render(<MantineProvider><MemoryRouter initialEntries={["/live-operations"]}><LiveOperationsPage /></MemoryRouter></MantineProvider>); }
describe("Live Operations page", () => {
  it("renders the all-Live overview without trading or authorization controls", () => { mocks.scope = { selectedAccount: null, isAll: true }; mocks.data = response(); renderPage(); expect(screen.getByText("Live accounts")).toBeTruthy(); expect(screen.getByText("Bobby Live")).toBeTruthy(); expect(screen.queryByRole("button", { name: /grant|arm|close|cancel/i })).toBeNull(); });
  it.each(["HEALTHY", "DEGRADED", "UNKNOWN", "ACTION_REQUIRED"] as const)("renders %s account health", (health) => { mocks.scope = { selectedAccount: null, isAll: true }; mocks.data = { ...response(), accounts: [{ ...snapshot, health, operationalState: health }] }; renderPage(); expect(screen.getAllByText(health.replaceAll("_", " ")).length).toBeGreaterThan(0); });
  it("renders single-account safety semantics and responsive position layout", () => { mocks.scope = { selectedAccount: { id: 7, environment: "LIVE" }, isAll: false }; mocks.data = response(); renderPage(); expect(screen.getByText("Account safety posture")).toBeTruthy(); expect(screen.getByText(/Exclusive Live-writer ownership is not proven/)).toBeTruthy(); expect(screen.getByText("Position-management capability")).toBeTruthy(); });
  it("shows the production executor banner", () => { mocks.scope = { selectedAccount: null, isAll: true }; mocks.data = response(); renderPage(); expect(screen.getByText("PRODUCTION ENVIRONMENT · LIVE EXECUTOR")).toBeTruthy(); });
  it("shows observer limitations without a local repair recommendation", () => { mocks.scope = { selectedAccount: { id: 7, environment: "LIVE" }, isAll: false }; const position = { id: 80, symbol: "RSP", qty: 4, avgEntryPrice: 221.3, status: "open", lastSyncedAt: snapshot.generatedAt, brokerLocalAgreement: "ALIGNED", lifecycleState: "UNAVAILABLE_LOCALLY", productionHealth: "UNKNOWN_FROM_THIS_ENVIRONMENT", observerLimitation: { code: "EXPECTED_OBSERVATION_LIMITATION" as const, title: "Lifecycle evidence unavailable locally", message: "No local repair is required; verify authoritative lifecycle health in production.", causalChain: ["Local attribution is unavailable.", "Therefore no local exit profile can be resolved.", "Therefore local exit evaluation cannot manage this position."] }, attribution: { resolved: false, finding: "EXPECTED_OBSERVATION_LIMITATION", assignmentId: null, assignmentKey: null, subscriptionId: null, configSnapshotPresent: false }, exitProfile: null, exitEvaluation: { applicable: false, eligible: false, health: "BACKING_OFF", lastSuccessAt: null, freshness: "EXPIRED" }, actionDue: false, activeOrderIntent: null, expectation: "Exit management is not authoritative in this environment.", attentionReasons: [] }; const observerResponse: LiveOperationsResponse = { ...response(), environmentContext: { ...productionContext, applicationEnvironment: "development", deploymentRole: "OBSERVATION_ONLY", operationalAuthority: "OBSERVATION_ONLY", liveEntryWritePolicy: "OBSERVATION_ONLY", liveRiskReducingWritePolicy: "OBSERVATION_ONLY" }, summary: { ...response().summary, accountsObservationLimited: 1 }, accounts: [{ ...snapshot, health: "UNKNOWN", operationalState: "OBSERVATION_ONLY", positions: [position], positionLifecycle: { health: "UNKNOWN", state: "UNAVAILABLE_LOCALLY" }, exitCapability: { ...snapshot.exitCapability, state: "OBSERVATION_ONLY", strategyResolved: false, environmentWritePolicy: "OBSERVATION_ONLY" }, reconciliation: { ...snapshot.reconciliation, health: "UNKNOWN", state: "NOT_AUTHORITATIVE" }, nextOperatorAction: { code: "VERIFY_IN_PRODUCTION", message: "No local repair or Live-management action is required. Verify canonical lifecycle health in the production executor." } }] }; mocks.data = observerResponse; renderPage(); expect(screen.getByText("DEVELOPMENT ENVIRONMENT · OBSERVATION ONLY")).toBeTruthy(); expect(screen.getByText("Lifecycle evidence unavailable locally")).toBeTruthy(); expect(screen.getByText(/Production health: UNKNOWN FROM THIS ENVIRONMENT/)).toBeTruthy(); expect(screen.queryByText(/repair the local record/i)).toBeNull(); expect(screen.queryByRole("button", { name: /grant|arm|close|repair|cancel/i })).toBeNull(); });
  it("keeps production missing attribution critical", () => { mocks.scope = { selectedAccount: null, isAll: true }; mocks.data = { ...response(), summary: { ...response().summary, accountsRequiringAttention: 1 }, accounts: [{ ...snapshot, health: "ACTION_REQUIRED", operationalState: "ACTION_REQUIRED", positionLifecycle: { health: "ACTION_REQUIRED", state: "ACTION_REQUIRED" } }] }; renderPage(); expect(screen.getAllByText("ACTION REQUIRED").length).toBeGreaterThan(0); expect(screen.getByText("Action required")).toBeTruthy(); });
});
