import { Alert, Badge, Button, Card, Group, SimpleGrid, Stack, Text, Title } from "@mantine/core";
import { Link } from "react-router-dom";
import { getAdminToken } from "../../lib/api";
import { TradingAccountScopeSelector } from "../tradingAccountScope/TradingAccountScopeSelector";
import { useTradingAccountScope } from "../tradingAccountScope/useTradingAccountScope";
import { useLiveOperations } from "./hooks";
import type { LiveAccountOperations } from "./types";

const color = (status: string) => status === "HEALTHY" || status === "READY" || status === "CURRENT" || status === "DISARMED" ? "green" : status === "ACTION_REQUIRED" || status === "BLOCKED" || status === "EXPIRED" ? "red" : status === "DEGRADED" || status === "STALE" || status === "NOT_AUTHORIZED" ? "yellow" : "gray";
const stamp = (value: string | null) => value ? new Date(value).toLocaleString() : "No evidence recorded";
function Status({ label, value }: { label: string; value: string }) { return <Group justify="space-between" gap="xs"><Text size="sm">{label}</Text><Badge color={color(value)}>{value.replaceAll("_", " ")}</Badge></Group>; }

function AccountOverview({ snapshot }: { snapshot: LiveAccountOperations }) {
  return <Card withBorder data-testid="live-account-overview"><Group justify="space-between" align="flex-start"><div><Title order={3}>{snapshot.account.displayName}</Title><Text size="xs" c="dimmed">{snapshot.account.broker} · LIVE · Account #{snapshot.account.id}</Text></div><Badge color={color(snapshot.health)}>{snapshot.health.replaceAll("_", " ")}</Badge></Group><Stack gap="xs" mt="md"><Status label="Open exposure" value={`${snapshot.exposure.openPositionCount} POSITION${snapshot.exposure.openPositionCount === 1 ? "" : "S"}`} /><Status label="Position lifecycle" value={snapshot.positionLifecycle.health} /><Status label="Exit capability" value={snapshot.exitCapability.state} /><Status label="Reconciliation" value={snapshot.reconciliation.health} /><Status label="Workers" value={snapshot.workers.health} /><Status label="Entry posture" value={snapshot.entryPosture.state} /><Text size="xs" c="dimmed">Evidence generated {stamp(snapshot.generatedAt)}</Text><Alert color={snapshot.health === "HEALTHY" ? "blue" : "yellow"} title={`Next operator action · ${snapshot.nextOperatorAction.code.replaceAll("_", " ")}`}>{snapshot.nextOperatorAction.message}</Alert><Button component={Link} to={`/live-operations?account=${snapshot.account.id}`} variant="default">View account operations</Button></Stack></Card>;
}

function AccountDetail({ snapshot }: { snapshot: LiveAccountOperations }) {
  return <Stack gap="md"><Alert color={snapshot.health === "HEALTHY" ? "green" : "yellow"} title={`${snapshot.account.displayName} · ${snapshot.health.replaceAll("_", " ")}`}>{snapshot.summary}</Alert>
    <SimpleGrid cols={{ base: 1, md: 2 }}><Card withBorder><Title order={3}>Position-management capability</Title><Stack mt="sm" gap="xs"><Status label="Exit strategy resolved" value={snapshot.exitCapability.strategyResolved ? "READY" : "BLOCKED"}/><Status label="Exit evaluator" value={snapshot.exitCapability.evaluatorHealth}/><Status label="Risk-reducing write path" value={snapshot.exitCapability.state}/><Status label="RISK_REDUCING authority" value={snapshot.exitCapability.authorizationActive ? "READY" : "NOT_AUTHORIZED"}/><Status label="Exit action" value={snapshot.exitCapability.actionDue ? "ACTION_REQUIRED" : "NOT_APPLICABLE"}/><Status label="Environment Live-write policy" value={snapshot.exitCapability.environmentWritePolicy}/></Stack></Card>
    <Card withBorder><Title order={3}>Account safety posture</Title><Stack mt="sm" gap="xs"><Status label="Account trading" value={snapshot.safetyPosture.tradingEnabled ? "ENABLED" : "DISABLED"}/><Status label="Kill switch" value={snapshot.safetyPosture.killSwitchEnabled ? "ENABLED" : "OFF"}/><Status label="Entry posture" value={snapshot.entryPosture.state}/><Status label="ENTRY authority" value={snapshot.safetyPosture.entryAuthorization}/><Status label="RISK_REDUCING authority" value={snapshot.safetyPosture.riskReducingAuthorization}/><Text size="sm">This environment is configured as <b>{snapshot.safetyPosture.deploymentRole.replaceAll("_", " ")}</b>. Exclusive Live-writer ownership is not proven.</Text><Button component={Link} to={`/trading-accounts/${snapshot.account.id}?tab=readiness`} variant="subtle">View authorization on Readiness</Button></Stack></Card></SimpleGrid>
    <Card withBorder><Group justify="space-between"><Title order={3}>Open Live exposure</Title><Badge>{snapshot.positions.length}</Badge></Group>{snapshot.positions.length === 0 ? <Text c="dimmed" mt="sm">No open Live positions.</Text> : <SimpleGrid cols={{ base: 1, lg: 2 }} mt="md">{snapshot.positions.map((position) => <Card withBorder key={position.id}><Group justify="space-between"><Title order={4}>{position.symbol} · {position.qty} shares</Title><Badge color={position.attentionReasons.length ? "red" : "green"}>{position.status}</Badge></Group><Text size="sm">Average entry: {position.avgEntryPrice === null ? "Unavailable" : `$${position.avgEntryPrice.toFixed(2)}`}</Text><Text size="sm">Broker/local agreement: {position.brokerLocalAgreement}</Text><Text size="sm">TrackedPosition #{position.id} · assignment {position.attribution.assignmentKey ?? "unattributed"}</Text><Text size="sm">Exit profile: {position.exitProfile ? `${position.exitProfile.name} (${position.exitProfile.mode})` : "unresolved"}</Text><Text size="sm">Evaluation: {position.exitEvaluation.health} · {position.exitEvaluation.freshness} · {stamp(position.exitEvaluation.lastSuccessAt)}</Text><Text size="sm">{position.expectation}</Text>{position.activeOrderIntent && <Text size="sm">OrderIntent #{position.activeOrderIntent.id} · {position.activeOrderIntent.status}</Text>}{position.attentionReasons.map((reason) => <Alert key={reason} color="red" mt="xs">{reason}</Alert>)}<Button component={Link} to={`/positions/open?account=${snapshot.account.id}`} variant="subtle" mt="sm">Open position records</Button></Card>)}</SimpleGrid>}</Card>
    <SimpleGrid cols={{ base: 1, md: 2 }}><Card withBorder><Title order={3}>Reconciliation</Title><Status label="Health" value={snapshot.reconciliation.health}/><Status label="Freshness" value={snapshot.reconciliation.freshness}/><Text size="xs" c="dimmed">Evidence {stamp(snapshot.reconciliation.evidenceAt)}</Text><Button component={Link} to={`/trading-accounts/${snapshot.account.id}/reconciliation`} variant="subtle">Full reconciliation</Button></Card><Card withBorder><Title order={3}>Account workers</Title><Stack gap="xs" mt="sm">{snapshot.workers.items.map((worker) => <div key={worker.key}><Status label={worker.key.replaceAll("_", " ")} value={worker.status}/><Text size="xs" c="dimmed">{worker.freshness} · {stamp(worker.evidenceAt)}</Text></div>)}</Stack></Card></SimpleGrid>
    <Alert color={snapshot.health === "HEALTHY" ? "blue" : "yellow"} title={`Next operator action · ${snapshot.nextOperatorAction.code.replaceAll("_", " ")}`}>{snapshot.nextOperatorAction.message}</Alert></Stack>;
}

export function LiveOperationsPage() {
  const scope = useTradingAccountScope();
  const selectedLiveId = scope.selectedAccount?.environment === "LIVE" ? scope.selectedAccount.id : undefined;
  const query = useLiveOperations(getAdminToken(), selectedLiveId);
  const data = query.data; const selected = data?.accounts[0];
  return <main><Stack gap="lg"><Group justify="space-between" align="flex-end"><div><Title order={2}>Live Operations</Title><Text size="sm" c="dimmed">Read-only, continuously derived monitoring of Live exposure and position-management capability.</Text></div><TradingAccountScopeSelector mode="ACCOUNT_FILTERABLE" expanded variant="dashboard" /></Group>{query.isLoading ? <Text>Loading Live operations…</Text> : query.isError ? <Alert color="red">Live operational state is unavailable.</Alert> : !data ? null : selectedLiveId && selected ? <AccountDetail snapshot={selected}/> : <><SimpleGrid cols={{ base: 2, md: 6 }}>{[["Live accounts",data.summary.liveAccountCount],["With exposure",data.summary.accountsWithExposure],["Open positions",data.summary.openPositionCount],["Action required",data.summary.accountsRequiringAttention],["Degraded / stale",data.summary.accountsDegradedOrStale],["Entry armed",data.summary.accountsWithActiveEntryArming]].map(([label,value]) => <Card withBorder key={label}><Text size="xs" c="dimmed">{label}</Text><Text size="xl" fw={700}>{value}</Text></Card>)}</SimpleGrid>{scope.selectedAccount?.environment === "PAPER" && <Alert color="blue">Paper accounts are excluded. Showing all accessible Live accounts.</Alert>}<SimpleGrid cols={{ base: 1, lg: 2 }}>{data.accounts.map((snapshot) => <AccountOverview key={snapshot.account.id} snapshot={snapshot}/>)}</SimpleGrid>{data.accounts.length === 0 && <Alert color="blue">No accessible Live accounts.</Alert>}</>}</Stack></main>;
}
