import { Alert, Badge, Card, Group, Loader, Stack, Text, Title, useMantineColorScheme, useMantineTheme } from "@mantine/core";
import { CandlestickSeries, ColorType, createChart, createSeriesMarkers, CrosshairMode, HistogramSeries, LineSeries, LineStyle, type IChartApi, type SeriesMarker, type Time, type UTCTimestamp } from "lightweight-charts";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { decisionWindow, filterRegularSessionBars, hasEventOutsideRegularHours, momentumChartPreferenceKey, parseMomentumChartPreferences, priorityMarkers, sessionWindow, type MomentumChartLayer, type MomentumChartRange } from "../momentumChartHelpers";
import type { MomentumMarketChartInterval, MomentumMarketChartMarkerType, MomentumMarketChartResponse } from "../types";
import { MomentumChartControls } from "./MomentumChartControls";

type Props = { data: MomentumMarketChartResponse | undefined; interval: MomentumMarketChartInterval; onIntervalChange: (interval: MomentumMarketChartInterval) => void; isLoading?: boolean; isFetching?: boolean; error?: Error | null; title?: string; candidate?: boolean };
type TooltipData = { bar: MomentumMarketChartResponse["bars"][number]; markers: MomentumMarketChartResponse["markers"] } | null;
const chartTime = (timestamp: string) => Math.floor(new Date(timestamp).getTime() / 1000) as UTCTimestamp;
function nearestChartTime(timestamp: string, times: UTCTimestamp[]) { const target = chartTime(timestamp); return times.reduce((nearest, time) => Math.abs(time - target) < Math.abs(nearest - target) ? time : nearest, times[0] ?? target); }
function markerAppearance(type: MomentumMarketChartMarkerType) {
  if (type === "ENTRY_READY") return { color: "#20c997", shape: "arrowUp" as const, position: "belowBar" as const };
  if (type === "ENTRY_BLOCKED" || type === "HANDOFF_CANCELLED") return { color: "#fa5252", shape: "arrowDown" as const, position: "aboveBar" as const };
  if (type.startsWith("CATALYST")) return { color: "#4dabf7", shape: "circle" as const, position: "aboveBar" as const };
  if (type.startsWith("HANDOFF")) return { color: "#cc5de8", shape: "square" as const, position: "aboveBar" as const };
  if (type === "CANDIDATE_DISCOVERED") return { color: "#ffd43b", shape: "circle" as const, position: "belowBar" as const };
  return { color: "#adb5bd", shape: "circle" as const, position: "aboveBar" as const };
}
function markerText(type: MomentumMarketChartMarkerType) { return ({ PRICE_CHECK: "Check", CATALYST_PUBLISHED: "Catalyst", CATALYST_RECEIVED: "Received", CANDIDATE_DISCOVERED: "Discovered", ENTRY_READY: "Ready", ENTRY_BLOCKED: "Blocked", HANDOFF_PREPARED: "Prepared", HANDOFF_SENT: "Sent", HANDOFF_CANCELLED: "Cancelled" })[type]; }
const formatPrice = (value: number | null | undefined) => value == null ? "-" : value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 4 });
const formatNewYork = (timestamp: string) => new Intl.DateTimeFormat(undefined, { timeZone: "America/New_York", dateStyle: "medium", timeStyle: "short" }).format(new Date(timestamp));

export function MomentumMarketChart({ data, interval, onIntervalChange, isLoading = false, isFetching = false, error = null, title = "Market context", candidate = false }: Props) {
  const containerRef = useRef<HTMLDivElement>(null); const chartRef = useRef<IChartApi | null>(null);
  const theme = useMantineTheme(); const { colorScheme } = useMantineColorScheme(); const isDark = colorScheme === "dark";
  const saved = useMemo(() => parseMomentumChartPreferences(typeof localStorage === "undefined" ? null : localStorage.getItem(momentumChartPreferenceKey)), []);
  const [layers, setLayers] = useState(saved.layers); const [sessionChoice, setSessionChoice] = useState<boolean | null>(null);
  const extendedHours = sessionChoice ?? (saved.extendedHours || Boolean(candidate && data && hasEventOutsideRegularHours(data.markers)));
  const [range, setRange] = useState<MomentumChartRange>(candidate ? "decision" : "session");
  const [expanded, setExpanded] = useState(false); const [tooltip, setTooltip] = useState<TooltipData>(null);
  useEffect(() => { localStorage.setItem(momentumChartPreferenceKey, JSON.stringify({ layers, extendedHours })); }, [extendedHours, layers]);
  const bars = useMemo(() => extendedHours ? data?.bars ?? [] : filterRegularSessionBars(data?.bars ?? []), [data, extendedHours]);
  const visibleMarkers = useMemo(() => priorityMarkers(data?.markers ?? [], layers).filter((marker) => extendedHours || isFinite(new Date(marker.timestamp).getTime())), [data, extendedHours, layers]);
  const barByTime = useMemo(() => new Map(bars.map((bar) => [chartTime(bar.timestamp), bar])), [bars]); const barTimes = useMemo(() => [...barByTime.keys()], [barByTime]);
  const markersByTime = useMemo(() => { const result = new Map<number, MomentumMarketChartResponse["markers"]>(); for (const marker of visibleMarkers) { const time = nearestChartTime(marker.timestamp, barTimes); result.set(time, [...(result.get(time) ?? []), marker]); } return result; }, [barTimes, visibleMarkers]);
  const applyRange = useCallback((chart: IChartApi) => { const window = range === "decision" ? decisionWindow(data?.markers ?? [], bars, interval) : range === "session" ? sessionWindow(bars) : null; if (window) chart.timeScale().setVisibleRange({ from: Math.floor(window.from / 1000) as UTCTimestamp, to: Math.floor(window.to / 1000) as UTCTimestamp }); else chart.timeScale().fitContent(); }, [bars, data?.markers, interval, range]);

  useEffect(() => {
    const container = containerRef.current; if (!container || !data || !bars.length) return;
    const chart = createChart(container, { autoSize: true, layout: { background: { type: ColorType.Solid, color: "transparent" }, textColor: isDark ? theme.colors.dark[1] : theme.colors.gray[7], panes: { separatorColor: isDark ? theme.colors.dark[4] : theme.colors.gray[3] } }, grid: { vertLines: { color: isDark ? theme.colors.dark[6] : theme.colors.gray[2] }, horzLines: { color: isDark ? theme.colors.dark[6] : theme.colors.gray[2] } }, crosshair: { mode: CrosshairMode.Normal }, timeScale: { timeVisible: interval !== "1d", secondsVisible: false } }); chartRef.current = chart;
    const candles = chart.addSeries(CandlestickSeries, { upColor: theme.colors.teal[6], downColor: theme.colors.red[6], borderVisible: false, wickUpColor: theme.colors.teal[5], wickDownColor: theme.colors.red[5] });
    candles.setData(bars.map((bar) => ({ time: chartTime(bar.timestamp), open: bar.open, high: bar.high, low: bar.low, close: bar.close })));
    if (layers.volume) { const volume = chart.addSeries(HistogramSeries, { priceFormat: { type: "volume" }, priceScaleId: "volume" }, 1); volume.setData(bars.flatMap((bar) => bar.volume === null ? [] : [{ time: chartTime(bar.timestamp), value: Number(bar.volume), color: bar.close >= bar.open ? `${theme.colors.teal[6]}80` : `${theme.colors.red[6]}80` }])); }
    if (layers.aggregateVwap) { const series = chart.addSeries(LineSeries, { color: theme.colors.blue[4], lineWidth: 2, title: "Aggregate VWAP", priceLineVisible: false, lastValueVisible: false }); series.setData(bars.flatMap((bar) => bar.vwap === null ? [] : [{ time: chartTime(bar.timestamp), value: bar.vwap }])); }
    const levels = [[layers.previousClose, data.referenceLevels.previousClose, theme.colors.gray[5], LineStyle.Dashed], [layers.sessionVwap, data.referenceLevels.sessionVwap, theme.colors.blue[6], LineStyle.Dotted], [layers.premarketHigh && extendedHours, data.referenceLevels.premarketHigh, theme.colors.yellow[6], LineStyle.Dashed], [layers.regularSessionHigh, data.referenceLevels.regularSessionHigh, theme.colors.violet[5], LineStyle.Dashed]] as const;
    for (const [enabled, price, color, lineStyle] of levels) if (enabled && price !== null) candles.createPriceLine({ price, color, lineStyle, axisLabelVisible: false, title: "" });
    createSeriesMarkers(candles, visibleMarkers.map((marker): SeriesMarker<Time> => ({ time: nearestChartTime(marker.timestamp, barTimes), ...markerAppearance(marker.type), text: markerText(marker.type) })));
    applyRange(chart); chart.subscribeCrosshairMove((param) => { if (typeof param.time !== "number") return setTooltip(null); const bar = barByTime.get(param.time); setTooltip(bar ? { bar, markers: markersByTime.get(param.time) ?? [] } : null); });
    return () => { chartRef.current = null; chart.remove(); };
  }, [applyRange, barByTime, barTimes, bars, data, extendedHours, interval, isDark, layers, markersByTime, theme.colors, visibleMarkers]);
  const updateLayer = (key: MomentumChartLayer, value: boolean) => setLayers((current) => ({ ...current, [key]: value }));
  const legend = [{ key: "catalystMarkers", label: "Catalyst", color: "blue" }, { key: "decisionMarkers", label: "Discovered / Ready / Blocked / Handoff", color: "violet" }, { key: "allPriceChecks", label: "All price checks", color: "gray" }, { key: "sessionVwap", label: "Session VWAP", color: "blue" }, { key: "aggregateVwap", label: "Aggregate VWAP", color: "cyan" }, { key: "previousClose", label: "Previous close", color: "gray" }, { key: "premarketHigh", label: "Premarket high", color: "yellow" }, { key: "regularSessionHigh", label: "Session high", color: "violet" }] as const;
  const height = expanded ? 640 : 430;
  return <Card withBorder radius="md" p="lg"><Stack gap="md"><Group justify="space-between" align="flex-start"><div><Title order={2}>{title}</Title><Text size="xs" c="dimmed">Adjusted Massive bars · New York market time · stored decisions remain authoritative</Text></div><Group gap="xs">{isFetching && !isLoading && <Loader size="xs" />}<MomentumChartControls interval={interval} onIntervalChange={onIntervalChange} layers={layers} onLayerChange={updateLayer} extendedHours={extendedHours} onExtendedHoursChange={setSessionChoice} range={range} onRangeChange={setRange} hasCandidate={candidate} expanded={expanded} onExpandedChange={() => setExpanded((value) => !value)} /></Group></Group>
    <Group gap={6} wrap="wrap">{legend.filter((item) => layers[item.key] && (item.key !== "premarketHigh" || extendedHours)).map((item) => <Badge key={item.key} size="sm" variant="dot" color={item.color}>{item.label}</Badge>)}</Group>
    {isLoading && <Group justify="center" h={height}><Loader /><Text c="dimmed">Loading market data…</Text></Group>}{!isLoading && error && <Alert color="red" title="Market chart unavailable">{error.message}</Alert>}{!isLoading && !error && data && !bars.length && <Alert color="blue" title="No market bars">No bars are available for the selected session.</Alert>}
    {!isLoading && !error && data && bars.length > 0 && <div style={{ position: "relative" }}><div ref={containerRef} style={{ height }} />{tooltip && <Card withBorder p="xs" radius="sm" style={{ position: "absolute", top: 8, left: 8, zIndex: 2, pointerEvents: "none", background: "var(--mantine-color-body)", maxWidth: 390 }}><Text size="xs" fw={700}>Market bar · {formatNewYork(tooltip.bar.timestamp)} ET</Text><Text size="xs">O {formatPrice(tooltip.bar.open)} · H {formatPrice(tooltip.bar.high)} · L {formatPrice(tooltip.bar.low)} · C {formatPrice(tooltip.bar.close)}</Text><Text size="xs">Volume {tooltip.bar.volume === null ? "-" : Number(tooltip.bar.volume).toLocaleString()} · Provider Aggregate VWAP {formatPrice(tooltip.bar.vwap)}</Text>{tooltip.markers.map((marker) => <Stack key={marker.id} gap={1} mt={4}><Group gap={4}><Badge size="xs" variant="light">{marker.label}</Badge><Text size="xs" fw={600}>{marker.type === "PRICE_CHECK" ? marker.metadata?.decision ? "Stored scanner decision" : "Stored scanner observation" : "Stored lifecycle event"}</Text></Group><Text size="xs" c="dimmed">{formatNewYork(marker.timestamp)} ET · stored price {formatPrice(marker.price)}</Text>{marker.type === "PRICE_CHECK" && <Text size="xs">Decision {String(marker.metadata?.decision ?? "-")} · confirmed {String(marker.metadata?.confirmed ?? "-")} · price {String(marker.metadata?.priceActionScore ?? "-")} · volume {String(marker.metadata?.volumeScore ?? "-")} · total {String(marker.metadata?.totalConfirmationScore ?? "-")}</Text>}{marker.metadata?.sessionVwap !== undefined && <Text size="xs">Stored VWAP {formatPrice(Number(marker.metadata.sessionVwap))} · above VWAP {marker.metadata.aboveVwap == null ? "-" : marker.metadata.aboveVwap ? "Yes" : "No"}</Text>}{Boolean(marker.metadata?.blockedReason || marker.metadata?.reason) && <Text size="xs" c="red">{String(marker.metadata?.blockedReason ?? marker.metadata?.reason)}</Text>}</Stack>)}</Card>}</div>}
    {data && <Stack gap={2}><Group gap="sm" wrap="wrap">{layers.sessionVwap && <Text size="xs">Session VWAP {formatPrice(data.referenceLevels.sessionVwap)}</Text>}{layers.aggregateVwap && <Text size="xs">Aggregate VWAP {formatPrice(bars.at(-1)?.vwap)}</Text>}{layers.previousClose && <Text size="xs">Previous close {formatPrice(data.referenceLevels.previousClose)}</Text>}{layers.premarketHigh && extendedHours && <Text size="xs">Premarket high {formatPrice(data.referenceLevels.premarketHigh)}</Text>}{layers.regularSessionHigh && <Text size="xs">Regular-session high {formatPrice(data.referenceLevels.regularSessionHigh)}</Text>}</Group><Text size="xs" c="dimmed">{data.source.cached ? "Cached" : "Fresh"} provider data fetched {formatNewYork(data.source.fetchedAt)} ET</Text></Stack>}</Stack></Card>;
}
