// @vitest-environment happy-dom
import { MantineProvider } from '@mantine/core';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { SecuritiesImportExportPage } from './SecuritiesImportExportPage';

const mocks = vi.hoisted(() => ({ requestImport: vi.fn(), requestFreeze: vi.fn(), requestBreadthStatus: vi.fn(), downloadSecurityCsv: vi.fn(), breadthStatusQueryKey: ['breadthRevisionStatus'] }));
vi.mock('./universeApi', () => ({ ...mocks }));
const emptyStatus = { asOfDate: '2026-10-01', state: 'EMPTY', current: { memberCount: 0, constituentHash: null }, latestRevision: null, difference: { addedCount: 0, removedCount: 0 } };
const requiredStatus = { asOfDate: '2026-10-01', state: 'REVISION_REQUIRED', current: { memberCount: 1, constituentHash: 'new-hash' }, latestRevision: null, difference: { addedCount: 1, removedCount: 0 } };
const currentStatus = { ...requiredStatus, state: 'CURRENT', latestRevision: { id: 13, effectiveDate: '2026-10-01', memberCount: 1, constituentHash: 'new-hash' }, difference: { addedCount: 0, removedCount: 0 } };
beforeEach(() => { mocks.requestBreadthStatus.mockResolvedValue(emptyStatus); });
afterEach(() => { cleanup(); vi.clearAllMocks(); });

function renderPage() {
  return render(<MantineProvider><QueryClientProvider client={new QueryClient()}><MemoryRouter><SecuritiesImportExportPage /></MemoryRouter></QueryClientProvider></MantineProvider>);
}
describe('Securities import/export review', () => {
  it('requires preview before apply and blocks conflicts', async () => {
    mocks.requestImport.mockResolvedValue({ applied: false, timing: { kind: 'immediate' }, effectiveDate: '2026-10-01', inputSecurityCount: 1, suppliedColumns: ['symbol'], omittedColumns: ['name'], newSecurities: [], metadataChanges: [], membershipAdditions: [], membershipRemovals: [], membershipDeletions: [], membershipReopens: [], unchangedMembershipValues: [], conflicts: ['Review conflict'], missingUniverses: [], currentBroadMemberCount: 0, resultingBroadMemberCount: 0, universeCounts: [] });
    renderPage();
    expect(screen.queryByLabelText('Mode')).toBeNull();
    expect(screen.queryByText(/Snapshot reconciliation|Partial update/i)).toBeNull();
    expect(screen.getByText(/Omitted rows, omitted columns, and blank cells leave existing values unchanged/)).toBeTruthy();
    const apply = screen.getByRole('button', { name: 'Apply reviewed import' }) as HTMLButtonElement;
    expect(apply.disabled).toBe(true);
    const user = userEvent.setup();
    const file = new File(['symbol\nAAPL\n'], 'review.csv', { type: 'text/csv' });
    Object.defineProperty(file, 'text', { value: async () => 'symbol\nAAPL\n' });
    await user.upload(document.querySelector('input[type="file"]') as HTMLInputElement, file);
    expect(screen.queryByLabelText('Membership effective date')).toBeNull();
    await user.click(screen.getByRole('button', { name: 'Preview' }));
    await waitFor(() => expect(mocks.requestImport).toHaveBeenCalledOnce());
    expect(mocks.requestImport.mock.calls[0][1]).toBe(false);
    expect(mocks.requestImport.mock.calls[0][0].timing).toEqual({ kind: 'immediate' });
    expect(mocks.requestImport.mock.calls[0][0]).not.toHaveProperty('mode');
    expect(apply.disabled).toBe(true);
    expect(screen.getByRole('heading', { name: 'Import Preview' })).toBeTruthy();
    expect(screen.getByText('CONFLICTS')).toBeTruthy();
    expect(screen.queryByRole('heading', { name: 'Import Result' })).toBeNull();
    expect(screen.getByText('Review conflict')).toBeTruthy();
  });
  it('does not offer a Breadth freeze when source membership changes leave the broad set unchanged', async () => {
    mocks.requestBreadthStatus.mockResolvedValue(currentStatus);
    const plan = { applied: false, timing: { kind: 'immediate' }, effectiveDate: '2026-10-01', inputSecurityCount: 1, suppliedColumns: ['symbol', 'SP600'], omittedColumns: ['name', 'sector'], newSecurities: [], metadataChanges: [], membershipAdditions: [{ symbol: 'AAPL', code: 'SP600' }], membershipRemovals: [], membershipDeletions: [], membershipReopens: [], unchangedMembershipValues: [], conflicts: [], missingUniverses: ['SP600'], currentBroadMemberCount: 1, resultingBroadMemberCount: 1, universeCounts: [{ code: 'SP500', before: 1, after: 1 }, { code: 'NASDAQ100', before: 0, after: 0 }, { code: 'DJIA', before: 0, after: 0 }, { code: 'RUSSELL2000', before: 0, after: 0 }, { code: 'SP400', before: 0, after: 0 }, { code: 'SP600', before: 0, after: 1 }], breadthMembershipChanged: false };
    mocks.requestImport.mockResolvedValueOnce(plan).mockResolvedValueOnce({ ...plan, applied: true });
    renderPage();
    const user = userEvent.setup();
    const file = new File(['symbol,SP600\nAAPL,1\n'], 'review.csv', { type: 'text/csv' });
    Object.defineProperty(file, 'text', { value: async () => 'symbol,SP600\nAAPL,1\n' });
    await user.upload(document.querySelector('input[type="file"]') as HTMLInputElement, file);
    expect(screen.queryByLabelText('Membership effective date')).toBeNull();
    await user.click(screen.getByRole('button', { name: 'Preview' }));
    await waitFor(() => expect(screen.getByRole('button', { name: 'Apply reviewed import' }).hasAttribute('disabled')).toBe(false));
    expect(screen.getByRole('heading', { name: 'Import Preview' })).toBeTruthy();
    expect(screen.getByText('READY TO APPLY')).toBeTruthy();
    expect(within(screen.getByTestId('import-plan-summary')).getByText('review.csv')).toBeTruthy();
    expect(screen.getByRole('heading', { name: 'Import Scope' })).toBeTruthy();
    expect(screen.getByText('Supplied fields')).toBeTruthy();
    expect(screen.getByText('Omitted fields · unchanged')).toBeTruthy();
    expect(screen.getByText('Source universes to initialize')).toBeTruthy();
    expect(within(screen.getByTestId('summary-securities')).getByText('1')).toBeTruthy();
    expect(within(screen.getByTestId('summary-broad')).getByText('1 → 1')).toBeTruthy();
    expect(within(screen.getByTestId('summary-additions')).getByText('1')).toBeTruthy();
    expect(within(screen.getByTestId('summary-removals')).getByText('0')).toBeTruthy();
    expect(screen.getByRole('heading', { name: 'Universe Membership Impact' })).toBeTruthy();
    expect(within(screen.getByTestId('universe-impact-SP600')).getByText('Changed')).toBeTruthy();
    expect(within(screen.getByTestId('universe-impact-SP500')).queryByText('Changed')).toBeNull();
    await user.click(screen.getByRole('button', { name: 'Apply reviewed import' }));
    await waitFor(() => expect(screen.getByText('Import applied.')).toBeTruthy());
    expect(screen.getByRole('heading', { name: 'Import Result' })).toBeTruthy();
    expect(screen.getByText('Applied import')).toBeTruthy();
    expect(screen.getByText('APPLIED')).toBeTruthy();
    expect(screen.queryByRole('heading', { name: 'Import Preview' })).toBeNull();
    expect(screen.queryByRole('button', { name: 'Preview Revision' })).toBeNull();
    expect(screen.getByText('CURRENT')).toBeTruthy();
    expect(mocks.requestFreeze).not.toHaveBeenCalled();
  });
  it('reveals future scheduling only in Advanced options and never offers early Breadth freeze', async () => {
    const plan = { applied: false, timing: { kind: 'scheduled', membershipEffectiveDate: '2099-01-01' }, effectiveDate: '2099-01-01', inputSecurityCount: 1, suppliedColumns: ['symbol', 'SP500'], omittedColumns: [], newSecurities: [], metadataChanges: [], membershipAdditions: [{ symbol: 'AAPL', code: 'SP500' }], membershipRemovals: [], membershipDeletions: [], membershipReopens: [], unchangedMembershipValues: [], conflicts: [], missingUniverses: [], currentBroadMemberCount: 0, resultingBroadMemberCount: 1, universeCounts: [{ code: 'SP500', before: 0, after: 1 }], breadthMembershipChanged: true };
    mocks.requestImport.mockResolvedValueOnce(plan).mockResolvedValueOnce({ ...plan, applied: true });
    renderPage();
    const user = userEvent.setup();
    expect(screen.queryByLabelText('Membership effective date')).toBeNull();
    await user.click(screen.getByText('Advanced options'));
    await user.click(screen.getByLabelText('Schedule universe membership changes for a future date'));
    expect(screen.getByText(/Security records and nonblank metadata are applied immediately/)).toBeTruthy();
    const date = screen.getByLabelText('Membership effective date');
    const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/New_York', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
    fireEvent.change(date, { target: { value: today } });
    expect(screen.getByText(/Choose a date after today's America\/New_York date/)).toBeTruthy();
    const file = new File(['symbol,SP500\nAAPL,1\n'], 'future.csv', { type: 'text/csv' });
    Object.defineProperty(file, 'text', { value: async () => 'symbol,SP500\nAAPL,1\n' });
    await user.upload(document.querySelector('input[type="file"]') as HTMLInputElement, file);
    expect((screen.getByRole('button', { name: 'Preview' }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(date, { target: { value: '2099-01-01' } });
    await user.click(screen.getByRole('button', { name: 'Preview' }));
    await waitFor(() => expect(screen.getByText('SCHEDULED')).toBeTruthy());
    expect(mocks.requestImport.mock.calls[0][0].timing).toEqual({ kind: 'scheduled', membershipEffectiveDate: '2099-01-01' });
    expect(screen.getByText(/Security\/catalog changes:/)).toBeTruthy();
    expect(screen.getByText(/Universe memberships:/)).toBeTruthy();
    await user.click(screen.getByRole('button', { name: 'Apply reviewed import' }));
    await waitFor(() => expect(screen.getByRole('heading', { name: 'Import Result' })).toBeTruthy());
    expect(screen.getByText('Applied import · memberships scheduled')).toBeTruthy();
    expect(screen.getByText(/Membership changes are scheduled and are not currently active/)).toBeTruthy();
    expect(screen.queryByRole('button', { name: 'Preview Revision' })).toBeNull();
    expect(mocks.requestBreadthStatus).toHaveBeenCalledOnce();
  });
  it('refetches persistent Breadth status after an immediate import', async () => {
    mocks.requestBreadthStatus.mockReset().mockResolvedValueOnce(emptyStatus).mockResolvedValue(requiredStatus);
    const plan = { applied: false, timing: { kind: 'immediate' }, effectiveDate: '2026-10-01', inputSecurityCount: 1, suppliedColumns: ['symbol', 'SP500'], omittedColumns: [], newSecurities: [], metadataChanges: [], membershipAdditions: [{ symbol: 'AAPL', code: 'SP500' }], membershipRemovals: [], membershipDeletions: [], membershipReopens: [], unchangedMembershipValues: [], conflicts: [], missingUniverses: [], currentBroadMemberCount: 0, resultingBroadMemberCount: 1, universeCounts: [{ code: 'SP500', before: 0, after: 1 }], breadthMembershipChanged: true };
    mocks.requestImport.mockResolvedValueOnce(plan).mockResolvedValueOnce({ ...plan, applied: true });
    renderPage();
    const user = userEvent.setup();
    const file = new File(['symbol,SP500\nAAPL,1\n'], 'today.csv', { type: 'text/csv' });
    Object.defineProperty(file, 'text', { value: async () => 'symbol,SP500\nAAPL,1\n' });
    await user.upload(document.querySelector('input[type="file"]') as HTMLInputElement, file);
    await user.click(screen.getByRole('button', { name: 'Preview' }));
    await waitFor(() => expect(screen.getByRole('button', { name: 'Apply reviewed import' }).hasAttribute('disabled')).toBe(false));
    await user.click(screen.getByRole('button', { name: 'Apply reviewed import' }));
    await waitFor(() => expect(screen.getByRole('button', { name: 'Preview Revision' })).toBeTruthy());
    expect(mocks.requestBreadthStatus.mock.calls.length).toBeGreaterThan(1);
    expect(screen.getByText('Immediate · takes effect today')).toBeTruthy();
  });
  it('shows revision-required status on direct load and gates freeze behind preview', async () => {
    mocks.requestBreadthStatus.mockResolvedValue(requiredStatus);
    mocks.requestFreeze.mockResolvedValue({ applied: false, alreadyExists: false, revisionId: null, effectiveDate: '2026-10-01', memberCount: 1, constituentHash: 'new-hash' });
    renderPage();
    await waitFor(() => expect(screen.getByText('REVISION REQUIRED')).toBeTruthy());
    expect(screen.getByText('1 member')).toBeTruthy();
    expect(screen.queryByRole('button', { name: 'Freeze Revision' })).toBeNull();
    await userEvent.setup().click(screen.getByRole('button', { name: 'Preview Revision' }));
    await waitFor(() => expect(screen.getByRole('button', { name: 'Freeze Revision' })).toBeTruthy());
    expect(mocks.requestFreeze).toHaveBeenCalledWith('2026-10-01', false, '2026-10-01');
  });
  it('shows persisted revision details on direct load', async () => {
    mocks.requestBreadthStatus.mockResolvedValue({ ...requiredStatus, state: 'CURRENT', latestRevision: { id: 13, effectiveDate: '2026-09-28', memberCount: 1, constituentHash: 'frozen-hash' }, difference: { addedCount: 0, removedCount: 0 } });
    renderPage();
    await waitFor(() => expect(screen.getByText('CURRENT')).toBeTruthy());
    expect(screen.getByText('#13')).toBeTruthy();
    expect(screen.getByText('2026-09-28')).toBeTruthy();
    expect(screen.getByText('frozen-hash')).toBeTruthy();
    expect(screen.queryByRole('button', { name: 'Preview Revision' })).toBeNull();
  });
  it('refetches persisted CURRENT status after explicit freeze', async () => {
    mocks.requestBreadthStatus.mockReset().mockResolvedValueOnce(requiredStatus).mockResolvedValue(currentStatus);
    mocks.requestFreeze.mockResolvedValueOnce({ applied: false, alreadyExists: false, revisionId: null, effectiveDate: '2026-10-01', memberCount: 1, constituentHash: 'new-hash' })
      .mockResolvedValueOnce({ applied: true, alreadyExists: false, revisionId: 13, effectiveDate: '2026-10-01', memberCount: 1, constituentHash: 'new-hash' });
    renderPage();
    await waitFor(() => expect(screen.getByRole('button', { name: 'Preview Revision' })).toBeTruthy());
    await userEvent.setup().click(screen.getByRole('button', { name: 'Preview Revision' }));
    await waitFor(() => expect(screen.getByRole('button', { name: 'Freeze Revision' })).toBeTruthy());
    await userEvent.setup().click(screen.getByRole('button', { name: 'Freeze Revision' }));
    await waitFor(() => expect(screen.getByText('CURRENT')).toBeTruthy());
    expect(screen.getByText('#13')).toBeTruthy();
    expect(mocks.requestFreeze).toHaveBeenCalledWith('2026-10-01', true, '2026-10-01', 'new-hash');
  });
});
