import { Fragment, useEffect, useMemo, useState } from "react";
import { Button, Card, Group, Modal, Pagination, Select, SimpleGrid, Stack, Table, Text, TextInput, Title } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconRefresh } from "@tabler/icons-react";
import { useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { CompactRecordList, DataState, DataTable, MobileRecordCard, RecordDetailsGrid, ResponsiveActions, ResponsiveDataView, ResponsiveDetails, ResponsiveFilterToolbar, StatusBadge, type SummaryField } from "../../components/data-display";
import { getAdminToken } from "../../lib/api";
import { useCreateSecurity, useSecurities, useSecuritiesSummary } from "./hooks";
import { ASSET_TYPES, type AssetType, type SecuritiesQueryParams, type Security, type SecuritySortBy, type SortDirection } from "./types";
import classes from "./SecuritiesPage.module.css";

const PAGE_SIZE_OPTIONS = [25, 50, 100, 250];
const param = (params: URLSearchParams, key: string) => params.get(key) ?? "";
const positive = (params: URLSearchParams, key: string, fallback: number) => { const value = Number(params.get(key)); return Number.isFinite(value) && value > 0 ? value : fallback; };
const assetParam = (params: URLSearchParams): AssetType | "" => ASSET_TYPES.includes(param(params, "assetType") as AssetType) ? param(params, "assetType") as AssetType : "";

function SecurityDetails({ security }: { security: Security }) {
  return <Stack gap="md"><section className={classes.detailCard}><Title order={3} size="h5">Security</Title><RecordDetailsGrid sections={[{ items: [{ label: "Symbol", value: security.symbol }, { label: "Name", value: security.name }, { label: "Asset type", value: security.assetType }, { label: "Sector", value: security.sector || "Not classified" }, { label: "Industry", value: security.industry || "Not classified" }, { label: "Catalog state", value: security.enabled ? "Enabled" : "Disabled" }] }]} /></section><section className={classes.detailCard}><Title order={3} size="h5">Usage</Title><RecordDetailsGrid sections={[{ items: [{ label: "Subscriptions", value: `${security.subscriptionCount} configured subscription${security.subscriptionCount === 1 ? "" : "s"}` }, { label: "Management", value: "Open the security workspace to inspect dependent strategies, exit profiles, and activity." }] }]} /></section><details className={classes.technical}><summary>Routing &amp; identifiers</summary><RecordDetailsGrid sections={[{ items: [{ label: "Security ID", value: security.id, technical: true }, { label: "Routing symbol", value: security.symbol, technical: true }, { label: "Raw asset type", value: security.assetType, technical: true }] }]} /></details></Stack>;
}

export function SecuritiesPage() {
  const [searchParams, setSearchParams] = useSearchParams(); const navigate = useNavigate(); const location = useLocation(); const token = getAdminToken();
  const [page, setPage] = useState(() => positive(searchParams, "page", 1)); const [pageSize, setPageSize] = useState(() => positive(searchParams, "pageSize", 50)); const [searchInput, setSearchInput] = useState(() => param(searchParams, "search")); const [search, setSearch] = useState(() => param(searchParams, "search"));
  const [assetType, setAssetType] = useState<AssetType | "">(() => assetParam(searchParams)); const [sector, setSector] = useState(() => param(searchParams, "sector")); const [industry, setIndustry] = useState(() => param(searchParams, "industry")); const [enabled, setEnabled] = useState(() => ["enabled", "disabled"].includes(param(searchParams, "status")) ? param(searchParams, "status") : "all"); const [usage, setUsage] = useState(() => ["configured", "unconfigured"].includes(param(searchParams, "subscriptionStatus")) ? param(searchParams, "subscriptionStatus") : "all");
  const [sortBy, setSortBy] = useState<SecuritySortBy>((param(searchParams, "sortBy") as SecuritySortBy) || "symbol"); const [sortDirection, setSortDirection] = useState<SortDirection>(param(searchParams, "sortDirection") === "desc" ? "desc" : "asc"); const [expandedId, setExpandedId] = useState<number | null>(null); const [detailSecurity, setDetailSecurity] = useState<Security | null>(null); const [detailOpener, setDetailOpener] = useState<HTMLElement | null>(null); const [createOpened, setCreateOpened] = useState(false); const [form, setForm] = useState({ symbol: "", name: "", assetType: "STOCK" as AssetType, sector: "", industry: "" });
  const query = useMemo<SecuritiesQueryParams>(() => ({ page, pageSize, search: search || undefined, assetType: assetType || undefined, sector: sector || undefined, industry: industry || undefined, enabled: enabled === "all" ? undefined : enabled === "enabled", subscriptionStatus: usage as SecuritiesQueryParams["subscriptionStatus"], sortBy, sortDirection }), [page, pageSize, search, assetType, sector, industry, enabled, usage, sortBy, sortDirection]);
  const securitiesQuery = useSecurities(query, token); const summaryQuery = useSecuritiesSummary(token); const createMutation = useCreateSecurity(token); const securities = securitiesQuery.data?.data ?? []; const pagination = securitiesQuery.data?.pagination; const filters = securitiesQuery.data?.filters;
  useEffect(() => { const next = new URLSearchParams(); if (page !== 1) next.set("page", String(page)); if (pageSize !== 50) next.set("pageSize", String(pageSize)); if (search) next.set("search", search); if (assetType) next.set("assetType", assetType); if (sector) next.set("sector", sector); if (industry) next.set("industry", industry); if (enabled !== "all") next.set("status", enabled); if (usage !== "all") next.set("subscriptionStatus", usage); if (sortBy !== "symbol") next.set("sortBy", sortBy); if (sortDirection !== "asc") next.set("sortDirection", sortDirection); setSearchParams(next, { replace: true }); }, [page, pageSize, search, assetType, sector, industry, enabled, usage, sortBy, sortDirection, setSearchParams]);
  const clear = () => { setPage(1); setSearchInput(""); setSearch(""); setAssetType(""); setSector(""); setIndustry(""); setEnabled("all"); setUsage("all"); };
  const applySearch = () => { setPage(1); setSearch(searchInput.trim()); };
  const activeFilters = [{ key: "asset", value: assetType, label: `Type: ${assetType}`, remove: () => setAssetType("") }, { key: "sector", value: sector, label: `Sector: ${sector}`, remove: () => setSector("") }, { key: "industry", value: industry, label: `Industry: ${industry}`, remove: () => setIndustry("") }, { key: "status", value: enabled !== "all" ? enabled : "", label: enabled === "enabled" ? "Enabled" : "Disabled", remove: () => setEnabled("all") }, { key: "usage", value: usage !== "all" ? usage : "", label: usage === "configured" ? "Configured" : "Unconfigured", remove: () => setUsage("all") }].filter((item) => item.value).map((item) => ({ key: item.key, label: item.label, onRemove: item.remove }));
  const manage = (security: Security) => navigate(`/securities/${encodeURIComponent(security.symbol)}`, { state: { returnTo: `${location.pathname}${location.search}` } });
  const identity = (security: Security) => <div className={classes.identity}><Text component="h3" fw={800} ff="monospace">{security.symbol}</Text><Text size="xs" c="dimmed">{security.name}</Text></div>;
  const fields = (security: Security): SummaryField[] => [{ label: "Asset type", value: security.assetType }, { label: "Classification", value: [security.sector, security.industry].filter(Boolean).join(" · ") || "Not classified" }, { label: "Usage", value: `${security.subscriptionCount} subscription${security.subscriptionCount === 1 ? "" : "s"}` }];
  const actions = (security: Security) => <ResponsiveActions compact primary={{ label: "Manage", onClick: () => manage(security) }} />;
  function sort(column: SecuritySortBy) { setPage(1); if (sortBy === column) setSortDirection((current) => current === "asc" ? "desc" : "asc"); else { setSortBy(column); setSortDirection("asc"); } }
  const sortLabel = (column: SecuritySortBy, label: string) => `${label}${sortBy === column ? sortDirection === "asc" ? " ↑" : " ↓" : ""}`;
  const wide = (items: readonly Security[]) => <DataTable caption="Security catalog" captionHidden density="compact"><Table.Thead><Table.Tr><Table.Th><button className={classes.sort} onClick={() => sort("symbol")}>{sortLabel("symbol", "Security")}</button></Table.Th><Table.Th><button className={classes.sort} onClick={() => sort("assetType")}>{sortLabel("assetType", "Asset type")}</button></Table.Th><Table.Th>Classification</Table.Th><Table.Th><button className={classes.sort} onClick={() => sort("enabled")}>{sortLabel("enabled", "Status")}</button></Table.Th><Table.Th><button className={classes.sort} onClick={() => sort("subscriptionCount")}>{sortLabel("subscriptionCount", "Usage")}</button></Table.Th><Table.Th>Actions</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{items.map((security) => <Fragment key={security.id}><Table.Tr><Table.Td>{identity(security)}</Table.Td><Table.Td>{security.assetType}</Table.Td><Table.Td>{[security.sector, security.industry].filter(Boolean).join(" · ") || "Not classified"}</Table.Td><Table.Td><StatusBadge status={security.enabled ? "enabled" : "disabled"} label={security.enabled ? "Enabled" : "Disabled"} tone={security.enabled ? "positive" : "neutral"} /></Table.Td><Table.Td>{security.subscriptionCount} subscription{security.subscriptionCount === 1 ? "" : "s"}</Table.Td><Table.Td><Group gap="xs" wrap="nowrap"><Button variant="default" size="compact-sm" onClick={() => setExpandedId(expandedId === security.id ? null : security.id)} aria-expanded={expandedId === security.id}>Details</Button>{actions(security)}</Group></Table.Td></Table.Tr>{expandedId === security.id && <Table.Tr><Table.Td colSpan={6}><SecurityDetails security={security} /></Table.Td></Table.Tr>}</Fragment>)}</Table.Tbody></DataTable>;
  async function create() { try { await createMutation.mutateAsync({ symbol: form.symbol.trim().toUpperCase(), name: form.name.trim(), assetType: form.assetType, sector: form.sector.trim() || undefined, industry: form.industry.trim() || undefined }); notifications.show({ message: `Security created: ${form.symbol.trim().toUpperCase()}`, color: "teal" }); setCreateOpened(false); setForm({ symbol: "", name: "", assetType: "STOCK", sector: "", industry: "" }); } catch (error) { notifications.show({ message: error instanceof Error ? error.message : "Failed to create security.", color: "red" }); } }
  return <main className={classes.page}><Stack gap="lg"><Group justify="space-between" align="flex-end" className={classes.header}><div><Title order={2} size="h3">Securities</Title><Text size="sm" c="dimmed">Search the symbol registry and inspect subscription dependencies.</Text></div><Button onClick={() => setCreateOpened(true)}>Create Security</Button></Group>
    <SimpleGrid cols={{ base: 2, sm: 3, lg: 6 }}>{[["TOTAL", summaryQuery.data?.summary.total], ["ENABLED", summaryQuery.data?.summary.enabled], ["DISABLED", summaryQuery.data?.summary.disabled], ["CONFIGURED", summaryQuery.data?.summary.configured], ["UNCONFIGURED", summaryQuery.data?.summary.unconfigured], ["ENABLED SUBSCRIPTIONS", summaryQuery.data?.summary.enabledSubscriptions]].map(([label, value]) => <Card key={label} withBorder><Text size="xs" c="dimmed">{label}</Text><Text size="xl" fw={700}>{value ?? "—"}</Text></Card>)}</SimpleGrid>
    <Card withBorder><Stack gap="md"><Group justify="space-between" align="flex-end"><ResponsiveFilterToolbar primary={<Group align="flex-end" wrap="nowrap"><TextInput label="Search securities" placeholder="Symbol or name" value={searchInput} onChange={(event) => setSearchInput(event.currentTarget.value)} onKeyDown={(event) => event.key === "Enter" && applySearch()} /><Button onClick={applySearch}>Search</Button></Group>} secondary={<><Select label="Asset type" value={assetType || null} clearable placeholder="All types" data={ASSET_TYPES} onChange={(value) => { setPage(1); setAssetType((value as AssetType) ?? ""); }} /><Select label="Sector" value={sector || null} clearable placeholder="All sectors" data={filters?.sectors ?? []} onChange={(value) => { setPage(1); setSector(value ?? ""); setIndustry(""); }} /><Select label="Industry" value={industry || null} clearable placeholder="All industries" data={filters?.industries ?? []} onChange={(value) => { setPage(1); setIndustry(value ?? ""); }} /><Select label="Status" value={enabled} data={[{ value: "all", label: "All statuses" }, { value: "enabled", label: "Enabled" }, { value: "disabled", label: "Disabled" }]} onChange={(value) => { setPage(1); setEnabled(value ?? "all"); }} /><Select label="Usage" value={usage} data={[{ value: "all", label: "All securities" }, { value: "configured", label: "Configured" }, { value: "unconfigured", label: "Unconfigured" }]} onChange={(value) => { setPage(1); setUsage(value ?? "all"); }} /><Select label="Per page" value={String(pageSize)} data={PAGE_SIZE_OPTIONS.map(String)} onChange={(value) => { setPage(1); setPageSize(Number(value ?? 50)); }} /></>} activeFilters={activeFilters} onClearAll={clear} /><Button variant="default" leftSection={<IconRefresh size={16} />} onClick={() => { void securitiesQuery.refetch(); void summaryQuery.refetch(); }}>Refresh</Button></Group>
      {securitiesQuery.isError ? <DataState state="error" title="Unable to load securities" message={securitiesQuery.error instanceof Error ? securitiesQuery.error.message : "Failed to load securities."} onRetry={() => securitiesQuery.refetch()} /> : securitiesQuery.isLoading ? <DataState state="loading" message="Loading securities…" /> : securities.length === 0 ? <DataState state="empty" title={activeFilters.length || search ? "No matching securities" : "No securities"} message={activeFilters.length || search ? "Clear or change the filters to see other securities." : "Create a security to begin."} action={activeFilters.length || search ? { label: "Clear filters", onClick: clear } : undefined} /> : <ResponsiveDataView records={securities} getRecordId={(security) => security.id} wide={wide} compact={(items) => <CompactRecordList records={items} getRecordId={(security) => security.id} renderIdentity={identity} renderFields={fields} renderDetails={(security) => <SecurityDetails security={security} />} renderActions={actions} expandedId={expandedId} onExpandedChange={(id) => setExpandedId(id as number | null)} />} narrow={(items) => <MobileRecordCard records={items} getRecordId={(security) => security.id} renderIdentity={identity} renderStatus={(security) => <StatusBadge status={security.enabled ? "enabled" : "disabled"} label={security.enabled ? "Enabled" : "Disabled"} tone={security.enabled ? "positive" : "neutral"} size="compact" />} renderFields={fields} onDetails={(security, opener) => { setDetailSecurity(security); setDetailOpener(opener); }} renderActions={actions} />} aria-label="Security catalog" />}
      {(pagination?.totalPages ?? 1) > 1 && <Group justify="space-between" className={classes.pagination}><Text size="sm" c="dimmed">Showing {(page - 1) * pageSize + 1}–{Math.min(page * pageSize, pagination?.total ?? 0)} of {pagination?.total ?? 0}</Text><Pagination value={page} total={pagination?.totalPages ?? 1} onChange={setPage} disabled={securitiesQuery.isFetching} /></Group>}
    </Stack></Card>
    <ResponsiveDetails opened={Boolean(detailSecurity)} title={detailSecurity ? `${detailSecurity.symbol} details` : "Security details"} onClose={() => setDetailSecurity(null)} returnFocusTo={detailOpener}>{detailSecurity && <SecurityDetails security={detailSecurity} />}</ResponsiveDetails>
    <Modal opened={createOpened} onClose={() => !createMutation.isPending && setCreateOpened(false)} title="Create Security" size="lg" closeOnEscape={!createMutation.isPending} closeOnClickOutside={!createMutation.isPending} styles={{ content: { maxHeight: "calc(100dvh - 2rem)" }, body: { overflowY: "auto" } }}><Stack><SimpleGrid cols={{ base: 1, sm: 2 }}><TextInput required label="Symbol" value={form.symbol} onChange={(event) => setForm((current) => ({ ...current, symbol: event.currentTarget.value }))} /><TextInput required label="Name" value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.currentTarget.value }))} /><Select required label="Asset type" data={ASSET_TYPES} value={form.assetType} onChange={(value) => setForm((current) => ({ ...current, assetType: (value as AssetType) ?? current.assetType }))} /><TextInput label="Sector" value={form.sector} onChange={(event) => setForm((current) => ({ ...current, sector: event.currentTarget.value }))} /><TextInput label="Industry" value={form.industry} onChange={(event) => setForm((current) => ({ ...current, industry: event.currentTarget.value }))} /></SimpleGrid><Group justify="flex-end" className={classes.modalActions}><Button variant="default" disabled={createMutation.isPending} onClick={() => setCreateOpened(false)}>Cancel</Button><Button loading={createMutation.isPending} disabled={createMutation.isPending || !form.symbol.trim() || !form.name.trim()} onClick={create}>Create Security</Button></Group></Stack></Modal>
  </Stack></main>;
}
