import { Accordion, Badge, Card, Group, SimpleGrid, Stack, Table, Text, Title } from "@mantine/core";
import type { ReactNode } from "react";
import { decimal, label, percent, percentagePoints } from "./presentation";
import type { Assessment, DimensionKey } from "./types";
import classes from "./MarketIntelligencePage.module.css";
type Json = Record<string, unknown>;
const object = (value: unknown): Json => value && typeof value === "object" && !Array.isArray(value) ? value as Json : {};
const list = (value: unknown): Json[] => Array.isArray(value) ? value.map(object) : [];
function Datum({ label: name, value }: { label: string; value: ReactNode }) { return <div className={classes.evidenceDatum}><Text size="xs" c="dimmed" fw={700}>{name}</Text><Text size="sm" fw={600} mt={4}>{value}</Text></div>; }
function InstrumentTrend({ symbol, value }: { symbol: string; value: Json }) { return <Card withBorder><Group justify="space-between"><Text fw={700}>{symbol}</Text><Badge>{String(value.state ?? "Unavailable")}</Badge></Group><Text size="sm" mt="xs">{String(value.reason ?? "No explanation recorded.")}</Text><Table mt="sm" fz="sm"><Table.Thead><Table.Tr><Table.Th>Measurement</Table.Th><Table.Th>Value</Table.Th><Table.Th>Signal</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{list(value.measurements).map(row => <Table.Tr key={String(row.key)}><Table.Td>{String(row.label ?? row.key)}</Table.Td><Table.Td>{percentagePoints(row.value)}</Table.Td><Table.Td>{label(String(row.classification ?? "Unavailable"))}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Card>; }
export function AssessmentEvidence({ dimension, assessment }: { dimension: DimensionKey | "breadthV2"; assessment: Assessment }) {
  const evidence = object(assessment.evidenceJson); const market = object(evidence.market); const transition = object(evidence.transition);
  return <Stack gap="md"><div><Title order={3}>Readable evidence</Title><Text size="sm" c="dimmed">Only persisted fields are formatted below; no values are recalculated.</Text></div>
    {typeof market.explanation === "string" && <Card withBorder><Text fw={700}>Published explanation</Text><Text size="sm" mt="xs">{market.explanation}</Text></Card>}
    {dimension === "trend" && <SimpleGrid cols={{ base: 1, lg: 2 }}><InstrumentTrend symbol="SPY" value={object(evidence.spy)} /><InstrumentTrend symbol="RSP" value={object(evidence.rsp)} /></SimpleGrid>}
    {dimension === "volatility" && <SimpleGrid cols={{ base: 1, sm: 2 }}>{(["spy", "rsp"] as const).map(symbol => { const row = object(evidence[symbol]); return <Card withBorder key={symbol}><Group justify="space-between"><Text fw={700}>{symbol.toUpperCase()}</Text><Badge>{String(row.rawState ?? "Unavailable")}</Badge></Group><div className={classes.evidenceGrid}><Datum label="10-session realized volatility" value={`${decimal(object(row.RV10).value)}% annualized`} /><Datum label="20-session realized volatility" value={`${decimal(object(row.RV20).value)}% annualized`} /><Datum label="ATR14 / close" value={percentagePoints(object(row.ATR14Pct).value)} /></div></Card>; })}</SimpleGrid>}
    {dimension === "breadth" && <div className={classes.evidenceGrid}>{Object.entries(object(evidence.measurements)).map(([key, value]) => { const row = object(value); return <Datum key={key} label={label(key)} value={`${percent(row.advanceShare)} advancing · ${percent(row.netBreadth)} net breadth`} />; })}</div>}
    {dimension === "participation" && <><div className={classes.evidenceGrid}><Datum label="Panel median relative volume" value={`${decimal(evidence.panelMedianRvol ?? evidence.panelMedian, 2)}×`} /><Datum label="Baseline sessions" value={String(evidence.baselineSessions ?? (Array.isArray(evidence.expectedBaselineDates) ? evidence.expectedBaselineDates.length : 20))} /></div>{Array.isArray(evidence.instruments) && <Table.ScrollContainer minWidth={520}><Table><Table.Thead><Table.Tr><Table.Th>Symbol</Table.Th><Table.Th>Relative volume</Table.Th><Table.Th>20-session median volume</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{list(evidence.instruments).map(row => <Table.Tr key={String(row.symbol)}><Table.Td>{String(row.symbol)}</Table.Td><Table.Td>{decimal(row.rvol20, 2)}×</Table.Td><Table.Td>{Number(row.medianVolume20).toLocaleString("en-US", { maximumFractionDigits: 0 })}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}</>}
    {dimension === "intradayStress" && <SimpleGrid cols={{ base: 1, sm: 2 }}>{(["spy", "rsp"] as const).map(symbol => { const row = object(evidence[symbol]); return <Card withBorder key={symbol}><Group justify="space-between"><Text fw={700}>{symbol.toUpperCase()}</Text><Badge>{String(row.instrumentRawState ?? "Unavailable")}</Badge></Group><div className={classes.evidenceGrid}><Datum label="15-minute shock" value={percent(row.shockPct, 2)} /><Datum label="60-minute realized movement" value={percent(row.realizedMovement60Pct, 2)} /><Datum label="Session drawdown" value={percent(row.sessionDrawdownPct, 2)} /><Datum label="Prior ATR14 / close" value={percent(row.priorAtr14Pct, 2)} /></div></Card>; })}</SimpleGrid>}
    {dimension === "breadthV2" && <div className={classes.evidenceGrid}>{Object.entries(object(evidence.horizons)).map(([key, value]) => { const row = object(value); return <Datum key={key} label={key.replace("DAY_", "") + "-session horizon"} value={`${label(String(row.state ?? "Unavailable"))} · ${percent(row.advanceShare)} advancing · ${percent(row.netBreadth)} net`} />; })}</div>}
    {typeof transition.reason === "string" && <Card withBorder><Text fw={700}>State transition</Text><Text size="sm" mt="xs">{transition.reason}</Text></Card>}
    <Accordion variant="separated"><Accordion.Item value="raw"><Accordion.Control>Raw diagnostic evidence</Accordion.Control><Accordion.Panel><pre className={classes.raw}>{JSON.stringify(assessment.evidenceJson, null, 2)}</pre></Accordion.Panel></Accordion.Item></Accordion>
  </Stack>;
}
