import { Accordion, Alert, Badge, Button, Card, Group, SimpleGrid, Stack, Table, Text, Title } from "@mantine/core";
import { useState } from "react";
import { DataState, ResponsiveDetails, StatusBadge } from "../../components/data-display";
import { useAssessmentDetail, useCurrentMarketRegimeComposition, useMarketRegimeCompositionDetail, useMarketRegimeCompositionHistory } from "./hooks";
import { formatDateTime, label } from "./presentation";
import { AssessmentEvidence } from "./AssessmentEvidence";
import type { DimensionKey } from "./types";

const dimensionKeys: Record<string, DimensionKey> = { TREND: "trend", VOLATILITY: "volatility", BREADTH: "breadth", PARTICIPATION: "participation", INTRADAY_STRESS: "intradayStress" };

export function ComposedMarketRegime() {
  const current = useCurrentMarketRegimeComposition();
  const history = useMarketRegimeCompositionHistory();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const detail = useMarketRegimeCompositionDetail(selectedId);
  const [selectedSource, setSelectedSource] = useState<{ dimension: DimensionKey; id: number } | null>(null);
  const sourceDetail = useAssessmentDetail(selectedSource?.dimension ?? "trend", selectedSource?.id ?? null);
  const rows = history.data?.pages.flat() ?? [];
  if (current.isLoading) return <Card withBorder><DataState state="loading" message="Loading composed Market Regime…" /></Card>;
  if (current.isError) return <Card withBorder><DataState state="error" title="Composed Market Regime unavailable" message={current.error.message} onRetry={() => void current.refetch()} /></Card>;
  const result = current.data!; const assessment = result.assessment;
  return <Card withBorder p="md">
    <Group justify="space-between" align="flex-start"><div><Group gap="xs"><Title order={2} size="h3">Composed Market Regime</Title><Badge color="blue">Observational only</Badge></Group><Text size="sm" c="dimmed">Immutable composition of the exact five authoritative V1 assessments. No score, recommendation, strategy policy, or trading authority.</Text></div><StatusBadge status={result.freshness} tone={result.freshness === "FRESH" ? "positive" : result.freshness === "EXPIRED" ? "warning" : "neutral"} /></Group>
    {!assessment ? <DataState state="empty" title="No composition published" message="The observational composer has not published an immutable source vector." /> : <Stack mt="md">
      <SimpleGrid cols={{ base: 1, sm: 2, lg: 4 }}><div><Text size="xs" c="dimmed">Publication</Text><StatusBadge status={assessment.publicationStatus} tone={assessment.publicationStatus === "SUCCEEDED" ? "positive" : "danger"} /></div><div><Text size="xs" c="dimmed">Evidence completeness</Text><StatusBadge status={assessment.evidenceHealth} tone={assessment.evidenceHealth === "COMPLETE" ? "positive" : "warning"} /></div><div><Text size="xs" c="dimmed">Observed</Text><Text fw={600}>{formatDateTime(assessment.observedAt)}</Text></div><div><Text size="xs" c="dimmed">Composition version</Text><Text fw={600}>{assessment.compositionVersion}</Text></div></SimpleGrid>
      {!result.wholeVectorUsable && <Alert color="yellow" title="Whole vector is not currently usable">Publication succeeded independently of evidence completeness and request-time freshness. Future policies must evaluate only their explicitly required dimensions.</Alert>}
      <Table.ScrollContainer minWidth={1060}><Table striped highlightOnHover><Table.Thead><Table.Tr><Table.Th>Dimension / source</Table.Th><Table.Th>State</Table.Th><Table.Th>Current health</Table.Th><Table.Th>Reason</Table.Th><Table.Th>Expected target</Table.Th><Table.Th>Selected target</Table.Th><Table.Th>Expires</Table.Th><Table.Th>Evidence</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{assessment.sources.map(source => <Table.Tr key={source.id}><Table.Td><Text fw={700}>{label(source.dimension)}</Text><Text size="xs" c="dimmed">{source.requiredAlgorithmVersion} · #{source.sourceAssessmentId ?? "missing"}{source.sourceAttempt ? ` attempt ${source.sourceAttempt}` : ""}</Text></Table.Td><Table.Td>{source.sourceEffectiveState ? label(source.sourceEffectiveState) : "—"}</Table.Td><Table.Td><StatusBadge status={source.currentHealth ?? source.health} tone={(source.currentHealth ?? source.health) === "AVAILABLE" ? "positive" : "warning"} size="compact" /></Table.Td><Table.Td>{source.currentReasonCode || source.reasonCode ? label(source.currentReasonCode ?? source.reasonCode!) : "—"}</Table.Td><Table.Td>{formatDateTime(source.expectedTargetAt)}</Table.Td><Table.Td>{formatDateTime(source.sourceTargetAt)}</Table.Td><Table.Td>{formatDateTime(source.sourceValidUntil)}</Table.Td><Table.Td>{source.sourceAssessmentId ? <Button size="compact-xs" variant="subtle" onClick={() => setSelectedSource({ dimension: dimensionKeys[source.dimension]!, id: source.sourceAssessmentId! })}>Inspect source</Button> : "—"}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>
      <Accordion variant="separated"><Accordion.Item value="history"><Accordion.Control>Immutable composition history ({rows.length} loaded)</Accordion.Control><Accordion.Panel>{history.isLoading ? <DataState state="loading" /> : history.isError ? <DataState state="error" message={history.error.message} /> : !rows.length ? <DataState state="empty" title="No history" /> : <Stack>{rows.map(row => <Group key={row.id} justify="space-between"><Text size="sm">#{row.id} · {formatDateTime(row.observedAt)} · {row.evidenceHealth}</Text><Button size="compact-xs" variant="default" onClick={() => setSelectedId(row.id)}>Inspect exact evidence</Button></Group>)}{history.hasNextPage && <Button variant="default" loading={history.isFetchingNextPage} onClick={() => void history.fetchNextPage()}>Load older compositions</Button>}</Stack>}</Accordion.Panel></Accordion.Item></Accordion>
    </Stack>}
    <ResponsiveDetails opened={selectedId !== null} onClose={() => setSelectedId(null)} title="Immutable Market Regime evidence">{detail.isLoading ? <DataState state="loading" /> : detail.isError ? <DataState state="error" message={detail.error.message} /> : detail.data && <Stack><Text fw={700}>Composition #{detail.data.id} · {detail.data.compositionVersion}</Text><Text size="sm">Fingerprint: {detail.data.sourceSetFingerprint}</Text><Text size="sm">Observed {formatDateTime(detail.data.observedAt)} · published {formatDateTime(detail.data.completedAt)}</Text><pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{JSON.stringify(detail.data.evidenceJson, null, 2)}</pre></Stack>}</ResponsiveDetails>
    <ResponsiveDetails opened={selectedSource !== null} onClose={() => setSelectedSource(null)} title="Exact source assessment evidence">{sourceDetail.isLoading ? <DataState state="loading" /> : sourceDetail.isError ? <DataState state="error" message={sourceDetail.error.message} /> : sourceDetail.data && selectedSource && <Stack><Text fw={700}>{sourceDetail.data.algorithmVersion} · assessment #{sourceDetail.data.id}</Text><Text size="sm">Target {formatDateTime(sourceDetail.data.targetAt)} · published {formatDateTime(sourceDetail.data.completedAt)}</Text><AssessmentEvidence dimension={selectedSource.dimension} assessment={sourceDetail.data} /></Stack>}</ResponsiveDetails>
  </Card>;
}
