import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import * as api from "./api";
import type { DimensionKey } from "./types";
const V1_DIMENSIONS: DimensionKey[] = ["trend", "volatility", "breadth", "participation", "intradayStress"];
export const useMarketIntelligenceSummary = (enabled = true) => useQuery({ queryKey: ["market-intelligence-summary"], queryFn: api.getSummary, enabled, refetchInterval: 60_000, staleTime: 30_000 });
export const useAssessmentHistory = (dimension: DimensionKey | "breadthV2", enabled = true) => useInfiniteQuery({ queryKey: ["market-intelligence-history", dimension], queryFn: ({ pageParam }) => api.getAssessments(dimension, pageParam), initialPageParam: undefined as number | undefined, getNextPageParam: page => page.length === 30 ? page.at(-1)?.id : undefined, enabled });
export const useAssessmentDetail = (dimension: DimensionKey | "breadthV2", id: number | null) => useQuery({ queryKey: ["market-intelligence-detail", dimension, id], queryFn: () => api.getAssessment(dimension, id!), enabled: id !== null });
export const useAssessmentTimeline = (enabled: boolean) => useQuery({ queryKey: ["market-intelligence-timeline", 20], queryFn: async () => Object.fromEntries(await Promise.all(V1_DIMENSIONS.map(async dimension => [dimension, await api.getAssessments(dimension, undefined, 20)] as const))) as Record<DimensionKey, import("./types").Assessment[]>, enabled, staleTime: 60_000 });
export const useCurrentMarketRegimeComposition = () => useQuery({ queryKey: ["market-regime-composition-current"], queryFn: api.getCurrentComposition, refetchInterval: 60_000, staleTime: 30_000 });
export const useMarketRegimeCompositionHistory = () => useInfiniteQuery({ queryKey: ["market-regime-composition-history"], queryFn: ({ pageParam }) => api.getCompositions(pageParam), initialPageParam: undefined as number | undefined, getNextPageParam: page => page.length === 20 ? page.at(-1)?.id : undefined });
export const useMarketRegimeCompositionDetail = (id: number | null) => useQuery({ queryKey: ["market-regime-composition-detail", id], queryFn: () => api.getComposition(id!), enabled: id !== null });
