import { Accordion, Alert, Anchor, Badge, Button, Card, Group, NativeSelect, SimpleGrid, Stack, Table, Text, Title } from "@mantine/core";
import { useState } from "react";
import { DataState, ResponsiveDetails, StatusBadge } from "../../components/data-display";
import { DimensionSummaryCard } from "./DimensionSummaryCard";
import { AssessmentTimeline } from "./AssessmentTimeline";
import { AssessmentEvidence } from "./AssessmentEvidence";
import { useAssessmentDetail, useAssessmentHistory, useMarketIntelligenceSummary } from "./hooks";
import { formatDateTime, label, percent } from "./presentation";
import type { DimensionKey } from "./types";
import classes from "./MarketIntelligencePage.module.css";
import { ComposedMarketRegime } from "./ComposedMarketRegime";
import { StrategyEligibility } from "./StrategyEligibility";
const names: Record<DimensionKey, string> = { trend: "Trend", volatility: "Volatility", breadth: "Breadth V1", participation: "Participation", intradayStress: "Intraday Stress" };
export function MarketIntelligencePage() {
  const summary = useMarketIntelligenceSummary(); const [dimension, setDimension] = useState<DimensionKey | "breadthV2">("trend"); const [selectedId, setSelectedId] = useState<number | null>(null);
  const history = useAssessmentHistory(dimension); const detail = useAssessmentDetail(dimension, selectedId);
  if (summary.isLoading) return <DataState state="loading" message="Loading market intelligence…" />;
  if (summary.isError && !summary.data) return <DataState state="error" title="Market intelligence unavailable" message={summary.error.message} onRetry={() => void summary.refetch()} />;
  const data = summary.data!; const v2 = data.breadthV2; const readiness = String(v2.assessmentReadiness.readiness ?? "UNKNOWN"); const historyRows = history.data?.pages.flat() ?? [];
  const assessmentBlocker = v2.assessmentReadiness.blocker && typeof v2.assessmentReadiness.blocker === "object" ? v2.assessmentReadiness.blocker as Record<string, unknown> : null; const observationReady = v2.observationReadiness.readiness === "READY"; const workerDisabled = v2.worker.enabled === false;
  return <Stack className={classes.page} gap="lg"><Group className={classes.header} justify="space-between" align="flex-start"><div><Title order={1}>Market Intelligence</Title><Text c="dimmed">Read-only production assessment evidence. These independently published dimensions are not a synchronized market snapshot and have no trading authority.</Text></div><Button variant="default" loading={summary.isFetching} onClick={() => void summary.refetch()}>Refresh</Button></Group>
    {summary.isError && <Alert color="red" title="Refresh failed">{summary.error.message} Values below are the last successful response evaluated {formatDateTime(data.evaluatedAt)} and are not presented as refreshed.</Alert>}
    <Text size="xs" c="dimmed">Summary evaluated {formatDateTime(data.evaluatedAt)}. Validity expiration uses each persisted valid-until timestamp; it does not prove currency for the latest expected market session.</Text>
    <SimpleGrid cols={{ base: 1, sm: 2, xl: 5 }}>{(Object.keys(names) as DimensionKey[]).map(key => <Anchor className={classes.summaryButton} key={key} component="button" type="button" underline="never" onClick={() => setDimension(key)}><DimensionSummaryCard dimension={key} title={names[key]} summary={data.dimensions[key]} /></Anchor>)}</SimpleGrid>
    <ComposedMarketRegime />
    <StrategyEligibility />
    <AssessmentTimeline />
    <Card withBorder p="md"><Group justify="space-between"><div><Group gap="xs"><Title order={2} size="h3">Breadth V2</Title><Badge color="grape">Shadow only</Badge></Group><Text size="sm" c="dimmed">Separate Tiingo multi-horizon evidence; not one of the five authoritative V1 dimensions.</Text></div><StatusBadge status={readiness} tone={readiness === "READY" || readiness === "ALREADY_PUBLISHED" ? "positive" : readiness === "BLOCKED" ? "warning" : "neutral"} /></Group>
      <SimpleGrid cols={{ base: 1, md: 3 }} mt="md"><div><Text size="xs" c="dimmed">Latest shadow state</Text><Text fw={700}>{v2.latestAttempt?.effectiveState ? label(v2.latestAttempt.effectiveState) : "Unavailable"}</Text></div><div><Text size="xs" c="dimmed">Assessment target</Text><Text fw={600}>{formatDateTime(v2.latestAttempt?.targetAt)}</Text></div><div><Text size="xs" c="dimmed">Latest measurement</Text><Text fw={600}>{v2.latestObservation?.sessionDate?.slice(0, 10) ?? "Unavailable"}</Text></div></SimpleGrid>{readiness === "BLOCKED" && <Alert mt="md" color="yellow" title={assessmentBlocker?.reasonCode ? label(String(assessmentBlocker.reasonCode)) : "Shadow assessment blocked"}><Text size="sm">{String(assessmentBlocker?.message ?? "The next shadow assessment prerequisite is unavailable.")}</Text><Text size="sm" mt="xs">Target session: {String(assessmentBlocker?.sessionDate ?? v2.assessmentReadiness.sessionDate ?? "Unavailable")}. {observationReady && workerDisabled ? "The measurement preview is ready, but the disabled shadow worker has not published the required immutable measurement set. This is expected while shadow publication remains disabled." : observationReady ? "Measurement evidence is ready; publication state requires operator review." : "Measurement evidence is not ready."}</Text></Alert>}<Button mt="md" variant="light" onClick={() => setDimension("breadthV2")}>Inspect shadow history</Button>{v2.latestObservation && <Accordion mt="md"><Accordion.Item value="horizons"><Accordion.Control>Latest 1/5/20-session horizon evidence</Accordion.Control><Accordion.Panel><SimpleGrid cols={{ base: 1, md: 3 }}>{v2.latestObservation.horizons.map(horizon => <Card withBorder key={horizon.id}><Group justify="space-between"><Text fw={700}>{horizon.horizonSessions}-session</Text><Badge variant="light">{percent(horizon.coverageRatio)} coverage</Badge></Group><Text size="sm" mt="sm">Advance share <b>{percent(horizon.advanceShare)}</b></Text><Text size="sm">Decline share <b>{percent(1 - Number(horizon.advanceShare))}</b></Text><Text size="sm">Net breadth <b>{percent(horizon.netBreadth)}</b></Text><Text size="xs" c="dimmed" mt="xs">{horizon.advancingCount.toLocaleString()} advancing · {horizon.decliningCount.toLocaleString()} declining · {horizon.unchangedCount.toLocaleString()} unchanged</Text><Text size="xs" c="dimmed">Anchor {horizon.anchorSessionDate.slice(0, 10)}</Text></Card>)}</SimpleGrid><Accordion mt="md" variant="separated"><Accordion.Item value="raw"><Accordion.Control>Raw measurement evidence</Accordion.Control><Accordion.Panel><pre className={classes.raw}>{JSON.stringify(v2.latestObservation.evidenceJson, null, 2)}</pre></Accordion.Panel></Accordion.Item></Accordion></Accordion.Panel></Accordion.Item></Accordion>}
    </Card>
    <Card withBorder p="md"><Group justify="space-between"><div><Title order={2} size="h3">Assessment history</Title><Text size="sm" c="dimmed">Every publication attempt remains visible; unsuccessful attempts are not replaced by older valid results.</Text></div><NativeSelect aria-label="History dimension" value={dimension} onChange={event => setDimension(event.currentTarget.value as DimensionKey | "breadthV2")} data={[...Object.entries(names).map(([value, label]) => ({ value, label })), { value: "breadthV2", label: "Breadth V2 shadow" }]} /></Group>
      {history.isLoading ? <DataState state="loading" /> : history.isError ? <DataState state="error" message={history.error.message} onRetry={() => void history.refetch()} /> : !historyRows.length ? <DataState state="empty" title="No assessment attempts" message="This publisher has not recorded an assessment attempt." /> : <><Table.ScrollContainer minWidth={780}><Table mt="md" striped highlightOnHover><Table.Thead><Table.Tr><Table.Th>Target</Table.Th><Table.Th>Status</Table.Th><Table.Th>Raw</Table.Th><Table.Th>Effective</Table.Th><Table.Th>Evidence through</Table.Th><Table.Th>Published</Table.Th><Table.Th /></Table.Tr></Table.Thead><Table.Tbody>{historyRows.map(row => <Table.Tr key={row.id}><Table.Td>{formatDateTime(row.targetAt)}</Table.Td><Table.Td><StatusBadge status={row.status} tone={row.status === "VALID" ? "positive" : row.status === "FAILED" ? "danger" : "warning"} size="compact" /></Table.Td><Table.Td>{row.rawState ? label(row.rawState) : "—"}</Table.Td><Table.Td>{row.effectiveState ? label(row.effectiveState) : "—"}</Table.Td><Table.Td>{formatDateTime(row.dataThroughAt)}</Table.Td><Table.Td>{formatDateTime(row.completedAt)}</Table.Td><Table.Td><Button size="compact-xs" variant="subtle" onClick={() => setSelectedId(row.id)}>Evidence</Button></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>{history.hasNextPage && <Button mt="md" variant="default" loading={history.isFetchingNextPage} onClick={() => void history.fetchNextPage()}>Load older attempts</Button>}</>}
    </Card>
    <ResponsiveDetails opened={selectedId !== null} onClose={() => setSelectedId(null)} title="Assessment evidence">{detail.isLoading ? <DataState state="loading" /> : detail.isError ? <DataState state="error" message={detail.error.message} /> : detail.data && <Stack><Group><StatusBadge status={detail.data.status} tone={detail.data.status === "VALID" ? "positive" : detail.data.status === "FAILED" ? "danger" : "warning"} /><Text>{detail.data.algorithmVersion} · attempt {detail.data.attempt}</Text></Group><SimpleGrid cols={{ base: 1, sm: 2 }}><Text size="sm">Target: {formatDateTime(detail.data.targetAt)}</Text><Text size="sm">Evidence through: {formatDateTime(detail.data.dataThroughAt)}</Text><Text size="sm">Published: {formatDateTime(detail.data.completedAt)}</Text><Text size="sm">Valid until: {formatDateTime(detail.data.validUntil)}</Text></SimpleGrid><AssessmentEvidence dimension={dimension} assessment={detail.data} /></Stack>}</ResponsiveDetails>
  </Stack>;
}
