// @vitest-environment happy-dom
import { MantineProvider } from "@mantine/core";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import type { ReactNode } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { DimensionSummaryCard } from "./DimensionSummaryCard";
import { AssessmentEvidence } from "./AssessmentEvidence";
import { AssessmentTimeline } from "./AssessmentTimeline";
import { ComposedMarketRegime } from "./ComposedMarketRegime";
import type { Assessment, DimensionKey, MarketRegimeComposition } from "./types";
const mocks = vi.hoisted(() => ({ timeline: vi.fn(), assessmentDetail: vi.fn(), compositionCurrent: vi.fn(), compositionHistory: vi.fn(), compositionDetail: vi.fn() }));
vi.mock("./hooks", async importOriginal => ({ ...await importOriginal<typeof import("./hooks")>(), useAssessmentTimeline: mocks.timeline, useAssessmentDetail: mocks.assessmentDetail, useCurrentMarketRegimeComposition: mocks.compositionCurrent, useMarketRegimeCompositionHistory: mocks.compositionHistory, useMarketRegimeCompositionDetail: mocks.compositionDetail }));
const row = (overrides: Partial<Assessment> = {}): Assessment => ({ id: 1, dimension: "TREND", algorithmVersion: "TREND_V1", evidenceSchemaVersion: 1, targetAt: "2026-10-07T20:00:00Z", sessionDate: "2026-10-07", attempt: 1, status: "VALID", reasonCode: null, rawState: "NEUTRAL", effectiveState: "NEUTRAL", dataThroughAt: "2026-10-07T20:00:00Z", validUntil: "2026-10-08T20:00:00Z", previousAssessmentId: null, startedAt: "2026-10-08T12:00:00Z", completedAt: "2026-10-08T12:00:01Z", createdAt: "2026-10-08T12:00:01Z", evidenceJson: {}, ...overrides });
const dimensions: DimensionKey[] = ["trend", "volatility", "breadth", "participation", "intradayStress"];
const composition = (): MarketRegimeComposition => ({ id: 44, compositionVersion: "MARKET_REGIME_COMPOSITION_V1", evidenceSchemaVersion: 1, targetAt: "2026-10-08T17:45:00Z", observedAt: "2026-10-08T18:00:00Z", dataThroughAt: "2026-10-07T20:00:00Z", validUntil: "2026-10-08T18:15:00Z", publicationStatus: "SUCCEEDED", evidenceHealth: "DEGRADED", publicationReasonCode: null, evidenceReasonCode: "SOURCE_VECTOR_DEGRADED", sourceSetFingerprint: "a".repeat(64), previousAssessmentId: 43, startedAt: "2026-10-08T18:00:00Z", completedAt: "2026-10-08T18:00:01Z", createdAt: "2026-10-08T18:00:01Z", evidenceJson: { exact: true }, sources: dimensions.map((key, index) => ({ id: index + 1, ordinal: index + 1, dimension: key === "intradayStress" ? "INTRADAY_STRESS" : key.toUpperCase(), requiredAlgorithmVersion: key === "intradayStress" ? "INTRADAY_STRESS_V1" : `${key.toUpperCase()}_V1`, expectedTargetAt: "2026-10-08T17:45:00Z", sourceAssessmentId: index + 10, sourceEvidenceSchemaVersion: 1, sourceAttempt: 1, sourceStatus: "VALID", sourceTargetAt: "2026-10-08T17:45:00Z", sourceCompletedAt: "2026-10-08T17:46:00Z", sourceDataThroughAt: "2026-10-08T17:45:00Z", sourceValidUntil: "2026-10-08T18:15:00Z", sourceRawState: "NORMAL", sourceEffectiveState: "NORMAL", health: index === 0 ? "EXPIRED" : "AVAILABLE", reasonCode: index === 0 ? "SOURCE_EXPIRED" : null, currentHealth: index === 0 ? "EXPIRED" : "AVAILABLE", currentReasonCode: index === 0 ? "SOURCE_EXPIRED_AT_READ" : null, evidenceJson: {} })) });
const wrap = (node: ReactNode, width = 1280) => { Object.defineProperty(window, "innerWidth", { value: width, configurable: true }); return render(<MantineProvider>{node}</MantineProvider>); };
describe("market intelligence polish", () => {
  afterEach(cleanup);
  beforeEach(() => { mocks.timeline.mockImplementation((enabled: boolean) => enabled ? { isLoading: false, isError: false, data: Object.fromEntries(dimensions.map(key => [key, [row({ id: dimensions.indexOf(key) + 1, dimension: key.toUpperCase(), algorithmVersion: `${key.toUpperCase()}_V1` }), row({ id: dimensions.indexOf(key) + 20, algorithmVersion: `${key.toUpperCase()}_V1`, status: key === "trend" ? "FAILED" : "UNAVAILABLE", effectiveState: null })]])) } : { isLoading: false, isError: false, data: undefined }); mocks.assessmentDetail.mockReturnValue({ isLoading: false, isError: false, data: row() }); mocks.compositionCurrent.mockReturnValue({ isLoading: false, isError: false, data: { evaluatedAt: "2026-10-08T18:16:00Z", freshness: "EXPIRED", wholeVectorUsable: false, assessment: composition() }, refetch: vi.fn() }); mocks.compositionHistory.mockReturnValue({ isLoading: false, isError: false, data: { pages: [[composition()]] }, hasNextPage: false }); mocks.compositionDetail.mockReturnValue({ isLoading: false, isError: false, data: composition() }); });
  it.each([390, 768, 1440])("keeps authoritative state and failure evidence readable at %s px", width => { wrap(<DimensionSummaryCard dimension="trend" title="Trend" summary={{ dimension: "TREND", algorithmVersion: "TREND_V1", latestAttempt: row({ status: "FAILED", reasonCode: "MISSING_MARKET_DATA", effectiveState: null, validUntil: null }), latestValid: row({ id: 9, effectiveState: "UP" }) }} />, width); expect(screen.getByText("Unavailable")).toBeTruthy(); expect(screen.getByText("Missing Market Data")).toBeTruthy(); expect(screen.getByText(/No current effective state/)).toBeTruthy(); expect(screen.queryByText(/^Up$/)).toBeNull(); });
  it("loads bounded independent timelines on demand and distinguishes failed from unavailable", () => { wrap(<AssessmentTimeline />); expect(mocks.timeline).toHaveBeenCalledWith(false); fireEvent.click(screen.getByRole("button", { name: "Load timeline" })); expect(mocks.timeline).toHaveBeenLastCalledWith(true); expect(screen.getByLabelText(/Trend .*FAILED/)).toBeTruthy(); expect(screen.getByLabelText(/Volatility .*UNAVAILABLE/)).toBeTruthy(); expect(screen.getByText("TREND_V1")).toBeTruthy(); });
  it("renders missing evidence safely and retains complete raw diagnostics", () => { wrap(<AssessmentEvidence dimension="intradayStress" assessment={row({ status: "UNAVAILABLE", evidenceJson: {} })} />); expect(screen.getAllByText("Unavailable").length).toBeGreaterThan(0); expect(screen.getByText("Raw diagnostic evidence")).toBeTruthy(); });
  it("separates publication, completeness and request-time freshness without inventing a recommendation", () => { wrap(<ComposedMarketRegime />); expect(screen.getByText("Composed Market Regime")).toBeTruthy(); expect(screen.getByText("Succeeded")).toBeTruthy(); expect(screen.getByText("Degraded")).toBeTruthy(); expect(screen.getAllByText("Expired").length).toBeGreaterThan(0); expect(screen.getByText(/Future policies must evaluate only/)).toBeTruthy(); expect(screen.queryByText(/bullish|bearish/i)).toBeNull(); });
});
