import { Accordion, Alert, Anchor, Badge, Button, Card, Group, NativeSelect, SimpleGrid, Stack, Table, Text, Title } from "@mantine/core";
import { useState } from "react";
import { DataState, ResponsiveDetails, StatusBadge } from "../../components/data-display";
import { DimensionSummaryCard } from "./DimensionSummaryCard";
import { useAssessmentDetail, useAssessmentHistory, useMarketIntelligenceSummary } from "./hooks";
import { formatDateTime, label } from "./presentation";
import type { DimensionKey } from "./types";
const names: Record<DimensionKey, string> = { trend: "Trend", volatility: "Volatility", breadth: "Breadth V1", participation: "Participation", intradayStress: "Intraday Stress" };
export function MarketIntelligencePage() {
  const summary = useMarketIntelligenceSummary(); const [dimension, setDimension] = useState<DimensionKey | "breadthV2">("trend"); const [selectedId, setSelectedId] = useState<number | null>(null);
  const history = useAssessmentHistory(dimension); const detail = useAssessmentDetail(dimension, selectedId);
  if (summary.isLoading) return <DataState state="loading" message="Loading market intelligence…" />;
  if (summary.isError && !summary.data) return <DataState state="error" title="Market intelligence unavailable" message={summary.error.message} onRetry={() => void summary.refetch()} />;
  const data = summary.data!; const v2 = data.breadthV2; const readiness = String(v2.assessmentReadiness.readiness ?? "UNKNOWN"); const historyRows = history.data?.pages.flat() ?? [];
  return <Stack gap="lg"><Group justify="space-between" align="flex-start"><div><Title order={1}>Market Intelligence</Title><Text c="dimmed">Read-only production assessment evidence. These independently published dimensions are not a synchronized market snapshot and have no trading authority.</Text></div><Button variant="default" loading={summary.isFetching} onClick={() => void summary.refetch()}>Refresh</Button></Group>
    {summary.isError && <Alert color="red" title="Refresh failed">{summary.error.message} Values below are the last successful response evaluated {formatDateTime(data.evaluatedAt)} and are not presented as refreshed.</Alert>}
    <Text size="xs" c="dimmed">Summary evaluated {formatDateTime(data.evaluatedAt)}. Validity expiration uses each persisted valid-until timestamp; it does not prove currency for the latest expected market session.</Text>
    <SimpleGrid cols={{ base: 1, sm: 2, xl: 5 }}>{(Object.keys(names) as DimensionKey[]).map(key => <Anchor key={key} component="button" type="button" underline="never" onClick={() => setDimension(key)}><DimensionSummaryCard title={names[key]} summary={data.dimensions[key]} /></Anchor>)}</SimpleGrid>
    <Card withBorder p="md"><Group justify="space-between"><div><Group gap="xs"><Title order={2} size="h3">Breadth V2</Title><Badge color="grape">Shadow only</Badge></Group><Text size="sm" c="dimmed">Separate Tiingo multi-horizon evidence; not one of the five authoritative V1 dimensions.</Text></div><StatusBadge status={readiness} tone={readiness === "READY" || readiness === "ALREADY_PUBLISHED" ? "positive" : readiness === "BLOCKED" ? "warning" : "neutral"} /></Group>
      <SimpleGrid cols={{ base: 1, md: 3 }} mt="md"><div><Text size="xs" c="dimmed">Latest shadow state</Text><Text fw={700}>{v2.latestAttempt?.effectiveState ? label(v2.latestAttempt.effectiveState) : "Unavailable"}</Text></div><div><Text size="xs" c="dimmed">Assessment target</Text><Text fw={600}>{formatDateTime(v2.latestAttempt?.targetAt)}</Text></div><div><Text size="xs" c="dimmed">Latest measurement</Text><Text fw={600}>{v2.latestObservation?.sessionDate?.slice(0, 10) ?? "Unavailable"}</Text></div></SimpleGrid><Button mt="md" variant="light" onClick={() => setDimension("breadthV2")}>Inspect shadow history</Button>{v2.latestObservation && <Accordion mt="md"><Accordion.Item value="horizons"><Accordion.Control>Latest 1/5/20-session horizon evidence</Accordion.Control><Accordion.Panel><Table.ScrollContainer minWidth={620}><Table><Table.Thead><Table.Tr><Table.Th>Horizon</Table.Th><Table.Th>Anchor</Table.Th><Table.Th>Coverage</Table.Th><Table.Th>Advance share</Table.Th><Table.Th>Net breadth</Table.Th><Table.Th>Advancing / declining / unchanged</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{v2.latestObservation.horizons.map(horizon => <Table.Tr key={horizon.id}><Table.Td>{horizon.horizonSessions} sessions</Table.Td><Table.Td>{horizon.anchorSessionDate.slice(0, 10)}</Table.Td><Table.Td>{horizon.coverageRatio}</Table.Td><Table.Td>{horizon.advanceShare}</Table.Td><Table.Td>{horizon.netBreadth}</Table.Td><Table.Td>{horizon.advancingCount} / {horizon.decliningCount} / {horizon.unchangedCount}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer><pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere", fontSize: 12 }}>{JSON.stringify(v2.latestObservation.evidenceJson, null, 2)}</pre></Accordion.Panel></Accordion.Item></Accordion>}
    </Card>
    <Card withBorder p="md"><Group justify="space-between"><div><Title order={2} size="h3">Assessment history</Title><Text size="sm" c="dimmed">Every publication attempt remains visible; unsuccessful attempts are not replaced by older valid results.</Text></div><NativeSelect aria-label="History dimension" value={dimension} onChange={event => setDimension(event.currentTarget.value as DimensionKey | "breadthV2")} data={[...Object.entries(names).map(([value, label]) => ({ value, label })), { value: "breadthV2", label: "Breadth V2 shadow" }]} /></Group>
      {history.isLoading ? <DataState state="loading" /> : history.isError ? <DataState state="error" message={history.error.message} onRetry={() => void history.refetch()} /> : !historyRows.length ? <DataState state="empty" title="No assessment attempts" message="This publisher has not recorded an assessment attempt." /> : <><Table.ScrollContainer minWidth={780}><Table mt="md" striped highlightOnHover><Table.Thead><Table.Tr><Table.Th>Target</Table.Th><Table.Th>Status</Table.Th><Table.Th>Raw</Table.Th><Table.Th>Effective</Table.Th><Table.Th>Evidence through</Table.Th><Table.Th>Published</Table.Th><Table.Th /></Table.Tr></Table.Thead><Table.Tbody>{historyRows.map(row => <Table.Tr key={row.id}><Table.Td>{formatDateTime(row.targetAt)}</Table.Td><Table.Td><StatusBadge status={row.status} tone={row.status === "VALID" ? "positive" : row.status === "FAILED" ? "danger" : "warning"} size="compact" /></Table.Td><Table.Td>{row.rawState ? label(row.rawState) : "—"}</Table.Td><Table.Td>{row.effectiveState ? label(row.effectiveState) : "—"}</Table.Td><Table.Td>{formatDateTime(row.dataThroughAt)}</Table.Td><Table.Td>{formatDateTime(row.completedAt)}</Table.Td><Table.Td><Button size="compact-xs" variant="subtle" onClick={() => setSelectedId(row.id)}>Evidence</Button></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>{history.hasNextPage && <Button mt="md" variant="default" loading={history.isFetchingNextPage} onClick={() => void history.fetchNextPage()}>Load older attempts</Button>}</>}
    </Card>
    <ResponsiveDetails opened={selectedId !== null} onClose={() => setSelectedId(null)} title="Assessment evidence">{detail.isLoading ? <DataState state="loading" /> : detail.isError ? <DataState state="error" message={detail.error.message} /> : detail.data && <Stack><Group><StatusBadge status={detail.data.status} tone={detail.data.status === "VALID" ? "positive" : detail.data.status === "FAILED" ? "danger" : "warning"} /><Text>{detail.data.algorithmVersion} · attempt {detail.data.attempt}</Text></Group><SimpleGrid cols={{ base: 1, sm: 2 }}><Text size="sm">Target: {formatDateTime(detail.data.targetAt)}</Text><Text size="sm">Evidence through: {formatDateTime(detail.data.dataThroughAt)}</Text><Text size="sm">Published: {formatDateTime(detail.data.completedAt)}</Text><Text size="sm">Valid until: {formatDateTime(detail.data.validUntil)}</Text></SimpleGrid><pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere", fontSize: 12 }}>{JSON.stringify(detail.data.evidenceJson, null, 2)}</pre></Stack>}</ResponsiveDetails>
  </Stack>;
}
