import { Alert, Badge, Button, Card, Group, Stack, Table, Text, Title } from "@mantine/core";
import { useState } from "react";
import { DataState, ResponsiveDetails, StatusBadge } from "../../components/data-display";
import { useCurrentStrategyEligibilitySummary, useStrategyEligibilityDetail, useStrategyEligibilityHistory } from "./hooks";
import { formatDateTime, label } from "./presentation";

export function StrategyEligibility() {
  const current = useCurrentStrategyEligibilitySummary(); const history = useStrategyEligibilityHistory(); const [selectedId, setSelectedId] = useState<number | null>(null); const detail = useStrategyEligibilityDetail(selectedId);
  const rows = history.data?.pages.flat() ?? [];
  return <Card withBorder p="md"><Stack><Group justify="space-between"><div><Group gap="xs"><Title order={2} size="h3">Strategy Eligibility</Title><Badge color="grape">Shadow only</Badge></Group><Text size="sm" c="dimmed">Recorded policy outcomes are evidence only. ALLOWED never grants permission to trade.</Text></div></Group>
    {current.data && <Group>{current.data.map((item, index) => <Badge key={item.assessment?.strategyId ?? `unrecorded-${index}`} color={item.freshness === "CURRENT" ? "teal" : "yellow"}>{item.assessment?.strategy.name ?? "Unrecorded"}: {item.assessment?.outcome ?? "NOT RECORDED"} · {label(item.freshness)}</Badge>)}</Group>}
    <Title order={3} size="h4">Decision history</Title>
    {history.isLoading ? <DataState state="loading" /> : history.isError ? <DataState state="error" message={history.error.message} onRetry={() => void history.refetch()} /> : !rows.length ? <DataState state="empty" title="No shadow decisions" message="The shadow evaluator has not recorded an active-policy decision." /> : <><Table.ScrollContainer minWidth={900}><Table striped highlightOnHover><Table.Thead><Table.Tr><Table.Th>Strategy</Table.Th><Table.Th>Catalog</Table.Th><Table.Th>Policy</Table.Th><Table.Th>Shadow outcome</Table.Th><Table.Th>Reason</Table.Th><Table.Th>Evaluated</Table.Th><Table.Th>Valid until</Table.Th><Table.Th /></Table.Tr></Table.Thead><Table.Tbody>{rows.map(row => <Table.Tr key={row.id}><Table.Td><Text fw={600}>{row.strategy.name}</Text><Text size="xs" ff="monospace">{row.strategy.key}</Text></Table.Td><Table.Td><Badge color={row.strategyEnabled ? "teal" : "gray"}>{row.strategyEnabled ? "Enabled" : "Disabled"}</Badge></Table.Td><Table.Td>{row.policyRevision ? `Revision ${row.policyRevision.revision}` : "None"}</Table.Td><Table.Td><StatusBadge status={row.outcome} tone={row.outcome === "ALLOWED" ? "positive" : row.outcome === "BLOCKED" ? "danger" : "warning"} /></Table.Td><Table.Td>{label(row.reasonCode)}</Table.Td><Table.Td>{formatDateTime(row.evaluatedAt)}</Table.Td><Table.Td>{formatDateTime(row.validUntil)}</Table.Td><Table.Td><Button size="compact-xs" variant="subtle" onClick={() => setSelectedId(row.id)}>Details</Button></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>{history.hasNextPage && <Button variant="default" loading={history.isFetchingNextPage} onClick={() => void history.fetchNextPage()}>Load older decisions</Button>}</>}
    <ResponsiveDetails opened={selectedId !== null} onClose={() => setSelectedId(null)} title="Strategy eligibility evidence">{detail.isLoading ? <DataState state="loading" /> : detail.isError ? <DataState state="error" message={detail.error.message} /> : detail.data && <Stack><Alert color="grape" title="SHADOW ONLY">This recorded outcome has no trading or execution authority.</Alert><Group><StatusBadge status={detail.data.outcome} tone={detail.data.outcome === "ALLOWED" ? "positive" : detail.data.outcome === "BLOCKED" ? "danger" : "warning"} /><Text>{label(detail.data.reasonCode)}</Text></Group><Text size="sm">Composition #{detail.data.marketRegimeAssessmentId ?? "unresolved"} · policy revision {detail.data.policyRevision?.revision ?? "none"}</Text><Table><Table.Thead><Table.Tr><Table.Th>Dimension</Table.Th><Table.Th>Rule</Table.Th><Table.Th>Outcome</Table.Th><Table.Th>Observed</Table.Th><Table.Th>Allowed</Table.Th><Table.Th>Health / source</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{detail.data.gates.map(gate => <Table.Tr key={gate.id}><Table.Td>{label(gate.dimension)}</Table.Td><Table.Td>{gate.requirement}</Table.Td><Table.Td><StatusBadge status={gate.outcome} /></Table.Td><Table.Td>{gate.observedState ? label(gate.observedState) : "—"}</Table.Td><Table.Td>{gate.allowedStatesJson.length ? gate.allowedStatesJson.map(label).join(", ") : "—"}</Table.Td><Table.Td>{label(gate.sourceHealth ?? "unavailable")} · assessment {gate.sourceAssessmentId ?? "none"}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Stack>}</ResponsiveDetails>
  </Stack></Card>;
}
