// @vitest-environment happy-dom
import { MantineProvider } from "@mantine/core";
import { cleanup, render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { DashboardOperationalAttentionBanner, DashboardOperationalAttentionSection } from "./DashboardOperationalAttention";
import type { AttentionSummary, OperationalAttention } from "./types";
import type { DashboardAttentionState } from "./useDashboardOperationalAttention";

function episode(overrides: Partial<OperationalAttention> = {}): OperationalAttention {
  return { id: 11, tradingAccountId: 2, code: "DEMO", source: "DEMO", status: "OPEN", severity: "WARNING", title: "Demo operational attention", message: "Review condition.", detailsJson: {}, occurrenceCount: 1, firstObservedAt: "2026-08-28T10:00:00Z", lastObservedAt: "2026-08-28T11:00:00Z", revision: 1, resolutionPolicy: "MANUAL_ALLOWED", acknowledgedAt: null, resolvedAt: null, resolutionReason: null, trackedPositionId: null, orderIntentId: null, brokerOrderId: null, tradingAccount: { id: 2, displayName: "Bobby Paper", environment: "PAPER" }, links: { account: "/trading-accounts/2", reconciliation: "/trading-accounts/2/reconciliation", position: null, order: null, systemEvents: "/system/events?account=2" }, allowedActions: { acknowledge: true, manualResolve: true }, ...overrides };
}
function summary(items: OperationalAttention[]): AttentionSummary { const severities = { INFO: 0, WARNING: 0, ERROR: 0, CRITICAL: 0 }; items.forEach((item) => { severities[item.severity] += 1; }); const rank = ["CRITICAL", "ERROR", "WARNING", "INFO"] as const; return { totalUnresolved: items.length, openCount: items.filter((item) => item.status === "OPEN").length, acknowledgedCount: items.filter((item) => item.status === "ACKNOWLEDGED").length, bySeverity: severities, highestSeverity: rank.find((value) => severities[value]) ?? null, criticalLiveAccounts: [], preview: items, evidenceAt: "2026-08-28T11:00:00Z" }; }
function state(items: OperationalAttention[], overrides: Record<string, unknown> = {}) { return { account: "2", visible: true, query: { data: summary(items), isLoading: false, isError: false, refetch: vi.fn(), ...overrides }, acknowledge: { isPending: false, mutate: vi.fn() } } as unknown as DashboardAttentionState; }
function renderAttention(value: DashboardAttentionState) { return render(<MantineProvider><MemoryRouter><DashboardOperationalAttentionBanner state={value}/><div data-testid="primary-metrics">Primary metrics</div><DashboardOperationalAttentionSection state={value}/></MemoryRouter></MantineProvider>); }
afterEach(cleanup);

describe("Dashboard Operational Attention hierarchy", () => {
  it("hides the healthy top banner and shows a compact history row below primary content", () => { renderAttention(state([])); expect(screen.queryByRole("alert")).toBeNull(); expect(screen.getByText("· No unresolved conditions")).toBeTruthy(); expect(screen.getByRole("link", { name: "View history" }).getAttribute("href")).toBe("/operational-attention?account=2&status=all"); const metrics = screen.getByTestId("primary-metrics"); expect(metrics.compareDocumentPosition(screen.getByText("· No unresolved conditions")) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy(); });
  it("shows one warning with account, title and exact deep link while retaining the lower preview", () => { renderAttention(state([episode()])); expect(screen.getByRole("alert").textContent).toContain("1 operational issue requires attention · WARNING"); expect(screen.getByRole("alert").textContent).toContain("Bobby Paper · PAPER: Demo operational attention"); expect(screen.getByRole("alert").querySelector('a')?.getAttribute("href")).toBe("/operational-attention?account=2&attention=11"); expect(screen.getByText(/1 occurrences/)).toBeTruthy(); expect(screen.getByRole("alert").textContent).not.toMatch(/Acknowledge|Resolve/); });
  it("keeps acknowledged attention visible and truthfully unresolved", () => { renderAttention(state([episode({ status: "ACKNOWLEDGED", allowedActions: { acknowledge: false, manualResolve: true } })])); expect(screen.getByRole("alert").textContent).toContain("ACKNOWLEDGED · UNRESOLVED"); expect(screen.getByRole("alert").textContent).toContain("1 operational issue"); });
  it("reflects an escalated acknowledged episode as one updated error", () => { renderAttention(state([episode({ severity: "ERROR", occurrenceCount: 2 })])); expect(screen.getByRole("alert").textContent).toContain("1 operational issue requires attention · ERROR"); expect(screen.getByText(/2 occurrences/)).toBeTruthy(); });
  it("aggregates multiple episodes, highest severity and affected accounts", () => { const live = episode({ id: 12, tradingAccountId: 7, severity: "CRITICAL", title: "Live worker stale", tradingAccount: { id: 7, displayName: "Bobby Live", environment: "LIVE" } }); renderAttention(state([live, episode({ severity: "ERROR" })], { data: summary([live, episode({ severity: "ERROR" })]) })); expect(screen.getByRole("alert").textContent).toContain("2 operational issues require attention · Highest severity CRITICAL"); expect(screen.getByRole("alert").textContent).toContain("2 trading accounts"); expect(screen.getByRole("alert").querySelector('a')?.getAttribute("href")).toBe("/operational-attention?account=2"); });
  it("keeps critical Live attention visible and named while Paper scope is selected", () => { const live = episode({ id: 12, tradingAccountId: 7, severity: "CRITICAL", tradingAccount: { id: 7, displayName: "Bobby Live", environment: "LIVE" } }); renderAttention(state([live])); expect(screen.getByRole("alert").textContent).toContain("Bobby Live · LIVE"); expect(screen.getByRole("alert").querySelector('a')?.getAttribute("href")).toBe("/operational-attention?account=7&attention=12"); });
  it("shows unavailable state, retry and no healthy claim on failure", () => { renderAttention(state([], { data: undefined, isError: true })); expect(screen.getByRole("alert").textContent).toContain("Operational attention unavailable"); expect(screen.getByRole("button", { name: "Retry" })).toBeTruthy(); expect(screen.queryByText("· No unresolved conditions")).toBeNull(); });
  it("renders nothing for roles without attention access", () => { const value = { ...state([episode()]), visible: false } as DashboardAttentionState; renderAttention(value); expect(screen.queryByRole("alert")).toBeNull(); expect(screen.queryByText("Operational Attention")).toBeNull(); });
});
