import { Alert, Anchor, Badge, Button, Card, Group, Skeleton, Stack, Text } from "@mantine/core";
import { Link } from "react-router-dom";
import { getAdminToken } from "../../lib/api";
import { useAuth } from "../auth/useAuth";
import { useAcknowledgeAttention, useAttentionSummary } from "./hooks";
import type { AttentionSeverity } from "./types";
const colors: Record<AttentionSeverity, string> = { CRITICAL: "red", ERROR: "orange", WARNING: "yellow", INFO: "blue" };
export function DashboardOperationalAttention({ account }: { account: string }) {
  const { access } = useAuth(); const visible = access?.permissions.includes("operationalAttention.read") === true; const token = getAdminToken(); const query = useAttentionSummary(token, account, visible); const acknowledge = useAcknowledgeAttention(token);
  if (!visible) return null;
  return <Card withBorder style={query.data?.highestSeverity === "CRITICAL" ? { borderColor: "var(--mantine-color-red-6)" } : undefined}><Group justify="space-between"><div><Text fw={800}>Operational Attention</Text><Text size="xs" c="dimmed">Unresolved current conditions; acknowledged items remain counted.</Text></div><Anchor component={Link} to={`/operational-attention?account=${account}`}>Review all</Anchor></Group>{query.isLoading ? <Skeleton height={80} mt="md" /> : query.isError ? <Alert mt="md" color="orange" title="Operational attention unavailable">Current attention state is unknown. The request failed.</Alert> : query.data?.totalUnresolved === 0 ? <Text mt="md">No unresolved operational attention.</Text> : <Stack mt="md"><Group>{(["CRITICAL", "ERROR", "WARNING"] as const).map((severity) => query.data!.bySeverity[severity] ? <Badge key={severity} color={colors[severity]}>{severity} {query.data!.bySeverity[severity]}</Badge> : null)}</Group>{query.data?.preview.map((item) => <Card withBorder key={item.id}><Group justify="space-between" align="flex-start"><div><Group gap="xs"><Badge color={colors[item.severity]}>{item.severity}</Badge><Badge variant="outline">{item.status}</Badge></Group><Text fw={700}>{item.title}</Text><Text size="sm">{item.tradingAccount.displayName} · {item.tradingAccount.environment}</Text><Text size="xs" c="dimmed">Observed {new Date(item.lastObservedAt).toLocaleString()} · {item.occurrenceCount} occurrences</Text></div><Stack gap="xs"><Button component={Link} to={`/operational-attention?account=${account}&attention=${item.id}`} variant="light" size="xs">Review</Button>{item.allowedActions.acknowledge && <Button variant="default" size="xs" loading={acknowledge.isPending} onClick={() => acknowledge.mutate({ id: item.id, revision: item.revision })}>Acknowledge</Button>}</Stack></Group></Card>)}</Stack>}</Card>;
}
