import { Group, Select, Stack, Table, Text, TextInput, Title } from "@mantine/core";
import { IconCopy, IconTrash } from "@tabler/icons-react";
import { useState } from "react";
import {
  CompactRecordList, DataState, DataTable, MobileRecordCard, RecordDetailsGrid,
  ResponsiveActions, ResponsiveDataView, ResponsiveDetails, ResponsiveFilterToolbar, StatusBadge,
  type SummaryField, type StatusTone,
} from "../../components/data-display";
import classes from "./ResponsiveDataPrimitivesPreview.module.css";

type Fixture = { id: string; symbol: string; account: string; side: string; qty: number; entry: number; current: number; pnl: number; status: string; tone: StatusTone; subscription: string; reason?: string; trailing: string };
const records: Fixture[] = [
  { id: "position-spy-101", symbol: "SPY", account: "Bobby Paper — Alpaca Paper Trading Primary Account", side: "Long", qty: 6, entry: 632.18, current: 637.42, pnl: 31.44, status: "OPEN", tone: "positive", subscription: "momentum-breakout-us-equities-primary-paper-account-with-long-routing-key", reason: "The entry remains open while the broker trailing stop protects gains after the configured profit target unlocked.", trailing: "TRAILING_STOP_ACTIVE" },
  { id: "position-tsla-102", symbol: "TSLA", account: "Bobby Paper", side: "Long", qty: 2, entry: 321.12, current: 317.5, pnl: -7.24, status: "ENTRY_BLOCKED", tone: "danger", subscription: "momentum-high-volatility", reason: "Entry blocked because account-level buying power, symbol exposure, and the configured daily loss boundary cannot safely accept another position.", trailing: "Waiting for unlock" },
  { id: "position-nvda-103", symbol: "NVDA", account: "Growth Account Without Credentials", side: "Long", qty: 4, entry: 178.6, current: 180.1, pnl: 6, status: "NEEDS_CREDENTIALS", tone: "warning", subscription: "ai-semiconductor-momentum", trailing: "TRADING_DISABLED" },
];

const fields = (record: Fixture): SummaryField[] => [{ label: "Account", value: record.account }, { label: "Position", value: `${record.side}, quantity ${record.qty}` }, { label: "P/L", value: <span className={record.pnl >= 0 ? classes.moneyPositive : classes.moneyNegative}>{record.pnl >= 0 ? "+" : ""}${record.pnl.toFixed(2)}</span> }];
const identity = (record: Fixture) => <Stack gap={2}><Text fw={800}>{record.symbol}</Text><StatusBadge status={record.status} tone={record.tone} size="compact" /></Stack>;
const details = (record: Fixture) => <RecordDetailsGrid sections={[{ title: "Position", items: [{ label: "Account", value: record.account }, { label: "Side / quantity", value: `${record.side}, ${record.qty}` }, { label: "Average entry", value: `$${record.entry.toFixed(2)}` }, { label: "Current price", value: `$${record.current.toFixed(2)}` }, { label: "Trailing state", value: record.trailing }] }, { title: "Routing and diagnostics", items: [{ label: "Subscription key", value: record.subscription, technical: true }, { label: "Decision reason", value: record.reason }, { label: "Broker order ID", value: null, technical: true }] }]}/>;

export function ResponsiveDataPrimitivesPreview() {
  const [expandedId, setExpandedId] = useState<string | number | null>(records[0].id);
  const [drawerRecord, setDrawerRecord] = useState<Fixture | null>(null);
  const [drawerOpener, setDrawerOpener] = useState<HTMLElement | null>(null);
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<string | null>("Open");
  const active = [query ? { key: "query", label: `Search: ${query}`, onRemove: () => setQuery("") } : null, status ? { key: "status", label: `Status: ${status}`, onRemove: () => setStatus(null) } : null].filter((item): item is NonNullable<typeof item> => Boolean(item));
  const clear = () => { setQuery(""); setStatus(null); };
  const renderWide = (items: readonly Fixture[]) => <DataTable caption="Representative open positions" density="compact"><Table.Thead><Table.Tr><Table.Th>Symbol</Table.Th><Table.Th>Account</Table.Th><Table.Th>Position</Table.Th><Table.Th>Entry</Table.Th><Table.Th>Current</Table.Th><Table.Th>P/L</Table.Th><Table.Th>Status</Table.Th><Table.Th>Actions</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{items.map((record) => <Table.Tr key={record.id}><Table.Td fw={700}>{record.symbol}</Table.Td><Table.Td>{record.account}</Table.Td><Table.Td>{record.side}, {record.qty}</Table.Td><Table.Td>${record.entry.toFixed(2)}</Table.Td><Table.Td>${record.current.toFixed(2)}</Table.Td><Table.Td>{fields(record)[2].value}</Table.Td><Table.Td><StatusBadge status={record.status} tone={record.tone} size="compact" /></Table.Td><Table.Td><ResponsiveActions compact primary={{ label: "Details", onClick: () => setDrawerRecord(record) }} secondary={[{ label: "Copy ID", icon: <IconCopy size={15}/>, onClick: () => undefined }, { label: "Close position", color: "red", icon: <IconTrash size={15}/>, onClick: () => undefined }]}/></Table.Td></Table.Tr>)}</Table.Tbody></DataTable>;
  const renderCompact = (items: readonly Fixture[]) => <CompactRecordList records={items} getRecordId={(record) => record.id} renderIdentity={identity} renderFields={fields} renderDetails={details} expandedId={expandedId} onExpandedChange={setExpandedId}/>;
  const renderNarrow = (items: readonly Fixture[]) => <MobileRecordCard records={items} getRecordId={(record) => record.id} renderIdentity={(record) => <><Title order={3} size="h4">{record.symbol}</Title><Text size="sm" c="dimmed">{record.account}</Text></>} renderStatus={(record) => <StatusBadge status={record.status} tone={record.tone} size="compact"/>} renderFields={fields} onDetails={(record, opener) => { setDrawerOpener(opener); setDrawerRecord(record); }} renderActions={(record) => <ResponsiveActions compact secondary={[{ label: `Copy ${record.symbol} ID`, icon: <IconCopy size={15}/>, onClick: () => undefined }]}/>}/>;
  const view = (items: readonly Fixture[]) => <ResponsiveDataView records={items} getRecordId={(record) => record.id} wide={renderWide} compact={renderCompact} narrow={renderNarrow} aria-label="Open position fixtures"/>;
  return <main className={classes.page}><Stack gap="xl"><div><Text c="cyan" fw={800} size="xs" tt="uppercase">Development preview</Text><Title order={1} size="h2">Responsive data primitives</Title><Text c="dimmed">Static fixtures only. Resize the content area or pin the sidebar to exercise container-driven presentation changes.</Text></div>
    <section className={classes.panel}><Title order={2} size="h4" mb="md">Responsive filters</Title><ResponsiveFilterToolbar primary={<TextInput label="Search positions" value={query} onChange={(event) => setQuery(event.currentTarget.value)} placeholder="Symbol or account"/>} secondary={<Select label="Status" value={status} onChange={setStatus} data={["Open", "Entry blocked", "Needs credentials"]}/>} activeFilters={active} onClearAll={clear}/></section>
    <section className={classes.panel}><Title order={2} size="h4" mb="md">Live container-responsive view</Title>{view(records)}</section>
    <section className={classes.panel}><Title order={2} size="h4" mb="md">Constrained compact and narrow previews</Title><div className={classes.forcedGrid}><div className={`${classes.constraint} ${classes.compact}`}>{view(records.slice(0, 2))}</div><div className={`${classes.constraint} ${classes.narrow}`}>{view(records.slice(0, 2))}</div></div></section>
    <section className={classes.panel}><Title order={2} size="h4" mb="md">Badge tones and states</Title><Group gap="sm"><StatusBadge status="ENABLED" tone="positive"/><StatusBadge status="PAUSED" tone="warning"/><StatusBadge status="ENTRY_BLOCKED" tone="danger"/><StatusBadge status="TRAILING_STOP_ACTIVE" tone="informational"/><StatusBadge status="TRADING_DISABLED" tone="neutral"/></Group></section>
    <section className={classes.panel}><Title order={2} size="h4" mb="md">Data states</Title><div className={classes.previewStack}><DataState state="loading"/><DataState state="empty" message="No positions match these filters."/><DataState state="error" message="The fixture request failed safely." onRetry={() => undefined}/></div></section>
  </Stack><ResponsiveDetails opened={Boolean(drawerRecord)} title={drawerRecord ? `${drawerRecord.symbol} position details` : "Position details"} onClose={() => setDrawerRecord(null)} returnFocusTo={drawerOpener}>{drawerRecord && details(drawerRecord)}</ResponsiveDetails></main>;
}
